### DISCUSSION TITLE
Access denied

### DISCUSSION THREAD

**Discussion by aleRizzolo** [rabbitmq/cluster-operator#1077] [Q&A]
Hello, I deployed a rabbitmq cluster on microk8s (local environment) with the following config:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rabbitmq
  name: cluster
spec:
  replicas: 1
  service:
    type: ClusterIP
    annotations:
       name: rabbit-service
  persistence:
    storageClassName: local-storage
    storage: 5Gi
```
The problem is that every time I try to apply an exchange, queue or a binding, I get the following error:

`[warning] <0.4773.0> HTTP access denied: user 'default_user_K3JQHfFex4eH-piuw6c' - invalid credentials]`

**Exchange**
```
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: direct
spec:
  name: direct_exchange
  type: direct
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: cluster
```
**Queue**
```
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: mail-queue
spec:
  name: mail_microservice_queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: cluster
```
**Binding**
```
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding
spec:
  source: direct_exchange # an existing exchange
  destination: mail-queue # an existing queue
  destinationType: queue # can be 'queue' or 'exchange'
  routingKey: "mail_key"
  rabbitmqClusterReference:
    name: cluster

```
Anyone knows how to solve this?
