### DISCUSSION TITLE
How to modify the management account password

### DISCUSSION THREAD

**Discussion by jiuker** [rabbitmq/cluster-operator#1093] [General]
**For questions**, please start a discussion in [RabbitMQ Discussions](https://github.com/rabbitmq/rabbitmq-server/discussions)
or send an email to [RabbitMQ Mailing list](https://groups.google.com/g/rabbitmq-users), stating that your question is regarding
RabbitMQ Cluster Operator.

There's also a `#kubernetes` channel in [RabbitMQ community Slack](https://rabbitmq-slack.herokuapp.com/).

If I modify the configuration items in the CR file, the mq instance can restart normally, but the modified account and password cannot log in to the management control page.

**Comment by ChunyiLyu** [comment]
@jiuker  I'm going to convert this issue to a discussion since this is a question.

**Comment by ChunyiLyu** [comment]
For user management in RMQ in k8s, we generally recommend using the Messaging Topology Operator and create `users.rabbitmq.com` objects: https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/users/userPreDefinedCreds.yaml

You can also import definitions if that fits your use case: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-https-url-definition

If you have to set credentials for the default user, you can create a default user secret first with the expected username and password before you create the rabbitmqcluster.  For example, if your rabbitmqcluster name is `sample`, you can create a secret, in the same namespace called `sample-default-user`:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-default-user
type: Opaque
stringData:
  username: guest-user
  password: guest-pass
  default_user.conf: |
    default_user = guest-user
    default_pass = guest-pass
``` 
Then you can create the rabbitmqcluster. There is no need to set the username&password in the rmq manifest with this approach.
