### DISCUSSION TITLE
Are there any other sources of the Grafana Dashboards?

### DISCUSSION THREAD

**Discussion by m0sh1x2** [rabbitmq/cluster-operator#1095] [Q&A] [answered]
Hello,

I am making a few tests and spinning up some clusters in order to verify that the dashboards/alarms are working fine but I noticed that some Grafana Dashboard ConfigMaps are directly pointing to remote URLs, for example:

```yaml
data:
  # https://grafana.com/grafana/dashboards/11350
  erlang-memory-allocators-dashboard.json.url: https://grafana.com/api/dashboards/11350/revisions/5/download
```
Source: https://github.com/rabbitmq/cluster-operator/tree/main/observability/grafana/dashboards

By any chance is there another repo/source that might be the source of truth for dashboard configurations because I constantly get RateLimited by the Grafana Cloud:

```shell
bash-5.1$ wget https://grafana.com/api/dashboards/10991/revisions/11/download
Connecting to grafana.com (34.120.177.193:443)
wget: server returned error: HTTP/1.1 429 Too Many Requests
```

Thanks!
