### DISCUSSION TITLE
Bitnami RabbitMQ Cluster Operator doesn't spawn a service

### DISCUSSION THREAD

**Discussion by IonitaCatalin** [rabbitmq/cluster-operator#1101] [Q&A]
Hello! I am quite new to operators.

I have deployed a RabbitMQ in EKS using cluster operator [bitnami helm chart](https://artifacthub.io/packages/helm/bitnami/rabbitmq-cluster-operator).
Everything seems to be working but I don have a service for the cluster operator.

```
clusterOperator:
  image:
    registry: docker.io
    repository: bitnami/rabbitmq-cluster-operator
    tag: 1.14.0-scratch-r1
    pullPolicy: IfNotPresent
    pullSecrets: []

  replicaCount: 3
  topologySpreadConstraints: []
  terminationGracePeriodSeconds: 120
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  startupProbe:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 5
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
  resources:
    limits: {}
    requests: {}
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    readOnlyRootFilesystem: true

  args: []
  hostAliases: []
  podLabels: {}
  podAnnotations: {}
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    values: []
  affinity: {}
  nodeSelector: 
    beta.kubernetes.io/instance-type: t3a.medium
  updateStrategy:
    type: RollingUpdate
  priorityClassName: ""
  lifecycleHooks: {}

  containerPorts:
    metrics: 9782

  extraEnvVars: []
  extraEnvVarsCM: "rabbitmq-operator-definitions-cm"
  extraEnvVarsSecret: ""
  extraVolumes: 
    - name: definitions
      configMap:
        name: rabbitmq-operator-definitions-cm
  extraVolumeMounts: 
    - mountPath: /opt/rabbitmq
      name: definitions
  sidecars: []
  initContainers: []

  rbac:
    create: true

  serviceAccount:
    create: true
    name: ""
    annotations: {}
    automountServiceAccountToken: true

  metrics:
    enabled: false
    service:
      type: ClusterIP
      ports:
        http: 80
      nodePorts:
        http: ""
      clusterIP: ""
      extraPorts: []
      loadBalancerIP: ""
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.clusterOperator.metrics.service.ports.http }}"
      sessionAffinity: None
      sessionAffinityConfig: {}
    serviceMonitor:
      namespace: "rabbit-test"
      jobLabel: app.kubernetes.io/name
      honorLabels: true
      selector: {}
      scrapeTimeout: ""
      interval: ""
      metricRelabelings: []
      relabelings: []
      labels: 
        release: prometheus
```
