### DISCUSSION TITLE
missing required field "containers" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.override.statefulSet.spec.template.spec

### DISCUSSION THREAD

**Discussion by alexey-gavrilov-flant** [rabbitmq/cluster-operator#1220] [Q&A] [answered]
## Describe the bug
containers should not be a required parameter

## To Reproduce
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            priorityClassName: production-medium
```

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**
I don't want to override containers

## Version and environment information
- RabbitMQ: [latest]
- RabbitMQ Cluster Operator: [2.0.0]
- Kubernetes: [1.21.0]
- Cloud provider or hardware configuration:
 
## Additional context
```
error: error validating "/tmp/00.yaml": error validating data: ValidationError(RabbitmqCluster.spec.override.statefulSet.spec.template.spec): missing required field "containers" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.override.statefulSet.spec.template.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by alexey-gavrilov-flant** [comment]
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            priorityClassName: production-medium
            containers:
            - name: empty
              image: nginx:1.23.3-alpine-slim
              securityContext:
                runAsUser: 0
```
here is a working version, but it looks ugly
