### DISCUSSION TITLE
Override / Service configuration for LoadBalancerIP

### DISCUSSION THREAD

**Discussion by james-nofrixion** [rabbitmq/cluster-operator#1224] [Q&A] [answered]
HI, I've a test deployment of a RabbitMQ cluster with `spec.service.type = LoadBalancer`. It is running fine but I would like to specify the load balancer IP so it doesn't change. For a normal kubernetes service, I just set the `spec.LoadBalancerIP` field to the required value. I can't find any information on setting this via the cluster operator. Is this possible?

I've tried setting the following to no avail:
```
RabbitmqCluster,spec.service.LoadBalancerIP
RabbitmqCluster.spec.override.service.spec.LoadBalancerIP
```
My cluster is in Azure Kubernetes Service, here is my manifest for the RabbitMQ cluster:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-dev
spec:
  image: masstransit/rabbitmq:latest
  replicas: 3
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"   # only expose to AKS vnet
  persistence:
  # storageClassName:   # take default for time being (Azure Disk)
    storage: 1Gi
  resources:            # It is recommended to keep the memory requests and limits as the same value.
    requests:
      cpu: 500m         # default 2000m => minimum for production workloads
      memory: 1Gi       # default 2Gi
    limits:             # defaults as for requests
      cpu: 500m          
      memory: 1Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_consistent_hash_exchange
      - rabbitmq_delayed_message_exchange
    additionalConfig: |
      disk_free_limit.absolute = 50MB
  tls:
    secretName: dev-internal-tls-secret
    disableNonTLSListeners: false
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              networking/allow-internet-access: "true"
```

**Comment by DanielePalaia** [comment, marked as answer]
Hi @james-nofrixion based on the crd it should be:
RabbitmqCluster.spec.override.service.spec.loadBalancerIP

```
Something like:
kind: RabbitmqCluster
metadata:
  name: hello-world
spec:
  service:
    type: LoadBalancer
  override:
    service:
      spec:
        loadBalancerIP: 70.37.78.36 
```

Is it not working for you?
