### DISCUSSION TITLE
How to override volumeClaimTemplates to null/empty/undefined?

### DISCUSSION THREAD

**Discussion by udhos** [rabbitmq/cluster-operator#1315] [Q&A] [answered]
I am trying to override the statefulset's volumeClaimTemplates with `volumeClaimTemplates: null`, as depicted in full below.

However it is not affecting the statefulset's volumeClaimTemplates.

My use case is to simplify management of the staging environment where we don't need to persist any rabbitmq data for more than half a day, since our staging EKS cluster is terminated daily at night to save costs. I also tried the local-path-provisioner but it has its own challenges with nodes that are deactivated while leaving stale PVCs around: rabbitmq statefulsel gets in trouble trying to mount the stale PVCs at every morning when the cluster is activated.

Please advise on how to disable volumeClaimTemplates.

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  rabbitmq:
    additionalPlugins:
    - rabbitmq_management
    - rabbitmq_federation_management
    #- rabbitmq_peer_discovery_k8s
    additionalConfig: |
      # cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      # cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      # cluster_formation.k8s.address_type = hostname
      # vm_memory_high_watermark_paging_ratio = 0.85
      # cluster_formation.node_cleanup.interval = 10
      # cluster_partition_handling = autoheal
      # queue_master_locator = min-masters
      loopback_users.guest = false
      #default_user = guest
      #default_pass = guest
      #load_definitions = /federation/definitions.json # Path to the mounted definitions file
    advancedConfig: ""
  persistence: null
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              resources:
                requests:
                  ephemeral-storage: "1Gi"
                limits:
                  ephemeral-storage: "1Gi"
              volumeMounts:
              - mountPath: /var/lib/rabbitmq/mnesia/
                name: persistence
            volumes:
            - name: persistence
              emptyDir: {}
        volumeClaimTemplates: null
```
