### DISCUSSION TITLE
Creating a cluster from existing PVCs

### DISCUSSION THREAD

**Discussion by oberstet** [rabbitmq/cluster-operator#1401] [Q&A]
Hi all,

I've been trying to figure out how to create a simple RabbitMQ cluster with 3 nodes using the RabbitMQ Cluster Operator with **pre-existing PVCs** `data-rabbitmq-0`, `data-rabbitmq-1` and `data-rabbitmq-2`.

Each RabbitMQ node 0, 1, 2 should only use the respective `data-rabbitmq-0`, `data-rabbitmq-1` and `data-rabbitmq-2` PVC.

No PVCs must be created dynamically.

How do I do that?

Is there an option to specify something like this (doesn't work, just to illustrate what I am looking for):

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: hello-world
spec:
  replicas: 3
  pvcs:
    - data-rabbitmq-0
    - data-rabbitmq-1
    - data-rabbitmq-2
```

I've read the docs, examples, tried various things, no luck:( I'm not even sure the operator is able to or designed to do that.

How are people running multi node clusters on pre-provisioned storage, with volumes dedicated to RabbitMQ nodes (which seems crucial for high performance clustered storage on RabbitMQ)?

Any hints or help would be greatly appreciated!

Cheers,
/Tobias

**Comment by Zerpet** [comment]
This is tricky, although could be possible with some clever naming. It is complicated because the Operator uses `VolumeClaimTemplate` from the StatefulSet, [see here](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#components):

```yaml
# ...
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
```

The statefulset controller then creates the PVCs and mount thems to each Pod. It is challenging to define each PVC for each Pod "manually" because the statefulset uses a Pod template; this has the implications that all Pods will be "replicas" of each other, just with a different Pod name, volumes and volume mounts will be identical. The `VolumeClaimTemplate` solves this problem, as it attaches one PVC for each Pod.

How do you run on pre-provisioned storage? You can create your PVCs with the names that the StatefulSet controller will attempt to create. IIRC, it follows the pattern `persistence-<rabbitmqcluster-name>-<index>` where `rabbitmqcluster-name` would be `hello-world` in your example, and `index` is the index for each replica, starting at 0. For example, if you have 3 replicas, indexes would be 0, 1 and 2. By pre-creating the PVCs, the StatefulSet will just use them. Be aware tho, that if you delete the `RabbitmqCluster`, the PVCs will be deleted as well.

As an alternative to all this trickery, you could define a `StorageClass` ([see docs](https://kubernetes.io/docs/concepts/storage/storage-classes/)) with a provisioner for your high performace storage, and set that name in the storage class field in `RabbitmqCluste` spec.
