### DISCUSSION TITLE
Need help on upgrade

### DISCUSSION THREAD

**Discussion by archana-elrod** [rabbitmq/cluster-operator#1412] [General]
I'm new to both k8s and RabbitMQ, I wonder if someone can help me with the upgrade issues I'm having.
I've upgraded cluster-operator v1.12.1 to v1.13.0 by executing 
`kubectl apply -f cluster-operator.yaml`
where cluster-operator.yaml is from Release v1.13.0. Next I ran following
```kubectl rollout status deployment/rabbitmq-cluster-operator
kubectl apply -f pdb.yaml
kubectl apply -f rabbitmq.yaml
kubectl rollout status statefulset/rabbitmq-server
```
pdb.yaml
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: #{Cluster.Name}
  namespace: #{Cluster.Namespace}
spec:
  minAvailable: 4 # the minimum required quorum + 1 (what the rabbitmq prestop hook waits for on shutdown)
  selector:
    matchLabels:
      app.kubernetes.io/name: #{Cluster.Name}
```
rabbitmq.yaml
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: #{Cluster.Name}
  namespace: #{Cluster.Namespace}
spec:
  override:
    statefulSet:
      spec:
        podManagementPolicy: Parallel
        template:
          spec:
            containers: []
            topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: #{Cluster.Name}
              maxSkew: 2
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
  persistence:
    storage: #{PersistenceStorage.Size}
    storageClassName: #{PersistenceStorage.StorageClassName}
  rabbitmq: #https://www.rabbitmq.com/memory.html#paging for vm_memory_high_watermark
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.9
      vm_memory_high_watermark.relative = 0.8
      disk_free_limit.relative = 1.0
      log.file.level = warning
      default_user = admin
      default_pass = admin
  replicas: #{Replicas.Count}       # num replicas should be at least quorum+2 since rabbitmq prestop hook waits for quorum+1 to be
  resources:                        # ready when shutting down, and must be at least 1 more than PDB's minAvailable or it would be
    limits:                         # unable to drain a node with rabbitmq on it
      cpu: #{Resources.CPU.Limit}
      memory: #{Resources.Memory.Limit}
    requests:
      cpu: #{Resources.CPU.Request}
      memory: #{Resources.Memory.Request}
```
When I check the rabbitmq-server-# nodes, I see RabbitMQ 3.8.19 and Erlang 24.0.5, which I believe should have been RabbitMQ 3.9.X as per cluster-operator release v.1.12.0. I am clueless on what am I missing such that RabbitMQ server is not upgrading? 
My k8 server version is at v1.26.3, please let me know if you need more info and wonder if someone can help me on RabbitMQ server not being bumped up when bumping up cluster-operator.
