### DISCUSSION TITLE
rabbitmq_delayed_message_exchange Plugin

### DISCUSSION THREAD

**Discussion by 3rk1n** [rabbitmq/cluster-operator#1484] [Q&A]
Hi,

We have an AKS ecosystem and we are using RabbitMQ as a cluster operator (https://github.com/rabbitmq/cluster-operator)
The development team wants to use **rabbitmq_delayed_message_exchange** plugin.

I added **additionalPlugins** in **RabbitmqCluster** and restart the deployment.

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
...
spec:
  rabbitmq:
    additionalPlugins:
    - rabbitmq_delayed_message_exchange
```

I can not see that plugin in POD plugin folders and in the plugin list.

![image](https://github.com/rabbitmq/cluster-operator/assets/50519199/bd1b83b9-d260-4b3b-9da3-e3f6ffa5a413)

![image](https://github.com/rabbitmq/cluster-operator/assets/50519199/e967ef46-4f9a-4e1e-a51e-5d14a9a5a0cd)

I checked that link (https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/community-plugins/rabbitmq.yaml) but I am not sure this is the best/correct answer.

What I am missing?

Thank you.
