### DISCUSSION TITLE
Issue with affinity and tolerations

### DISCUSSION THREAD

**Discussion by alter** [rabbitmq/cluster-operator#1582] [Q&A]
## Describe the bug
When I add affinity and tolerations sections into my rabbitmq cluster definition service fails with log:
```
rabbitmq 08:12:55.67 INFO  ==> Starting RabbitMQ in background...
rabbitmq 08:15:20.79 ERROR ==> Couldn't start RabbitMQ in background.
```
if I remove both sections - everything works perfectly, but how can you notice, I show you logs of a pod, it means that the pod itself was able to start, so there is no issue with affinity and tolerations on Kubernetes level(I also copied sections from another application, that works successfully).

## To Reproduce
1) Install the operator from the bitnami chart:
```
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.17.0
    chart: rabbitmq-cluster-operator
```
2) setup cluster with the following yaml:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  skipPostDeploySteps: true
  terminationGracePeriodSeconds: 180
  persistence:
    storageClassName: gp2 # I also tried aws efs as a storage, but it didn't help
    storage: 20Gi
  resources:
    requests:
      cpu: 150m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  tolerations:
    - key: "spotInstance"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "spotInstance"
            operator: "In"
            values:
            - "true"
  rabbitmq:
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
      - rabbitmq_prometheus
      - rabbitmq_shovel_management
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      vm_memory_high_watermark_paging_ratio = 0.85
      cluster_formation.node_cleanup.interval = 10
      cluster_partition_handling = autoheal
      queue_master_locator = min-masters
      loopback_users.guest = false
      log.console.level = debug
      default_user_tags.administrator = true
```
3) set a proper label and taint to your node:
add label **spotInstance=true**
add taint
```
  {
    "effect": "NoExecute",
    "key": "spotInstance",
    "value": "true"
  }
```

**Expected behavior**
The application(rabbitmq pod) just has to launch as it was without affinity and tolerations.

## Version and environment information
- RabbitMQ: Successfully pulled image "docker.io/bitnami/rabbitmq:3.12.12-debian-11-r10"
- RabbitMQ Cluster Operator: chart 3.17.0
- Kubernetes: v1.28.5-eks-5e0fdde
- Cloud provider or hardware configuration: AWS EKS
