### DISCUSSION TITLE
The RabbitMQ cluster does not provide high availability (HA).

### DISCUSSION THREAD

**Discussion by sdwan444** [rabbitmq/cluster-operator#1615] [Q&A]
## Describe the bug
Hello, we are experiencing an issue with our RabbitMQ cluster. We have three nodes in the cluster using the Bitnami operator. When one node goes down, we encounter errors, and some of our queues turn red (increasing by 0).

<img width="974" alt="image" src="https://github.com/rabbitmq/cluster-operator/assets/166641652/6246a662-6e8a-4d04-87eb-72929d95d7c2">
<img width="1279" alt="image" src="https://github.com/rabbitmq/cluster-operator/assets/166641652/799e27e4-0283-4ab4-bba4-302651e01c3a">
<img width="1244" alt="image" src="https://github.com/rabbitmq/cluster-operator/assets/166641652/cd6620e2-cb32-44e6-b85c-682905af2f2b">
<img width="1359" alt="image" src="https://github.com/rabbitmq/cluster-operator/assets/166641652/92f412e4-e988-4258-9f35-f89236fd2c94">

**Expected behavior**
When node is failing the messages should keep going. 
## Version and environment information
- RabbitMQ: [e.g. 3.12.12]
- RabbitMQ Cluster Operator:(rabbitmq-cluster-operator:2.7.0-debian-11-r3)
- Kubernetes: [e.g. 1.28.0]
- Cloud provider or hardware configuration: k8s with spot instance.

**Comment by lukebakken** [comment]
Hello, thanks for using RabbitMQ.

We need more information before we can assist you.

* Are you running in AWS? https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-spot-instances.html
* How _exactly_ are you configuring the RabbitMQ cluster operator in your k8s environment? Please provide your FULL configuration yaml.
* How are you stopping one node in this cluster?
* Please provide your full log files. NOT screenshots. _ATTACH_ your compressed log files to this discussion.

**Reply by sdwan444** [reply]
Hey, Thx for the quick response, unfortunately i can't share the log file publicly.

The node stops because of spot switch with evict. and it does a "drain" action. 

The yml is:

<details><summary>Yaml</summary>

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  spec:
  delayStartSeconds: 30
  image: docker.io/bitnami/rabbitmq:3.12.12-debian-11-r10
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
              - labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: rabbitmq
                maxSkew: 10
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: ScheduleAnyway
  persistence:
    storage: 20Gi
    storageClassName: gp3
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
      vm_memory_high_watermark.relative = 0.8
    additionalPlugins:
      - rabbitmq_amqp1_0
      - rabbitmq_management
      - rabbitmq_event_exchange
      - rabbitmq_web_dispatch
      - rabbitmq_management_agent
      - rabbitmq_stomp
      - rabbitmq_web_stomp
      - rabbitmq_web_mqtt
      - rabbitmq_mqtt
  replicas: 3
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: '1'
      memory: 3Gi
  secretBackend:
    externalSecret: {}
  service:
    type: ClusterIP
  terminationGracePeriodSeconds: 604800
```
</details>
