### DISCUSSION TITLE
Override rabbit-mq-server cluster name using override stateful set option

### DISCUSSION THREAD

**Discussion by vinvli** [rabbitmq/cluster-operator#1660] [Q&A]
Is it possible to override the stateful set name using the operator?
I want to rename rabbit-mq-server (the default) to rabbit-mq but it doesn't seem to work that way:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-mq
  namespace: rabbitmq-system
spec:
  replicas: 3
  override:
    statefulSet:
      metadata:
        **name: rabbit-mq**
  delayStartSeconds: 30
```
