### DISCUSSION TITLE
rabbitmq waiting for mnesia tables error using the cluster operator

### DISCUSSION THREAD

**Discussion by vineelaop** [rabbitmq/cluster-operator#1661] [Q&A]
The environment (AWS + k3d) where my rabbitmq is deployed gets rebooted twice a day while it automatically looks for updates, meaning both the cluster and cluster operator are deleted and redeployed. We are using persistent volumes to save rabbitmq's data. In my local environment I did not encounter this issue when I deleted and redeployed the rabbitmq cluster and operator and I haven't been able to reproduce it. The only way to fix this has been to delete the old data and redeploy the cluster again. When looking for solutions I found this [https://stackoverflow.com/questions/60407082/rabbit-mq-error-while-waiting-for-mnesia-tables](https://stackoverflow.com/questions/60407082/rabbit-mq-error-while-waiting-for-mnesia-tables). According to Michael Klishin's answer this shouldn't be happening while using the operator. Does anyone have any idea why this issue is occuring or how I can debug? Any help would be much appreciated!

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: demo
spec:
  image: rabbitmq:3.9.29-management-alpine
  replicas: 3
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user= guest 
                  default_pass = guest
                  default_user_tags.administrator = true
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - name: data-vol
                mountPath: /data
              env:
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: RABBITMQ_MNESIA_DIR
                value: "/data/$(MY_POD_NAME)"
            volumes:
            - name: data-vol
              hostPath:
                path: "/Users/Vineela/Testing/rabbitmq_demo/data"
```
