### DISCUSSION TITLE
lifecycle sleep does not work

### DISCUSSION THREAD

**Discussion by nenych** [rabbitmq/cluster-operator#1766] [General]
## Describe the bug
If we want to set the lifecycle hook to sleep before the termination - the operator will not create the resource.
Note: exec with sleep works fine.

## To Reproduce
1) Create resource
2) No resource is created by the operator

Include any YAML or manifest necessary to reproduce the problem.
```
apiVersion: "rabbitmq.com/v1beta1"
kind: "RabbitmqCluster"
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: "rabbitmq"
                lifecycle:
                  preStop:
                    sleep:
                      seconds: 10
```

**Expected behavior**
RabbitMQ pod with the lifecycle hook

## Version and environment information
- RabbitMQ: 3.10.7-debian-11-r8
- RabbitMQ Cluster Operator: 2.9.0-debian-12-r2
- Kubernetes: v1.30.5
- Cloud provider or hardware configuration: GCP
