### DISCUSSION TITLE
Changing default ports

### DISCUSSION THREAD

**Discussion by olegans1972** [rabbitmq/cluster-operator#1843] [General]
Is is possible  to change default ports to another value? For example  management set to 15673? I tried  this https://www.rabbitmq.com/kubernetes/operator/using-operator#override it allows me  create additional ports, but if I set something like this 

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{va_rmq_cluster}}
  namespace: {{k8s_resource_namespace}}
spec:
  override:
    service:
      spec:
        ports:
          - name: management
            protocol: TCP
            port: 15673
            targetPort: 15673
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                ports:
                  - containerPort: 15673 
                    name: management
                    protocol: TCP        


---
```

I got mistake : `invalid: spec.ports[2].name: Duplicate value: \"management\""`

`{"level":"error","ts":"2025-03-23T10:58:54Z","msg":"Reconciler error","controller":"rabbitmqcluster","controllerGroup":"rabbitmq.com","controllerKind":"RabbitmqCluster","RabbitmqCluster":{"name":"va-rmq","namespace":"va"},"namespace":"va","name":"va-rmq","reconcileID":"6262cb65-d45d-417b-8f30-46c823567a06","error":"Service \"va-rmq\" is invalid: spec.ports[2].name: Duplicate value: \"management\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/bitnami/blacksmith-sandox/rabbitmq-cluster-operator-2.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/bitnami/blacksmith-sandox/rabbitmq-cluster-operator-2.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/bitnami/blacksmith-sandox/rabbitmq-cluster-operator-2.8.0/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227"}
`

**Comment by mkuratczyk** [comment]
You'd also need to reconfigure RabbitMQ as well, to actually listen on different ports. I don't think we ever tested changing the default ports though. Why would you want to do that?

**Comment by olegans1972** [comment]
I use two rabbitMQs at the same k3s cluster, this k3s cluster uses cloud VMs, and this cloud doesn't support metallb function. So my rabbitMQs works as LB and uses the same IPs))

````
[ GPBMOBILE ] [12:06]:[opodguyko@sifox-k3s-c1s1-1 ~]$ sudo kubectl get svc -A | grep rmq
cpaas             cpaas-rmq                                                         LoadBalancer   10.43.141.60    172.31.90.10,172.31.90.11,172.31.90.12,172.31.90.13,172.31.90.14,172.31.90.15,172.31.90.4,172.31.90.5,172.31.90.6,172.31.90.7,172.31.90.8,172.31.90.9   15672:30772/TCP,15692:31285/TCP,5672:32764/TCP                                                                   5d4h
cpaas             cpaas-rmq-nodes                                                   ClusterIP      None            <none>                                                                                                                                                  4369/TCP,25672/TCP                                                                                               5d4h
va                va-rmq                                                            LoadBalancer   10.43.248.179   <pending>                                                                                                                                               15673:31521/TCP,15672:30794/TCP,15692:32185/TCP,5672:30304/TCP                                                   21h
va                va-rmq-nodes                                                      ClusterIP      None            <none>                                                                                                                                                  4369/TCP,25672/TCP                                                                                               21h
[ GPBMOBILE ] [12:06]:[opodguyko@sifox-k3s-c1s1-1 ~]$ 
````
As you see the cpaas-rmq  has external IPs (group of IPs) but the va-rmq doesn't have....This happens because the second rabbitMQ is trying to occupy a port that is already in use. I thought I could separate them by ports. You wrote that I can reconfigure RabbiMQ. Сould you explain more deeper?

**Reply by mkuratczyk** [reply]
You can learn more about how to configure RabbitMQ in the docs, eg.  https://www.rabbitmq.com/docs/networking#interfaces (but each listener/protocol needs to be configured). Or check the cluster-operator source code to see how we configure some of the ports (eg. add ports when a given plugin is enabled).

But honestly, containers were pretty much invented to solve this kind of problems - each container has its own IP and you can easily run multiple instances using the same port numbers, because they are not the same IP:PORT pairs. I see no reason to allow reconfiguring the default ports. Quite likely it's already possible with some RabbitMQ configuration + `spec.override` settings, but I'm not going to spend any more time on this.

**Comment by olegans1972** [comment]
Thank you for your help! I found a better solution for myself. At default service I set  service as ClusterIP  and the default service stopped binding to the common address. After it I created new service which used another ports:

````
---
apiVersion: v1
kind: Service
metadata:
  name: {{va_rmq_cluster}}-external
  namespace: {{k8s_resource_namespace}}
spec:
  type: LoadBalancer
  ports:
  - name: management
    port: 15673
    protocol: TCP
    targetPort: 15672
  - name: amqp
    port: 5673
    protocol: TCP
    targetPort: 5672
  - name: prometheus
    port: 15693
    protocol: TCP
    targetPort: 15692
  selector:
    app.kubernetes.io/name: {{va_rmq_cluster}}
```

And now both rabbitMO works simultaneously without any problems!

```
[ GPBMOBILE ] [13:58]:[opodguyko@sifox-k3s-c1s1-1 ~]$ sudo kubectl get svc -A | grep rmq | grep Loa
cpaas             cpaas-rmq                                                         LoadBalancer   10.43.141.60    172.31.90.10,172.31.90.11,172.31.90.12,172.31.90.13,172.31.90.14,172.31.90.15,172.31.90.4,172.31.90.5,172.31.90.6,172.31.90.7,172.31.90.8,172.31.90.9   15672:30772/TCP,15692:31285/TCP,5672:32764/TCP                                                                   5d5h
va                va-rmq-external                                                   LoadBalancer   10.43.61.237    172.31.90.10,172.31.90.11,172.31.90.12,172.31.90.13,172.31.90.14,172.31.90.15,172.31.90.4,172.31.90.5,172.31.90.6,172.31.90.7,172.31.90.8,172.31.90.9   15673:31022/TCP,5673:30536/TCP,15693:32539/TCP                                                                   42m
[ GPBMOBILE ] [13:58]:[opodguyko@sifox-k3s-c1s1-1 ~]$ 
```
