### DISCUSSION TITLE
High watermark memory usage never goes down (using a quorom queue)

### DISCUSSION THREAD

**Discussion by dsaintilma-flinks** [rabbitmq/cluster-operator#815] [General]
## Describe the bug
High watermark memory usage never goes down (using a quorum queue) although there's very low to no message in the queue.

## To Reproduce
- Setup and use a quorum queue

### Deployment (for the RabbitMQCluster)
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq
spec:
  persistence:
    storage: 20Gi
    storageClassName: standard
  replicas: 3
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  terminationGracePeriodSeconds: 60

```
**Expected behavior**
For the memory to purge itself but it keeps slowly going up.

## Screenshots
![Screenshot from 2021-08-20 11-08-21](https://user-images.githubusercontent.com/85182091/130254255-29430218-90df-407e-9613-e01e979f6f35.png)

## Version and environment information
- RabbitMQ: 3.8.18
- RabbitMQ Cluster Operator: 1.8.1
- Kubernetes: 1.18.20-gke.501 (control plane), 1.18.20-gke.501 (nodes)
- Cloud provider or hardware configuration: GKE
