### DISCUSSION TITLE
Configure or limit operator's logs

### DISCUSSION THREAD

**Discussion by flagsibh** [rabbitmq/cluster-operator#849] [Q&A] [answered]
Hi.

I've already configure the log verbosity and level of the RabbitMq Cluster with a snippet like this:

```yaml
spec:
  rabbitmq:
    additionalConfig: |
      log.default.level = warning
      log.file.level = warning
      log.console.level = warning
      log.connection.level = warning
```

And it's rocking fine. Okay.

My question is: how can I do the same with the cluster-operator and the messaging-topology-operator themselves? Is there any way to restrict the log level?

Thank you very much.

**Comment by Zerpet** [comment, marked as answer]
There's a not-so-great approach to set the log level to `error`. You can modify the Deployment manifest and add the following (abbreviated):

```yaml
spec:
  template:
    spec:
      containers:
      - command:
         - /manager
        args:
        - --zap-log-level=error
```

The accepted values for this flag are `debug`, `info` and `error`. There's no warning in the standard levels that we use in the code. Be aware that changing the log level will make harder to debug the operators.

Edit: hit enter too soon :(
