### DISCUSSION TITLE
additionalConfig doesnt seem to work [atleast for me]

### DISCUSSION THREAD

**Discussion by vitarkah** [rabbitmq/cluster-operator#875] [Q&A]
Additional config looks like this
`  rabbitmq:
    additionalConfig: |
      channel_max = 1050
      loopback_users.guest = true
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000`

and this is what I see in see
`rabbitmq@rabbitmq-cluster-server-0:/$ cat /etc/rabbitmq/conf.d/90-userDefinedConfiguration.conf
total_memory_available_override_value = 1717986919
channel_max                           = 1050
loopback_users.guest                  = true
cluster_partition_handling            = pause_minority
vm_memory_high_watermark_paging_ratio = 0.99
disk_free_limit.relative              = 1.0
collect_statistics_interval           = 10000`

But getting this
PLAIN login refused: user 'guest' - invalid credentials

What am i missing?

**Comment by ChunyiLyu** [comment]
@vitarkah Are you trying to set credentials for the default user?

For user management in RMQ in k8s, we generally recommend using the Messaging Topology Operator and create `users.rabbitmq.com` objects: https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/users/userPreDefinedCreds.yaml

You can also import definitions if that fits your use case: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-https-url-definition

If you have to set credentials for the default user, you can create a default user secret first with the expected username and password before you create the rabbitmqcluster.  For example, if your rabbitmqcluster name is `sample`, you can create a secret, in the same namespace called `sample-default-user`:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-default-user
type: Opaque
stringData:
  username: guest-user
  password: guest-pass
  default_user.conf: |
    default_user = guest-user
    default_pass = guest-pass
``` 
Then you can create the rabbitmqcluster. There is no need to set the username&password in the rmq manifest with this approach.
