### DISCUSSION TITLE
support set securityContext

### DISCUSSION THREAD

**Discussion by alochym01** [rabbitmq/cluster-operator#881] [Q&A] [answered]
error: error validating "rabbitmq-cluster.yaml": error validating data: ValidationError(RabbitmqCluster.spec): unknown field "securityContext" in com.rabbitmq.v1beta1.RabbitmqCluster.spec; if you choose to ignore these errors, turn validation off with --validate=false
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbit-alochym
    namespace: rabbitmq-system
spec:
    securityContext:
        fsGroup: 1000
        runAsUser: 1000    
    replicas: 1
    persistence:
        storageClassName: local-storage
        storage: 10Gi    
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      #value: "rabbitmq"
      effect: "NoSchedule"    
      # node-role.kubernetes.io/master:NoSchedule
    resources:
        requests:
            cpu: 500m
            memory: 1Gi
        limits:
            cpu: 4000m
            memory: 8Gi
```

**Comment by Zerpet** [comment, marked as answer]
You can configure the security context via StatefulSet override, something like this:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmqcluster
spec:
  # Any properties you already have +
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
            securityContext:
              fsGroup: 1000
              runAsUser: 1000
```

We do not plan to add the security context as a top level proeprty in our Spec for now.
