### DISCUSSION TITLE
Support of priorityClassName

### DISCUSSION THREAD

**Discussion by timbrd** [rabbitmq/cluster-operator#892] [Q&A] [answered]
My k8s cluster is running several RabbitMQ clusters - a production and 3 development clusters.
I would like to define a priority class for my RabbitMQ pods to prioritise the production cluster when resources are low.

In the operator documentation I could not find a way to set a priority class, so I guess it is currently unsupported?

**Comment by mkuratczyk** [comment, marked as answer]
You should be able to set `priorityClassName` through `.spec.override.statefulSet`: https://www.rabbitmq.com/kubernetes/operator/using-operator.html#override

**Reply by timbrd** [reply]
> You should be able to set `priorityClassName` through `.spec.override.statefulSet`: https://www.rabbitmq.com/kubernetes/operator/using-operator.html#override

Thanks, overriding the container part of the statefulset worked.

**Reply by landbaychrisburrell** [reply]
Would there be any chance to share an example for posterity?

**Reply by dankolt** [reply]
This snippet works for me:
```yaml
override:
  statefulSet:
    spec:
      template:
        spec:
          priorityClassName: "your-priority-class"
          containers:
            - name: rabbitmq
```
Keep in mind that `containers:` field is required when you override `.statefulSet.spec.template.spec` block
