### DISCUSSION TITLE
add `RabbitmqCluster.spec.persistence.selector` to select PV to bind

### DISCUSSION THREAD

**Discussion by wenmingwei** [rabbitmq/cluster-operator#939] [Q&A] [answered]
Feature Requirement:
> add `RabbitmqCluster.spec.persistence.selector` to select PV to bind

Backgroud:
> I allocated RabbitmqCluster and cluster of other product on same nodes to share resources, when I created local-storage PV for each cluster(one PV for RabbitmqCluster and one PV for cluster of other product).
> But I cannot bind RabbitmqCluster.spec.persistence to specified PV which is labeled.
>

**Comment by Zerpet** [comment, marked as answer]
The cluster operator creates a PVC dynamically using the [StatefulSet volume claim template field](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates). We did not consider static provisioned PVs as an option, and it makes more sense to support mainly dynamic PV provisioning.

If you still want to use the PV you created, you can override the PVC claim with the StatefulSet override feature, something like this:

```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmqcluster
spec:
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
          - spec:
              accessModes:
                - ReadWriteOnce
              selector:
                matchLabels:
                  rabbitmq: mylabel
              resources:
                requests:
                  storage: "15Gi"
            metadata:
              name: persistence
  persistence:
    storage: "15Gi"
```

The field `.spec.override.statefulSet.spec.volumeClaimTemplate[].metadata.name` is required and must be set to that value. You can tune the storage request and the label selector. Hope this helps!

**Comment by vinu1421** [comment]
@Zerpet What if we need to have more than one replica, will this work?

**Comment by Zerpet** [comment]
As long as you have sufficient PVs with the label in your selector, it should. Note that a single PV won't be claimed by two Pods, given the access mode defined, neither you should allow more than one RabbitMQ Pod access the same PV.

**Comment by vinu1421** [comment]
@Zerpet We already have an existing PV and tried what you have suggested, But getting below error
`claim.Spec.Selector is not supported for dynamic provisioning on GCE`
Seems like it is trying dynamic provisioning

**Reply by Zerpet** [reply]
That behaviour seems specific to GCE. My guess is GCE may have an option to configure this behaviour. I'd suggest to ask in their community or support service whether this is possible; providing them with the StatefulSet YAML created by the Operator might help.

**Reply by vinu1421** [reply]
@Zerpet I was able to resolve this issue using like  below 

```
spec:
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
          - spec:
              storageClassName: ""
              accessModes:
               - ReadWriteOnce
              resources:
                requests:
                  storage: "10Gi"
            metadata:
              name: persistence
  replicas: 3
```
And using proper claimref in PV 

```
  claimRef:
    namespace: rabbitmq
    name: persistence-rabbitmq-server-0
```

so adding an empty storageClassName is disabling the dynamic provisioning i think.
