### DISCUSSION TITLE
Admin user access issue

### DISCUSSION THREAD

**Discussion by sujithpaily** [rabbitmq/cluster-operator#952] [Q&A]
I have deployed a RabbitMQ in EKS using cluster operator. It was working fine and suddenly I noticed admin login not working and it was showing error
 HTTP access denied and No administrator tags
The admin user was added via following configuration(not the default user)
 
 
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name:rabbitmq-cluster
  namespace: rabbitmq
spec: 
  replicas: 3
  persistence:
   storageClassName: sc-data-encrypted-az2
   storage: 20Gi
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 300m
      memory: 1Gi
  rabbitmq:
          additionalConfig: |
                  log.console.level = info
                  channel_max = 1700
                  default_user= admin
                  default_pass = *******
                  default_user_tags.administrator = true
```

**Comment by Zerpet** [comment]
RabbitMQ configures the default username, password and tags during the first time it starts up, when it forms its internal database. Looking at any events that occurred before the password stopped working would help to determine what may have happened.

**Comment by ChunyiLyu** [comment]
@sujithpaily For user management in RMQ in k8s, we generally recommend using the Messaging Topology Operator and create `users.rabbitmq.com` objects: https://github.com/rabbitmq/messaging-topology-operator/blob/main/docs/examples/users/userPreDefinedCreds.yaml

You can also import definitions if that fits your use case: https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-https-url-definition

If you have to set credentials for the default user, you can create a default user secret first with the expected username and password before you create the rabbitmqcluster.  For example, if your rabbitmqcluster name is `sample`, you can create a secret, in the same namespace called `sample-default-user`:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-default-user
type: Opaque
stringData:
  username: guest-user
  password: guest-pass
  default_user.conf: |
    default_user = guest-user
    default_pass = guest-pass
``` 
Then you can create the rabbitmqcluster. There is no need to set the username&password in the rmq manifest with this approach.
