### DISCUSSION TITLE
How to remove a port from the service?

### DISCUSSION THREAD

**Discussion by jkager** [rabbitmq/cluster-operator#967] [Q&A] [answered]
The [additional port example](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/additionalPorts) shows how to add a port to the service deployed by the cluster operator.

I need the opposite: I want to remove the Prometheus port from the service, since I publish the service outside of the cluster and don't want to publish internal metrics to the world. But I can't figure out how to do that, and I can't find anything in the documentation.

The example indicates that the overrides will be applied using strategic merge patch, so I unsuccessfully tried this override:

```yml
override:
  service:
    spec:
      ports:
        - $patch: delete
          name: prometheus-tls
          port: 15691
```

So I tried to patch the service after deployment, using this patch file:

```yml
spec:
  ports:
    - $patch: delete
      name: prometheus-tls
      port: 15691
```

which gives me the desired result when I do a dry run like this:

    kubectl patch service rabbitmq --type=strategic --patch-file patch.yml --dry-run -o yaml

But when I actually apply the patch to the service, it has no effect - I suspect that the cluster operator overwrites my change again?

Am I overlooking something? Is there any supported way to remove the port? Or do I need to publish an additional service manually?
