### DISCUSSION TITLE
Add hostpath volume to RabbitMQ `RabbitmqCluster`

### DISCUSSION THREAD

**Discussion by asoleimanibo** [rabbitmq/cluster-operator#971] [Q&A] [answered]
I want to persist a path on Kubernetes worker. In regular Kubernetes deployment, I can add a volume like this:

```
volumes:
  - name: logs
    hostPath:
        path: /var/log
```

how can I add `hostpath` volume to `RabbitmqCluster` ?
