### ISSUE TITLE
Missing Exchange Api Resource from rabbitmq.com/v1beta1

### ISSUE THREAD

**Issue by molupini** [rabbitmq/cluster-operator#1012]
## Missing Exchange Api Resource from rabbitmq.com/v1beta1

Missing api resources see https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html except for **rabbitmqclusters**
Unable to create exchange, queue etc 

In the example below when executed I get the below exception -- see screenshot  

```
❯ kubectl apply -f overlays/environments/rabbitmq/base/exchange.yaml
error: unable to recognize "overlays/environments/rabbitmq/base/exchange.yaml": no matches for kind "Exchange" in version "rabbitmq.com/v1beta1"
```

## To Reproduce
1. install the rabbitmq operator 
2. install the rabbitmq cluster
3. try to install a rabbitmq exchange as per reference documentation
4. missing api resources -- see screenshot

Include YAML to reproduce the problem.

crd 
```
namespace: rabbitmq-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/download/v1.12.0/cluster-operator.yml
```
cluster
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  replicas: 3
  image: rabbitmq:3.9-management
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
  rabbitmq:
    additionalPlugins:
    - rabbitmq_stream
    - rabbitmq_prometheus
    additionalConfig: |
      # https://www.rabbitmq.com/configure.html
      vm_memory_high_watermark.absolute = 7GB
      vm_memory_high_watermark_paging_ratio = 0.99
      # Statistics collection interval in milliseconds (default=5000)
      collect_statistics_interval = 10000
      # supported values: basic, detailed, none
      # default=basic
      management.rates_mode = basic
      # defaults: 5, 60, 1800
      management.sample_retention_policies.global.minute = 10
      management.sample_retention_policies.global.hour = 300
      management.sample_retention_policies.global.day = 1800
      # defaults: 5, 60
      management.sample_retention_policies.basic.minute = 10
      management.sample_retention_policies.basic.hour = 300
      # management metrics can be disabled altogether
      # TODO: disable if saving required. 
      management_agent.disable_metrics_collector = false
      # default:  5
      management.sample_retention_policies.detailed.10 = 60
```
exchange 
```
# https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html#exchanges-bindings
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: delayed
  namespace: messaging
spec:
  name: 
  type: direct
  autoDelete: false
  durable: true
  # TODO: unsure how to specify args
  # args:  
  #   x-delayed-type: direct
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: messaging
```

**Expected behavior**
Expecting the api resources to be available as per documentation 
https://www.rabbitmq.com/kubernetes/operator/using-topology-operator.html

## Screenshots
error when creating exchange
![image](https://user-images.githubusercontent.com/48324091/162178201-ad2ee5b3-61af-4a4d-a578-4314e140586b.png)
list of api-resources -- notice missing resouces 
![image](https://user-images.githubusercontent.com/48324091/162175047-967ccf20-c1bc-4096-8f40-c51aa78d679e.png)
forced to create the exchange manually -- this is not desirable.
![image](https://user-images.githubusercontent.com/48324091/162182707-96fc4979-9130-411c-828f-ac7f59a98a2e.png)

## Version and environment information
- RabbitMQ: 3.9.13
- RabbitMQ Cluster Operator: 1.12.0
- Kubernetes: v1.22.3+fdba464
- Cloud provider or hardware configuration: see below 
```
❯ oc get clusterversion -o wide
NAME      VERSION                         AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.9.0-0.okd-2022-02-12-140851   True        False         36d     Cluster version is 4.9.0-0.okd-2022-02-12-140851
```
 
## Additional context
Unsure how to create exchange with arguments, please advise.
