### ISSUE TITLE
user secret not updated when creating cluster with default_user config

### ISSUE THREAD

**Issue by heimdull** [rabbitmq/cluster-operator#1018]
## Describe the bug
When using the default_user/default_pass the kubernetes secret is not updated. When using the messaging-topology-operator with a set default_user you will get a 401 because it looks at the secret.

## To Reproduce
deploy cluster with this additionalConfig:

spec:
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest

**Expected behavior**
secret is used by other operators so it needs to be updated

## Version and environment information
latest operator

**Comment by ChunyiLyu** [comment]
@heimdull This is a known limitation with the operator. I could treat this as a feature request and discuss with the rest of the team.

Meanwhile, for a workaround, you could either update the secret manually yourself after the rmq is created. Or, you can create a default user secret first with the expected username and password before you create the rabbitmqcluster.  For example, if your rabbitmqcluster name is `sample`, you can create a secret, in the same namespace called `sample-default-user`:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-default-user
type: Opaque
stringData:
  username: guest-user
  password: guest-pass
  default_user.conf: |
    default_user = guest-user
    default_pass = guest-pass
``` 
Then you can create the rabbitmqcluster. There is no need to set the username&password in the rmq manifest with this approach.
