### ISSUE TITLE
How to set the timeoutSeconds of readiness probe in RabbitmqCluster yaml file

### ISSUE THREAD

**Issue by zhenghan008** [rabbitmq/cluster-operator#1019]
**For questions**, please start a discussion in [RabbitMQ Discussions](https://github.com/rabbitmq/rabbitmq-server/discussions)
or send an email to [RabbitMQ Mailing list](https://groups.google.com/g/rabbitmq-users), stating that your question is regarding
RabbitMQ Cluster Operator.

There's also a `#kubernetes` channel in [RabbitMQ community Slack](https://rabbitmq-slack.herokuapp.com/).
hi, teams！please tell me how to set the timeoutSeconds of readiness probe in RabbitmqCluster yaml file. thanks!

**Comment by coro** [comment]
This is a statefulSet property, so can be overridden using the `rabbitmqCluster.spec.override.statefulSet` property. In your case, your yaml will look like:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: override-probe
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              readinessProbe:
                timeoutSeconds: 999
```
