### ISSUE TITLE
Missing vhost CRD

### ISSUE THREAD

**Issue by danielkucera** [rabbitmq/cluster-operator#1022]
## Describe the bug
I am trying to configure vhost but getting an error:
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Vhost" in version "rabbitmq.com/v1beta1"
```

## To Reproduce
1. Create manifest:
```
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: amqp-vhost
spec:
  name: somevhost
  rabbitmqClusterReference:
    name: amqp
```
3. helm install
5. See error

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**
I expect the vhost to be created in cluster `amqp`

## Screenshots
N/A

## Version and environment information
- RabbitMQ: 
- RabbitMQ Cluster Operator: rabbitmqoperator/cluster-operator:1.12.1
- Kubernetes: Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10-gke.2000", GitCommit:"0823380786b063c3f71d5e7c76826a972e30550d", GitTreeState:"clean", BuildDate:"2022-03-17T09:22:22Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
 
## Additional context
list-api doesn't show the vhost object:
```
kubectl api-resources | grep rabbit
rabbitmqclusters                        rmq                                                                                rabbitmq.com/v1beta1                                 true         RabbitmqCluster
```
