### ISSUE TITLE
Vault enabled rabbitmqcluster does not expose service information in status

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#1030]
## Describe the bug

Vault enabled rabbitmqcluster does not expose Service reference information. `.Status.DefaultUser.ServiceReference.Name` is a dependency for messaging topology operator when accessing rabbitmq svc. See: https://github.com/rabbitmq/messaging-topology-operator/blob/main/internal/cluster_reference.go#L97

## To Reproduce

Create a rabbitmqcluster with vault as secret backend. E.g.

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test
spec:
  replicas: 1
  secretBackend:
    vault:
      role: rabbitmq
      annotations:
        vault.hashicorp.com/template-static-secret-render-interval: "15s"
        vault.hashicorp.com/tls-skip-verify: "true"
      defaultUserPath: secret/data/rabbitmq/config
```

Apply and check `.status` and see there is no `.Status.DefaultUser.ServiceReference.Name` set

```
...
spec:
  ...
status:
  conditions:
  - lastTransitionTime: "2022-05-10T15:10:38Z"
    reason: AllPodsAreReady
    status: "True"
    type: AllReplicasReady
  - lastTransitionTime: "2022-05-10T15:10:38Z"
    reason: AtLeastOneEndpointAvailable
    status: "True"
    type: ClusterAvailable
  - lastTransitionTime: "2022-05-10T12:23:23Z"
    reason: NoWarnings
    status: "True"
    type: NoWarnings
  - lastTransitionTime: "2022-05-10T12:24:10Z"
    message: Finish reconciling
    reason: Success
    status: "True"
    type: ReconcileSuccess
  observedGeneration: 5
```
