### ISSUE TITLE
The Rabbitmq Operator is not working in openshift, only in priviliged scc

### ISSUE THREAD

**Issue by adaumann** [rabbitmq/cluster-operator#1135]
## Describe the bug

The Rabbitmq Operator is not working in openshift, only in priviliged scc

## To Reproduce
1. Install Openshift CRC with Openshift 4.11
2. Install the Rabbit MQ Operator in Openshift using the Operator Hub 
3. Create RabbitMqCluster kind with following settings:

````

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hcv-rabbitmqcluster
spec:
  replicas: 1
  persistence:
    storageClassName: nfs
    storage: 2Gb
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
````
Also tried to set the "runAsUser", but no luck:

````
    statefulSet:
      spec:
        template:
          spec:
[...]
            containers: []
            securityContext: 
              runAsUser: 1000006000
              runAsNonRoot: true
              fsGroup: 
````

6. Error: create Pod hcv-rabbitmqcluster-server-0 in StatefulSet hcv-rabbitmqcluster-server failed error: pods "hcv-rabbitmqcluster-server-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{0}: 0 is not an allowed group, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "consul-client": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

**Workaround**

Set to privileged user: `oc adm policy add-scc-to-user privileged -z hcv-rabbitmqcluster-server`

**Expected behavior**
Does not work as intended in the documenation

## Version and environment information
- RabbitMQ: rabbitmq:3.10.2-management
- RabbitMQ Cluster Operator: 1.14.0 via RedHat Operator Hub
- Kubernetes: 1.24
- Cloud provider or hardware configuration: Openshift

**Comment by DanielePalaia** [comment]
Hi @adaumann thank you to have noticed this issue. I tried to reproduce the issue using our OKD cluster but I wasn't able to reproduce it. I defined the same RabbitMQ cluster as you did installing from the openshift-marketplace (the olm bundle is the same as the one in operatorhub). The SCC is of type "restricted". I just put "standard" as storageClassName as the cluster is deployed in GCP. I will try to test using CRC now as you did and see what happens. What installation mode you used? Allnamespaces?

**Comment by DanielePalaia** [comment]
Hi also tried to reproduce it using crc (using openshift 4.11). With crc by default I can't find any storageclass defined.
If I don't specify any storageclassname in the RabbitmqCluster definition the cluster is going up without issue. How did you defined/configured the nfs storage class on crc?

**Comment by adaumann** [comment]
Hi, that's true a storage class is not defined as default. There is a workaround to use a hostpath storage class (which is fine for testing I assume). 
The tutorial is straight forward: https://github.com/code-ready/crc/wiki/Dynamic-volume-provisioning

**Comment by adaumann** [comment]
> Hi @adaumann thank you to have noticed this issue. I tried to reproduce the issue using our OKD cluster but I wasn't able to reproduce it. I defined the same RabbitMQ cluster as you did installing from the openshift-marketplace (the olm bundle is the same as the one in operatorhub). The SCC is of type "restricted". I just put "standard" as storageClassName as the cluster is deployed in GCP. I will try to test using CRC now as you did and see what happens. What installation mode you used? Allnamespaces?

I used the cluster-wide installation of rabbitmq cluster operator. For storage class, see below

**Comment by DanielePalaia** [comment]
@adaumann well I tried now installing the local-path storageclass and for me it is working fine.

I started with a fresh installation of crc:
```
crc version
CRC version: 2.8.0+ff5e73ea
OpenShift version: 4.11.1
Podman version: 4.1.1
crc delete
crc start --cpus 8 --memory 12000
```
Then I installed the Dynamic volume provisioning as for the documentation you posted.
I installed the operator from the openshift-marketplace:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-rabbitmq-cluster-operator
  namespace: operators
spec:
  channel: stable
  name: rabbitmq-cluster-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rabbitmq-cluster-operator.v1.14.0
```
and then:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hcv-rabbitmqcluster
spec:
  replicas: 1
  persistence:
    storageClassName: local-path
    storage: 2Gi
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
```
I can see the pod of the cluster up and running:
This is what I get from the pod definition:
```
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000660000
```
And this is the scc selected:
openshift.io/scc: restricted-v2

What SCC is selected on the rabbit deployed pod?
