### ISSUE TITLE
Cannot directly remove default resource limits and requests from existing cluster

### ISSUE THREAD

**Issue by st3v** [rabbitmq/cluster-operator#114]
**Describe the bug**
There seems to be no direct way to remove the default resource limits and requests from a `RabbitmqCluster` that had been originally created without explicitly specifying any such limits and requests. 

**To Reproduce**
1. Create a `RabbitmqCluster` that does NOT specify `resources`.
```yaml
$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq created
```

2. As expected, the created `RabbitmqCluster` uses the default resource `requests` and `limits`.
```yaml
$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[limits:map[cpu:2 memory:2Gi] requests:map[cpu:1 memory:2Gi]]
```

3. Update the `RabbitmqCluster` to explicitly set the resources to an empty struct, i.e. we want no more resource `requests` and `limits`.
```yaml
$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
    resources: {}
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq configured
```

4. Check the resource `requests` and `limits` after making the previous change...
```yaml
$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[limits:map[cpu:2 memory:2Gi] requests:map[cpu:1 memory:2Gi]]
```

**Expected behavior**
In step 4 above, we should have seen the following...

```yaml
$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[]
```

Note that there are no more `limits` and `requests` set.

**Additional Notes**
Removing explicitly defined resource limits and requests works as expected...

```yaml
$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
    resources:
      limits:
        cpu: 1
        memory: 1
      requests:
        cpu: 1
        memory: 1
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq created

$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[limits:map[cpu:1 memory:1] requests:map[cpu:1 memory:1]]

$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
    resources: {}
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq configured

$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[]
```

**Workaround**

Temporarily override the default limits and requests with explicit values before removing them altogether...

```yaml
$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq created

$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[limits:map[cpu:2 memory:2Gi] requests:map[cpu:1 memory:2Gi]]

$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
    resources:
      limits:
        cpu: 1
        memory: 1
      requests:
        cpu: 1
        memory: 1
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq configured

$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[limits:map[cpu:1 memory:1] requests:map[cpu:1 memory:1]]

$ kubectl apply -f - << EOF
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    name: example-rabbitmq
  spec:
    replicas: 1
    resources: {}
EOF
rabbitmqcluster.rabbitmq.pivotal.io/example-rabbitmq configured

$ kubectl get rabbitmqcluster example-rabbitmq -ojsonpath='{.spec.resources}'
map[]
```
