### ISSUE TITLE
Install recommended Service Binding spec RBAC for provisioned service type

### ISSUE THREAD

**Issue by Samze** [rabbitmq/cluster-operator#1149]
**Is your feature request related to a problem? Please describe.**
When using the `RabbitmqCluster` resource with the https://github.com/servicebinding/spec I currently must create my own RBAC rules to allow implementors of the spec to read the `RabbitmqCluster` resource. 

**Describe the solution you'd like**
As per the spec [recommendations](https://servicebinding.io/spec/core/1.0.0/#considerations-for-role-based-access-control-rbac) the RabbitMQ cluster operator should ship a ClusterRole with the appropriate permissions and aggregating label. 

> Cluster operators and CRD authors SHOULD opt-in resources to expose provisioned services by defining a ClusterRole with a label matching servicebinding.io/controller=true. The get, list, and watch verbs MUST be granted in the ClusterRole.

e.g.

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmq-cluster-operator-service-binding
  labels:
    servicebinding.io/controller: "true"
rules:
  - apiGroups: ["rabbitmq.com"]
    resources: ["rabbitmqclusters"]
    verbs: ["get", "list", "watch"]
```

**Additional context**
Implementors of the Service Binding spec.
- https://github.com/servicebinding/runtime
- https://github.com/redhat-developer/service-binding-operator
- https://github.com/vmware-tanzu/servicebinding
