### ISSUE TITLE
RabbitMQ Operator does not work properly with External Secrets Tool

### ISSUE THREAD

**Issue by marandalucas** [rabbitmq/cluster-operator#1168]
**Is your feature request related to a problem?**
Hi folks! We are using External Secrets tools in GKE to retrieve the secrets from Google Secret Manager. Basically, we want to retrieve the secret from GCP and then launch the rabbitMQ operator with a secret. 

The issue happens when we are deploying all the Kubernetes (RabbitMQ operator and External Secret) manifests. We found a race condition issue (We can't control the order of creation because we are following the Kubernetes Deployment Anti-patterns good practices).

- 1 - The RabbitMQ operator creates the custom secret by default.
- 2 - The External Secrets tool needs a little bit more time to retrieve the secret from GCP and then create it.
- 3 - The External Secrets try to create the secret but unfortunately the RabbitMQ Cluster is already starting...

This is the trace/log:
`could not set ExternalSecret controller reference: Object namespace/rabbitmq-default-user is already owned by another RabbitmqCluster controller rabbitmq`

**Describe the solution you'd like**
We are going to try overwriting the StatefulSet, but I would like to have an integration with External Secrets or at least an option to define the custom secret name that we would like to use, so the StatefulSet will wait for the creation of the secret.

Thanks in advance!

**Comment by marandalucas** [comment]
New Updates

We were able to overwrite the RabbitMQ statefulset with the following configuration binding a new secret created by External Secrets:

```
    override:
      statefulSet:
        spec:
          template:
            spec:
              volumes:
              - name: rabbitmq-confd
                projected:
                  defaultMode: 420
                  sources:
                  - secret:
                      items:
                      - key: default_user.conf
                        path: default_user.conf
                      name: rabbitmq-default-user-es
```

Unfortunately, the default secret is still created in the cluster and we can not remove it, because the RabbitMQ Operator creates it again when it's deleted. Is there any way to say??? RabbitMQ please don't create a custom secret by default.

**Comment by yyvess** [comment]
I have exactly the same issue as you, thanks for the workaround.
I quick look on the code and seem that only case where secret is not created is when Vault is configured =>
https://github.com/rabbitmq/cluster-operator/blob/e4e4271134b0c5e33932a2749f3856e545d241b8/internal/resource/rabbitmq_resource_builder.go#L43

I agree that will be great to have an option in the CRD RabbitmqCluster to skip secret creation and eventually to customise his name.

Somethings like that =>

```  
secretBackend:
      external: true
```

**Comment by DanielePalaia** [comment]
Hello, thank you for the feedback, we will discuss this internally next week.

**Comment by marandalucas** [comment]
Hi everyone! I recommend to DO NOT using the workaround because it's broken the replication between the nodes... I had to go back to passing the user/password thought helm in order to create the RabbitQM secret before the operator...

**Comment by DanielePalaia** [comment]
Hello,

yes at the moment the only way to skip the creation of the default-user secret creation is to use HashiCorp Vault as secret management tool.

The default-user secret (or Vault if enabled) is also used by our messaging-topology operator (and maybe other tools) and these are meant to be working together, so we can't skip the creation of the default-user secret or this one will not work anymore.

Anyway we acknowledge that an integration with ExternalSecrets is something important to have and we are planning an integration even tough I'm not sure on a possible release version/date yet.

**Comment by sylguyot** [comment]
Can we have the option to create the default-user secret only in Kubernetes (as a Kubernetes secret), if we don't want to use an external secret manager ?

**Comment by yyvess** [comment]
@DanielePalaia 
I use https://akv2k8s.io/ and the current format is not an issue.

I see two options to fix the issue
1) add an option on the crd to not create the secret and let external secret manager to create it.

2) update mq credentials when the pod start and 8n runtime if the value in the secret change


`When a volume contains data from a Secret, and that Secret is updated, Kubernetes tracks this and updates the data in the volume`

**Comment by marandalucas** [comment]
> Hi @marandalucas we are thinking on a possible integration.
> 
> At the moment what is the format of your secret stored in gcloud and exported in k8s with the external tool (I assume is External Secret operator https://external-secrets.io/v0.6.1/)? I'm asking because default_user.conf stored in our default secret is a .ini file of this format:
> 
> default_user = default_user_ default_pass = password
> 
> So I guess your original secret stored in gcloud is with the same format and exported in a K8s secret with a single data attribute like that?

Hi! @DanielePalaia I'm sorry for my late.

Currently, We are using the latest stable version of the External Secret operator https://external-secrets.io/v0.6.1/) as you mentioned.

Regarding the format, there is no limitation in the External Secret tool to create the Kubernetes secret with the same format that you already have. Let me share an example of my implementation:

- Two secrets created in GPC Secret Manager.
  - customerone-rabbitmq-username (Content -> customerone)
  - customerone-rabbitmq-password (Content -> customerone)
- External Secret Manifest to retrieve the secret from GCP using template v2 https://external-secrets.io/v0.6.1/guides/templating/
```
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-credentials
  labels:
    app.kubernetes.io/name: rabbitmq-credentials
spec:
  secretStoreRef:
    kind: SecretStore
    name: secret-store-customerone
  refreshInterval: 24h
  target:
    name: rabbitmq-default-user # This is the secret that the External Secret Operator can not overwrite because the RabbitMQ operator creates it before External Secrets Operator.
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: Opaque
      data: # We can create kubernetes secrets with the desired format.
        default_user.conf: |
          default_user = "{{ .username }}"
          default_pass = "{{ .password }}"
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
       key: customerone-rabbitmq-username # GCP Secret Name
    - secretKey: password
      remoteRef:
       key: customerone-rabbitmq-password # GCP Secret Name
```
- Kubernetes secrets created from The External Secret Operator should be the same as the previous implementation.

So, I agree with @yyvess option 1. Basically, the RabbitMQ operator needs to wait for the External Secrets Operator creates the secrets.

Thanks in advance
