### ISSUE TITLE
get hostname error

### ISSUE THREAD

**Issue by yanqin001** [rabbitmq/cluster-operator#1211]
## escribe the bug
new rabbitmq cluster get hostname error when init

## To Reproduce
RabbitmqCluster yaml:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: kb
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 5Gi
    limits:
      cpu: 2
      memory: 5Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: longhorn
    storage: "100Gi"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - rabbitmq
        topologyKey: kubernetes.io/hostname
```
## Screenshots
![image](https://user-images.githubusercontent.com/69463077/207313273-555c4869-ed6d-4f17-9a6b-170b07974caa.png)

## Version and environment information
- RabbitMQ: rabbitmq:latest
- RabbitMQ Cluster Operator: https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml
- Kubernetes: v1.19.14
