### ISSUE TITLE
missing required field "containers" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.override.statefulSet.spec.template.spec

### ISSUE THREAD

**Issue by alexey-gavrilov-flant** [rabbitmq/cluster-operator#1218]
## To Reproduce
```

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

## Screenshots
If applicable, add screenshots to help explain your problem.

## Version and environment information
- RabbitMQ: [e.g. 3.8.0]
- RabbitMQ Cluster Operator: [e.g. 1.1.0 or commit if building from source]
- Kubernetes: [e.g. 1.18.0]
- Cloud provider or hardware configuration:
 
## Additional context
Add any other context about the problem here.

**Comment by alexey-gavrilov-flant** [comment]
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            priorityClassName: production-medium
            containers:
            - name: empty
              image: alpine:3.17.0
              command:
               - sleep
               - infinity
```
here is a working version, but it looks ugly
