### ISSUE TITLE
Default template typo(?) causes permission error in Openshift

### ISSUE THREAD

**Issue by karatekaneen** [rabbitmq/cluster-operator#1227]
## Describe the bug
When creating a new instance on Openshift with the default template that looks like this:

```yaml
kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: hello-world
  namespace: xxxx
spec:
  override:
    statefulset:
      spec:
        template:
          spec:
            containers: '[]'
            securityContext: {}
```

I get a bunch of errors:
> create Pod hello-world-server-0 in StatefulSet hello-world-server failed error: pods "hello-world-server-0" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{0}: 0 is not an allowed group, spec.initContainers[0].securityContext.runAsUser: Invalid value: 999: must be in the ranges: [1000710000, 1000719999], spec.containers[0].securityContext.runAsUser: Invalid value: 999: must be in the ranges: [1000710000, 1000719999], provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{0}: 0 is not an allowed group, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

This can be related to #1135 but not sure. 

### Solution
To fix this it was just to remove the quotes from the container selection. So to replace `containers: '[]'` with `containers: []` 

Tried to find where that snippet comes from in the source but could not find it so it may already be fixed.

## Version and environment information
- RabbitMQ Cluster Operator: `2.0`, installed from market place
- Openshift: `4.11.0-0.okd-2022-12-02-145640`
