### ISSUE TITLE
Allow persistentVolumeClaimRetentionPolicy setting for RabbitMQ cluster statefulSet

### ISSUE THREAD

**Issue by Dragane** [rabbitmq/cluster-operator#1231]
This option has been available since the Kubernetes v1.23 and it would be really helpful with AWS installations, where PVs get automatically deleted when PVC gets deleted. And that's what RabbitMQ Operator does. It automatically deletes the PVCs. 

This is how it would be set up:
```
spec:
  replicas: 3     
  override:
    statefulSet:
      spec:
        persistentVolumeClaimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Delete
```

If we use it like this though,  we get this error:
`Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(RabbitmqCluster.spec.override.statefulSet.spec): unknown field "persistentVolumeClaimRetentionPolicy" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.override.statefulSet.spec`

The workaround is to set the StorageClass retention policy to "Retain" but then it's hard to re-attach such volume after the reinstallation of the RabbitMQ cluster as AWS doesn't allow the usage of  a claim Selector. Thus PV stays in the "released" state while the new empty one is created for the new PVC.
![image](https://user-images.githubusercontent.com/47391107/212327669-6544715b-952c-4062-ae32-8b6b6ee74464.png)

I think there are plenty of K8s AWS users to justify this being a bit more of a priority issue. I have already seen this being requested here but I tried explaining it more clearly why it's necessary.
