### ISSUE TITLE
Problems setting up TLS

### ISSUE THREAD

**Issue by amoorthaemer** [rabbitmq/cluster-operator#1295]
Hi,

I'm getting "**TLS server: In state wait_finished received CLIENT ALERT: Fatal - Bad Certificate**" after setting TLS on the cluster. I checked the certificates on the cluster servers and found out that the permissions are not right,. The tls.crt, tls.key and ca.crt all have the following permissions:

```text
rabbitmq@rabbitmq-server-0:/etc/rabbitmq-tls$ ls -la ..2023_03_22_09_14_16.5482906/
total 12
drwxr-sr-x 2 root root  100 Mar 22 09:14 .
drwxrwsrwt 3 root root  140 Mar 22 09:14 ..
-rw-rw---- 1 root root 1103 Mar 22 09:14 ca.crt
-rw-rw---- 1 root root 1663 Mar 22 09:14 tls.crt
-rw-rw---- 1 root root 3243 Mar 22 09:14 tls.key
```

Now I'm stuck because I don't know how to change the permissions using the deployment YAML e.g.:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: parel25
  labels:
    app: rabbitmq
spec:
  replicas: 2
  tls:
    secretName: rabbitmq-certificate
    caSecretName: rabbitmq-certificate
  image: rabbitmq:latest
  service:
    type: ClusterIP
  persistence:
    storageClassName: hostpath
    storage: 10
  resources:
    requests:
      cpu: 256m
      memory: 1Gi
    limits:
      cpu: 256m
      memory: 1Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      vm_memory_high_watermark_paging_ratio = 0.85
      cluster_formation.node_cleanup.interval = 10
      cluster_partition_handling = autoheal
      queue_master_locator = min-masters
    advancedConfig: ""
```
Can you help me out?

TIA

Bert
