### ISSUE TITLE
RabbitMQ pod always stucks in the last one

### ISSUE THREAD

**Issue by xixiangzouyibian** [rabbitmq/cluster-operator#1297]
## Describe the bug
Leverage latest rabbitmq cluster operator to deploy cluster with 3 nodes, only change the image version and the last pod falls into stucking, which the status is always terminating.

## To Reproduce
1. Install rabbitmq cluster operator:
`kubectl-rabbitmq v2.2.0`
3. Deploy cluster with image version: rabbitmq:3.10-management (Successful)
4. Deploy cluster again with image version: rabbitmq:3.11-management (Successful)
5. Deploy cluster back to image version: rabbitmq:3.10-management (Failed)
6. See error:
![image](https://user-images.githubusercontent.com/8375855/227166958-d60b1bc8-31f9-43e6-a942-7aba05cb9b07.png)

Post Rabbitmq deployment yaml file:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-ndu
  namespace: mq
spec:
  replicas: 3
  image: rabbitmq:3.10-management
  service:
    type: LoadBalancer
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
    additionalConfig: |
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      vm_memory_high_watermark_paging_ratio = 0.85
      cluster_formation.node_cleanup.interval = 10
      cluster_partition_handling = autoheal
      queue_master_locator = min-masters
      loopback_users.guest = false
      default_user = guest
      default_pass = guest
  persistence:
    storageClassName: "local-path"
    storage: "20Gi"
```
Check problematic node status:
![image](https://user-images.githubusercontent.com/8375855/227168248-b9c0e117-8522-4a63-a97e-c51c4b49ccf4.png)
All of quorum queues stop

Check queue state:
![image](https://user-images.githubusercontent.com/8375855/227168621-72dfc544-5065-49f6-a648-592ec58c1d40.png)

**Expected behavior**
- All of pods status is Running
- The messages as above snapshot shows should not be NaN in "Ready" column

## Version and environment information
- RabbitMQ: [3.10-management, 3.11-management]
- RabbitMQ Cluster Operator: [v2.2.0]
- Kubernetes: 
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1+rke2r2", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-06-08T18:04:43Z", GoVersion:"go1.18.2b7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1+rke2r2", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-06-08T18:04:43Z", GoVersion:"go1.18.2b7", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
![image](https://user-images.githubusercontent.com/8375855/227170669-0a850894-bff4-442f-a531-0f40560fbfb9.png)
