### ISSUE TITLE
external-admin-secret-credentials: unknown field "externalSecret"

### ISSUE THREAD

**Issue by udhos** [rabbitmq/cluster-operator#1299]
## Describe the bug
I am trying to create a cluster with custom admin secret according directions at:
https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/external-admin-secret-credentials

However I am hitting this error:

```
kubectl apply -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  secretBackend:
    externalSecret:
      name: "rabbitmq-user-custom"
EOF

error: error validating "STDIN": error validating data: ValidationError(RabbitmqCluster.spec.secretBackend): unknown field "externalSecret" in com.rabbitmq.v1beta1.RabbitmqCluster.spec.secretBackend; if you choose to ignore these errors, turn validation off with --validate=false
```

## To Reproduce
1. Create a brand new EKS cluster
2. Install rabbitmq operator chart: helm install rabbitmq bitnami/rabbitmq-cluster-operator --version 3.2.5
3. Apply the manifest:

```
kubectl apply -f - <<EOF
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  secretBackend:
    externalSecret:
      name: "rabbitmq-user-custom"
EOF
```

**Expected behavior**
The RabbitmqCluster is created without errors.

## Version and environment information
- RabbitMQ: NA
- RabbitMQ Cluster Operator: 2.1.0 (chart 3.2.5), also on 2.2.0 (chart 3.2.7)
- Kubernetes: EKS 1.23
- Cloud provider or hardware configuration: AWS
 
## Discussion

https://github.com/rabbitmq/cluster-operator/discussions/1298
