### ISSUE TITLE
Use same custom serviceAccount name for operator's deployment and CRD statefulSet

### ISSUE THREAD

**Issue by jurim76** [rabbitmq/cluster-operator#1312]
**Is your feature request related to a problem? Please describe.**
Due a our Vault network policy restirction, I could use a static serviceAccount name "rabbitmq" only.
Operator supports custom serviceAccount name in values.yaml, but for own deployment type (perhaps I missed something).
CRD statefulSet pods still use own serviceAccount name "<common-name>-server" (aka test-rabbitmq-server) and vault annotation fails for secret with error "permission denied".
Is it possible to use the same serviceAccount name (aka "rabbitmq") for operator's and CRD statefulSet pods?

**Comment by DanielePalaia** [comment]
Hi @jurim76 Yes it appears that this functionality is not yet implemented, as it is also documented here: https://www.rabbitmq.com/kubernetes/operator/using-operator.html#psp 

The Operator creates a Service Account using the pattern INSTANCE-NAME-server. For example, a RabbitmqCluster named 'mycluster' will generate a Service Account named mycluster-server.

It seems like that even overriding the statefulset is not enough to replace this sa.
As a workaround what you can do (even tough I'm not sure how clean this solution really is so you may need to test it well).
You can manually create the service account rabbitmq and assign to it the same permission the operator is assigning to the automatically created sa through a RoleBinding (You can reuse the same Role created by the operator).

and then try to override the ServiceAccount in the stetefulset like this:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-tanzu-rabbit
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            serviceAccount: rabbit
            serviceAccountName: rabbit
```

Take in account that in this way the sa "rabbit" is not managed by the operator so for example if you delete the operator this will stay there and you need to delete it manually.
