### ISSUE TITLE
Statefulset pod denying custom user access after restart

### ISSUE THREAD

**Issue by udhos** [rabbitmq/cluster-operator#1316]
## Describe the bug
I have created a custom user using Secret+User+Permission.
It works correctly.
However if I delete the statefulset replica (kubectl delete po rabbitmq-server-0), the new replica rejects that user:

2023/04/06 13:57:26 attempt=145: dialing amqp://guest:guest@rabbitmq:5672/: error: Exception (403) Reason: "username or password not allowed"

I can work-around the issue by manually deleting and reapplying Secret+User+Permission.

## To Reproduce

1. Install rabbitmq helm chart:

```
helm install rabbitmq bitnami/rabbitmq-cluster-operator --version 3.2.10
```

2. Create a cluster

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  resources:
    requests:
      cpu: 2
      memory: "2Gi"
      ephemeral-storage: "4Gi"
    limits:
      cpu: 2
      memory: "2Gi"
      ephemeral-storage: "4Gi"
  persistence:
    storage: 0 # Set to 0 to deactivate persistence altogether
  rabbitmq:
    additionalPlugins:
    - rabbitmq_management
    - rabbitmq_federation_management
    #- rabbitmq_peer_discovery_k8s
    additionalConfig: |
      # cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      # cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      # cluster_formation.k8s.address_type = hostname
      # vm_memory_high_watermark_paging_ratio = 0.85
      # cluster_formation.node_cleanup.interval = 10
      # cluster_partition_handling = autoheal
      # queue_master_locator = min-masters
      loopback_users.guest = false
```

3. Create the custom user

```
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-user-guest
  namespace: default #same namespace as the deployed RabbitmqCluster
type: Opaque
stringData:
  username: guest
  password: guest
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-user-guest
  namespace: default # same namespace as the deployed RabbitmqCluster
spec:
  tags:
  - administrator
  #- management
  importCredentialsSecret:
    name: rabbitmq-user-guest
  rabbitmqClusterReference:
    name: rabbitmq # name of the RabbitmqCluster
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-user-guest
  namespace: default #same namespace as the deployed RabbitmqCluster
spec:
  vhost: "/"
  user: "guest" # name of the created user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq # name of the RabbitmqCluster
```

4. Now the application should be able to connect to amqp://guest:guest@rabbitmq:5672/

5. Delete the replica

```
kubectl delete po rabbitmq-server-0
```

6. When the new replica is active, it will deny access for the custom user:

```
error: Exception (403) Reason: "username or password not allowed"
```

7. Deleting and reapplying Secret+User+Permission fixes the issue.

**Expected behavior**
The recreated pod rabbitmq-server-0 from the statefulset should accept the custom user credentials without requiring to delete/reapply the customer user definition.

## Version and environment information
- RabbitMQ: 3.11.11-debian-11-r2
- RabbitMQ Cluster Operator: 2.2.0
- Kubernetes: AWS EKS 1.23

**Comment by MirahImage** [comment]
Indeed, this is because the metadata state is stored only in memory, and in a single node cluster, any in-memory state will be lost on cluster restart, as there are no other nodes from which to fetch the cluster. For this and other reasons, single-node clusters are not recommended for production purposes.

As a workaround, it is possible to modify a label on the User object, which will force reconciliation of that object, recreating the user within RabbitMQ.

**Comment by udhos** [comment]
Thank you for the clarifications! I have an old non-operator rabbitmq configured to set the user credentials from a Secret, no persistent volume involved. I have been trying to reproduce that scenario but keep hitting unexpected behaviors like this one. Do you think that switching back to a non-operator current rabbitmq would be the most recommended course to achieve a similar setup?

**Comment by MirahImage** [comment]
You could consider using import definitions to ensure the cluster state is retained https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/import-definitions

**Comment by udhos** [comment]
Hi! Thanks again for the suggestion!

Just to let you know I actually attempted the definitions route first but got in other troubles as well. I dont remember the issues clearly since I experimented many options with different issues. I guess my last issue with definitions was I failed to setup exchange federation.

My current setup is almost working, including federation, custom user, disabled disk persistence (close to the old rabbitmq deploy I need to replace). Except for the user credential being lost on restarts.

**Comment by Zerpet** [comment]
You can configure the default user in the configuration of RabbitMQ itself, instead of using a secret + user + permission.

<details>
<summary>rabbitmq.yaml</summary>

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  resources:
    requests:
      cpu: 2
      memory: "2Gi"
      ephemeral-storage: "4Gi"
    limits:
      cpu: 2
      memory: "2Gi"
      ephemeral-storage: "4Gi"
  persistence:
    storage: 0 # Set to 0 to deactivate persistence altogether
  rabbitmq:
    additionalPlugins:
    - rabbitmq_management
    - rabbitmq_federation_management
    #- rabbitmq_peer_discovery_k8s
    additionalConfig: |
      # cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      # cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      # cluster_formation.k8s.address_type = hostname
      # vm_memory_high_watermark_paging_ratio = 0.85
      # cluster_formation.node_cleanup.interval = 10
      # cluster_partition_handling = autoheal
      # queue_master_locator = min-masters
      loopback_users.guest = false
      default_user = guest
      default_pass = guest
```

</details>

I assumed you wanted to have the default user as guest since the permissions are assigning the same permissions and tag as to the default user. This will survive pod restarts.
