### ISSUE TITLE
cannot_create_mnesia_dir 

### ISSUE THREAD

**Issue by vkiranananda** [rabbitmq/cluster-operator#1327]
I have a problem after recreate node and using [rancher.io/local-path](http://rancher.io/local-path)

The operator recreate the /opt/local-path-provisioner/pod-name-dir directory with 755 permissions.
And I get an error.

{cannot_create_mnesia_dir, "/var/lib/rabbitmq/mnesia/rabbit@rabbitmq-cluster-prod-server-0.rabbitmq-cluster-prod-nodes.default/", eacces}}

After I changed the permissions on 777 the pod starts well…

**Comment by ciyunruoshui** [comment]
en.. I'm also having this issue。 I try to add securityContext to rabbitmq pod ,  but Not effective

**Comment by DanielePalaia** [comment]
Is rancher the Kubernetes distribution you are using with these tests? I tried testing the local-path and the operator on minikube and there I can't reproduce the issue.

**Comment by vkiranananda** [comment]
This problem occurs when I reinstall node not pod. 
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster-prod
spec:
  replicas: 3
  tls:
    secretName: my-sert
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - francesca-node-yo5cq
            - francesca-node-nijvx
            - francesca-node-pm35e
    podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmq-cluster-prod
            topologyKey: "kubernetes.io/hostname"
  resources:
    requests:
      cpu: 256m
      memory: 3Gi
    limits:
      cpu: 1
      memory: 4.5Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.99
      disk_free_limit.absolute = 1GB
      default_user_tags.administrator = true
      default_user = user
      default_pass = pass
```
