### ISSUE TITLE
How to import dashboards by grafana sidecar

### ISSUE THREAD

**Issue by xixiangzouyibian** [rabbitmq/cluster-operator#1331]
Hi,

I referred the document: https://www.rabbitmq.com/kubernetes/operator/operator-monitoring.html and tried to import example dashboards into grafana: https://github.com/rabbitmq/cluster-operator/tree/main/observability/grafana/dashboards.

But the document was so brief both in rabbitmq and grafana side,  which took me a long time to figure out how I needed to specify helm chart values during the grafana installation. 

My environment was (following the rabbitmq document to "kubectl apply all of examples"):
![image](https://user-images.githubusercontent.com/8375855/233833954-2eed8793-279c-4641-8525-5844dbccf778.png)

And I tried to configure following values for grafana helm chart:
![image](https://user-images.githubusercontent.com/8375855/233833979-7a719e2e-94c7-49df-96ee-2cd790facd1b.png)

But it didn't wok well that the grafana UI said no datasources found, and the dashboard was not fully imported:
![image](https://user-images.githubusercontent.com/8375855/233834063-0909a78a-df6d-4b5e-aa18-41fa941ef78f.png)

Please advise how to configure the grafana helm chart values to import the example dashboards.

**Comment by Zerpet** [comment]
I've reproduced this issue, although I'm unsure if the root cause is the same.

The problem is that the sidecar tries to do basic authentication using Grafana credentials in the HTTP request to `https://grafana.com`. This is not correct, and it results in the following response from Grafana dot com API:

```json
{
  "code": "InvalidCredentials",
  "message": "Invalid password",
  "requestId": "18f1a4bd-fc89-4716-ad16-67682896831a"
}
```

If you tail the logs from Grafana server (Grafana running in your k8s), do you see errors similar to this?

```
logger=cleanup t=2023-04-25T10:48:51.29230316Z level=info msg="Completed cleanup jobs" duration=23.356ms
logger=provisioning.dashboard type=file name=sidecarProvider t=2023-04-25T10:49:12.801080962Z level=error msg="failed to load dashboard from " file=/tmp/dashboards/rabbitmq-overview-dashboard.json error="Dashboard title cannot be empty"
logger=provisioning.dashboard type=file name=sidecarProvider t=2023-04-25T10:49:12.801169587Z level=error msg="failed to load dashboard from " file=/tmp/dashboards/rabbitmq-quorum-queues-raft-dashboard.json error="Dashboard title cannot be empty"
logger=provisioning.dashboard type=file name=sidecarProvider t=2023-04-25T10:49:42.800807685Z level=error msg="failed to load dashboard from " file=/tmp/dashboards/rabbitmq-quorum-queues-raft-dashboard.json error="Dashboard title cannot be empty"
logger=provisioning.dashboard type=file name=sidecarProvider t=2023-04-25T10:49:42.800884102Z level=error msg="failed to load dashboard from " file=/tmp/dashboards/rabbitmq-overview-dashboard.json error="Dashboard title cannot be empty"
```

**Comment by Zerpet** [comment]
Regarding the data sources, I can import data sources without issues. I created the following `Secret`:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-ds
  namespace: grafana
  labels:
    grafana_datasource: "true"
stringData:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.prometheus.svc
      access: server
      isDefault: true
```

Note that my Prometheus is deployed in `prometheus` namespace using [Prometheus Helm Chart](https://artifacthub.io/packages/helm/prometheus-community/prometheus). The only relevant changes I made to the data source helm values are:

```yaml
sidecar:
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "true"
    skipReload: false
```
