### ISSUE TITLE
The format of Secret proposed for RabbitmqCluster is problematic

### ISSUE THREAD

**Issue by tebaly** [rabbitmq/cluster-operator#1332]
**Is your feature request related to a problem? Please describe.**
The format of Secret proposed for RabbitmqCluster is problematic. It mixes different types of parameters, making it difficult to use. Specifically, it combines security attributes, connection parameters, and configuration file format in a single Secret.

**Describe the solution you'd like**
I would like to propose a solution where the different types of parameters are separated based on their purpose. For example, security attributes should be in a separate Secret, connection parameters in another Secret, and the configuration file format for security attributes should be in its own ConfigMap.

**Additional context**
Separating the parameters in this way will make it easier to understand their purpose and manage them effectively. It will also improve the security of RabbitmqCluster by allowing for more granular control over access to sensitive information.

```yaml
apiVersion: v1
data:
  default_user.conf: ZGVmYXVsdF91c2VyID0gZGVmYXVsdF91c2VyX2htR1pGaGRld3E2NVA0ZElkeDcKZGVmYXVsdF9wYXNzID0gcWM5OG40aUdEN01ZWE1CVkZjSU8ybXRCNXZvRHVWX24K
  host: dmF1bHQtZGVmYXVsdC11c2VyLmRlZmF1bHQuc3Zj
  password: cWM5OG40aUdEN01ZWE1CVkZjSU8ybXRCNXZvRHVWX24=
  port: NTY3Mg==
  provider: cmFiYml0bXE=
  type: cmFiYml0bXE=
  username: ZGVmYXVsdF91c2VyX2htR1pGaGRld3E2NVA0ZElkeDc=
kind: Secret
metadata:
  name: my-secret 
  namespace: rabbitmq-system
type: Opaque
```

You have duplication already here. (password and username in default_user.conf) Are you making a operator to control a CLUSTER - and you can't avoid duplicating variables?..
