### ISSUE TITLE
Grafana dashboard import process is broken with Grafana Helm Chart

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#1334]
## Describe the bug
The [Operator Monitoring guide](https://www.rabbitmq.com/kubernetes/operator/operator-monitoring.html#grafana) documents a process to provision Grafana dashboards using the side-car container feature, when Grafana is deployed by the Helm Chart. Specifically the following text:

> Alternatively, if Grafana is deployed by the [Grafana Helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana), `kubectl apply` the `ConfigMaps` in directory [grafana/dashboards](https://github.com/rabbitmq/cluster-operator/tree/main/observability/grafana/dashboards) to import RabbitMQ Grafana dashboards [using a sidecar container](https://github.com/grafana/helm-charts/tree/main/charts/grafana#sidecar-for-dashboards).

Following those instructions result in no dashboards imported, and Grafana logging an error.

## To Reproduce
1. Deploy Prometheus
    ```
     helm install prometheus prometheus-community/prometheus --namespace prometheus --create-namespace
     ```
2. Deploy Grafana with sidecar enabled
     ```
     helm install grafana grafana/grafana --namespace grafana --create-namespace --values ./grafana-values.yaml
     ```
3. Import any dashboard that loads from Grana's API, e.g. rabbitmq-overview
    ```
    kubectl apply -n grafana -f https://github.com/rabbitmq/cluster-operator/blob/main/observability/grafana/dashboards/rabbitmq-overview.yml
    ```
5. See error in Grafana logs
    ```
    logger=provisioning.dashboard type=file name=sidecarProvider t=2023-04-25T10:49:42.800884102Z level=error msg="failed to load dashboard from " file=/tmp/dashboards/rabbitmq-overview-dashboard.json error="Dashboard title cannot be empty"
    ```

<details>
<summary>grafana-values.yaml</summary>

```yaml
adminUser: admin
adminPassword: strongpassword

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "true"
    searchNamespace: grafana
    reloadURL: "http://localhost:3000/api/admin/provisioning/dashboards/reload"
    provider:
      name: sidecarProvider
      orgid: 1
      type: file
  datasources:
    enabled: true
    label: grafana_datasource
    labelValue: "true"
    reloadURL: "http://localhost:3000/api/admin/provisioning/datasources/reload"
    searchNamespace: grafana
```

</details>

**Expected behavior**
Dashboards are imported correctly into Grafana.

## Screenshots
N/A

## Version and environment information
- RabbitMQ: 3.11
- RabbitMQ Cluster Operator: latest
- Kubernetes: 1.25
- Cloud provider or hardware configuration: k3s
 
## Additional context
The root cause is that the side-car container tries to use basic authentication, something equivalent to the following `curl` command:

```shell
curl -u admin:admin https://grafana.com/api/dashboards/11352/revisions/7/download
# {
#  "code": "InvalidCredentials",
#  "message": "Invalid password",
#  "requestId": "6c130573-2f5b-4dab-972c-886f6831d0dc"
# }
```

Edit: Uncovered this issue as part of investigating #1331

**Comment by Zerpet** [comment]
I suspect that `grafana.com/api` used to ignore basic auth, and now it does not ignore it. One potential solution is to change the dashboard URL to a permalink to rabbitmq-server repo, this the following:

<details>
<summary>rabbitmq-overview.yaml</summary>

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-overview-dashboard
  labels:
    grafana_dashboard: "true"
data:
  # https://grafana.com/grafana/dashboards/10991
  rabbitmq-overview-dashboard.json.url: https://github.com/rabbitmq/rabbitmq-server/raw/fd08728ff17cfa812f040acc567cf9192e90e74a/deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Overview.json
```

</details>

The downside is that we lose the ability to correlate dashboard versions with dashboards available in `grafana.com`.

What do you think @ansd @binarin ?
Tagging you since you worked on this part previously 🙂
