### ISSUE TITLE
Enabling community plugins does not work as described

### ISSUE THREAD

**Issue by Mandraenke** [rabbitmq/cluster-operator#1352]
## Describe the bug
The provided example of enabling community plugins in docs/examples/community-plugins/rabbitmq.yaml does not work.

## To Reproduce
1. Downloaded the example. 
2. Added rabbitmq_delayed_message_exchange accordingly to the example
3. applied to cluster 
4. plugin was ignored and not active

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster 
metadata: 
  name: rabbitmq
spec:
  image: docker.io/bitnami/rabbitmq:3.10.11-debian-11-r4
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                volumeMounts:
                  - mountPath: /opt/rabbitmq/community-plugins
                    name: community-plugins
            volumes:
              - name: community-plugins
                emptyDir: {}
            initContainers:
              - command:
                  - sh
                  - -c
                  - curl -L -v  https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.10.2/rabbitmq_delayed_message_exchange-3.10.2.ez --output /community-plugins/rabbitmq_delayed_message_exchange-3.10.2.ez
                image: curlimages/curl
                imagePullPolicy: IfNotPresent
                name: copy-community-plugins
                resources:
                  limits:
                    cpu: 100m
                    memory: 500Mi
                  requests:
                    cpu: 100m
                    memory: 500Mi
                terminationMessagePolicy: FallbackToLogsOnError
                volumeMounts:
                  - mountPath: /community-plugins/
                    name: community-plugins
  persistence:
    storage: 10Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_delayed_message_exchange
    envConfig: |
      PLUGINS_DIR=/opt/rabbitmq/plugins:/opt/rabbitmq/community-plugins
```

**Expected behavior**
The plugin is deployed and active. 

## Version and environment information
- RabbitMQ Cluster Operator: docker.io/bitnami/rabbitmq-cluster-operator:2.0.0-scratch-r5
- Kubernetes: 1.23.4
- Cloud provider or hardware configuration: Open Telecom Cloud CCE
 
## Additional context

I investigated the issue myself, it seems that there are two problems (at least after fixing them it worked for me):

1. The env variable should be `RABBITMQ_PLUGINS_DIR`
2. In the provided default, the directory with the shipped plugins is missing (`/opt/bitnami/rabbitmq/plugins`)

After these two changes it worked for me. Will prodive a PR of what I did.
