### ISSUE TITLE
VHost resource not reapplied if all pods restart with no storage

### ISSUE THREAD

**Issue by mchandler-plato** [rabbitmq/cluster-operator#1370]
## Describe the bug
VHost resource not reapplied if all pods restart with no storage

## To Reproduce
1. Create cluster with storage set to `0`
2. Create vhost resource
3. Validate cluster is created and has vhost
4. Restart all rabbit pods in cluster at same time
5. Cluster comes back up with zero vhost config

```
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: infra-rabbitmq-vhost
spec:
  name: testvhost
  rabbitmqClusterReference:
    name: infra-rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: infra-rabbitmq
spec:
  image: rabbitmq:3.11.11-management
  persistence:
    storage: '0'
  replicas: 3
```

**Expected behavior**
5. Cluster comes back up with correct vhost config

## Version and environment information
- RabbitMQ: `3.11.11`
- RabbitMQ Cluster Operator: `docker.io/bitnami/rabbitmq-cluster-operator:2.2.0-scratch-r3`, `docker.io/bitnami/rmq-messaging-topology-operator:1.10.2-scratch-r0`
- Kubernetes: 1.26
- Cloud provider or hardware configuration: aws/eks
