### ISSUE TITLE
Can't delete rabbitmq-cluster

### ISSUE THREAD

**Issue by marczahn** [rabbitmq/cluster-operator#1409]
I am not sure whether this is a bug or I am doing sth. wrong. The strange thing is it worked before:

I set up a rabbitmq cluster

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: new-rabbitmq
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_management
  service:
    type: ClusterIP
```

Then, for some test purposes, I added another cluster:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 5
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_management
  service:
    type: ClusterIP
```

Now, I want to delete new-rabbitmq. I tried out some things earlier and back then I could start deleting the services, then the pods and so on. But now, it doesn't work. The services come back again and again.
