### ISSUE TITLE
RabbitMQ-cluster-operator disappeared from operator index 

### ISSUE THREAD

**Issue by a164407** [rabbitmq/cluster-operator#1415]
Referring to mail sent to rabbitmq-platform email. It looks like the operator has been removed from the registry.redhat.io/redhat/community-operator-index:v4.11 

It exists for v4.10 and v4.12

Relevant PR: https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/3005

**Comment by DanielePalaia** [comment]
Hi @a164407 Do you have the possibility to do a 

```
oc describe packagemanifests rabbitmq-cluster-operator -n openshift-marketplace
```

from the openshift cluster?

actually at the moment we just have a OKD cluster available (version is 4.10)

As you stated the rabbitmq-operator is actually there:

```
dpalaia@dpalaiaYMD6R build % kubectl describe packagemanifests rabbitmq-cluster-operator -n openshift-marketplace
Name:         rabbitmq-cluster-operator
Namespace:    openshift-marketplace
Labels:       catalog=community-operators
              catalog-namespace=openshift-marketplace
              operatorframework.io/arch.amd64=supported
              operatorframework.io/os.linux=supported
              provider=VMware Tanzu
              provider-url=
Annotations:  <none>
API Version:  packages.operators.coreos.com/v1
Kind:         PackageManifest
Metadata:
  Creation Timestamp:  2022-03-23T10:39:18Z
Spec:
Status:
  Catalog Source:               community-operators
  Catalog Source Display Name:  Community Operators
  Catalog Source Namespace:     openshift-marketplace
  Catalog Source Publisher:     Red Hat
  Channels:
    Current CSV:  rabbitmq-cluster-operator.v2.4.0
```

So instead I tried to load operators from 4.11 catalog installing it in another project.

```
dpalaia@dpalaiaYMD6R build % cat catalogsource.yml 
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: devopstales-catalog
  namespace: my-marketplace
spec:
  displayName: devopstales
  publisher: devopstales
  sourceType: grpc
  image: registry.redhat.io/redhat/community-operator-index:v4.11
  updateStrategy:
    registryPoll:
      interval: 1m
```

As you can see I created a my own catalog based on registry.redhat.io/redhat/community-operator-index:v4.11 and installed it in namespace/project "my-marketplace"

and if I do:

dpalaia@dpalaiaYMD6R build % kubectl describe packagemanifests rabbitmq-cluster-operator -n my-marketplace
Name:         rabbitmq-cluster-operator
Namespace:    my-marketplace
Labels:       catalog=community-operators
              catalog-namespace=openshift-marketplace
              operatorframework.io/arch.amd64=supported
              operatorframework.io/os.linux=supported
              provider=VMware Tanzu
              provider-url=
Annotations:  <none>
API Version:  packages.operators.coreos.com/v1
Kind:         PackageManifest
Metadata:
  Creation Timestamp:  2022-03-23T10:39:18Z
Spec:
Status:
  Catalog Source:               community-operators
  Catalog Source Display Name:  Community Operators
  Catalog Source Namespace:     openshift-marketplace
  Catalog Source Publisher:     Red Hat
  Channels:
    Current CSV:  rabbitmq-cluster-operator.v2.4.0
    Current CSV Desc:

Seems there.
Not sure if maybe in Openshift they are just listing "certified operators"?
