### ISSUE TITLE
The cluster couldn't be formed with Erlang/OTP 26: K8S API endpoint peer verification is enabled by default

### ISSUE THREAD

**Issue by xixiangzouyibian** [rabbitmq/cluster-operator#1602]
## Describe the bug
The cluster couldn't be formed correctly for RabbitMQ 3.13

## To Reproduce
1. Apply rabbitmq manifest: # kubectl apply -f -
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/name: rabbitmq
        topologyKey: kubernetes.io/hostname
  delayStartSeconds: 30
  image: rabbitmq:3.13.0-management
  override: {}
  persistence:
    storage: 20Gi
    storageClassName: local-path
  rabbitmq:
    additionalConfig: |-
      cluster_formation.peer_discovery_backend = rabbit_peer_discovery_k8s
      cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
      cluster_formation.k8s.address_type = hostname
      cluster_partition_handling = pause_minority
      queue_leader_locator = balanced
      loopback_users.guest = false
    additionalPlugins:
    - rabbitmq_management
    - rabbitmq_peer_discovery_k8s
  replicas: 3
```
2. Check Rabbitmq Cluster: # kubectl exec svc/rabbitmq -n default -- rabbitmqctl cluster_status
![image](https://github.com/rabbitmq/cluster-operator/assets/8375855/b6d66964-0015-43b0-8720-772342d93e56)
As snapshot shown above, only one running nodes. 
A similar check was performed on each rabbitmq pod and it was found that the 3 rabbitmq pods did not form a cluster

**Expected behavior**
The 3 rabbitmq Pods should discover each other and join in the same cluster.

## Screenshots
Shown as above.

## Version and environment information
- RabbitMQ: 3.13.0-management 
- RabbitMQ Cluster Operator: 2.7.0-debian-12-r8
- Kubernetes: Client Version: v1.27.6+rke2r1/Kustomize Version: v5.0.1/Server Version: v1.27.6+rke2r1
- Cloud provider or hardware configuration: vmware vcenter
