### ISSUE TITLE
Limit permissions to the namespace it is created in. 

### ISSUE THREAD

**Issue by netic-rkm** [rabbitmq/cluster-operator#1632]
**Is your feature request related to a problem? Please describe.**
If I create a vhost in the namespace **foo**, I am able to add a user and permissions to that vhost in the namespace **bar**. 

**Describe the solution you'd like**
I would like to be able to set a list of allowed namespaces on the vhost to limit the namespaces that can create permissions to it. 

**Describe alternatives you've considered**
I was considering a cluster per namespace, but it really feels like an anti pattern, and a waste of resources. 

**Additional context**
Non

**Comment by mkuratczyk** [comment]
It's not clear to me what you mean. Please provide an executable test case (kubectl/rabbitmqctl commands we can use to see the problem).

**Comment by netic-rkm** [comment]
Here is a manifest, hope that makes it more clear 

```yaml
--- 
#
# Vhost created in namespace for the application foo 
#

apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: private-vhost
  namespace: foo
spec:
  name: private-vhost
  rabbitmqClusterReference:
    name: rabbitmq-delayed-messaging
    namespace: rabbitmq-system

---
#
# User created in an other namespace 
#

apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: other-user
  namespace: bar
spec:
  rabbitmqClusterReference:
    name: rabbitmq
    namespace: rabbitmq-system
  tags:
  - administrator

---
#
# I am able to give permissions to a vhost that is in an other namespace 
#

apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: other-user-permission
  namespace: bar
spec:
  permissions:
    configure: .*
    read: .*
    write: .*
  rabbitmqClusterReference:
    name: rabbitmq-delayed-messaging
    namespace: rabbitmq-system
  userReference:
    name: other-user
  vhost: private-vhost
```
