### ISSUE TITLE
ArgoCD health check missing on RabbitMQ CRD

### ISSUE THREAD

**Issue by TucoBouchState** [rabbitmq/cluster-operator#1834]
## Describe the bug
When synchronizing RabbitMQ CRDs such as Exchange, Queue, and Binding using ArgoCD, there is no existing resource health check implemented for these. 
For example, if a typo is made in the CRD, ArgoCD will consider it as Synced and OK from ArgoCD’s point of view, but on the RabbitMQ side, the resource creation will fail.
I understand this is related to ArgoCD, but I think it is relevant to discuss here. 
ArgoCD currently implements a health check only for the Cluster resource: see [ArgoCD RabbitmqCluster](https://github.com/argoproj/argo-cd/tree/master/resource_customizations/rabbitmq.com/RabbitmqCluster). 
It would be useful to include health checks for other CRDs as well.

## To Reproduce
Into a Kubernetes cluster with ArgoCD operator and RabbitMq operator installed 
Given a project created in ArgoCD synchronizing RabbitMQ CRD from GIT :
1. Create a CRD with a typo :
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: test-gbo-ajout4
  namespace: my-namespace
spec:
  name: test-gbo-ajout4
  vhost: vhost
  type: error #a typo  here, should be fanout
  durable: true
  rabbitmqClusterReference:
    name: mycluster
    namespace: my-namespace
```

2. ArgoCD sync the CRD :
![Image](https://github.com/user-attachments/assets/3f1aa03d-6b9b-4ad5-b81c-f073051015b7)
But besides, the status of the CRD is :
![Image](https://github.com/user-attachments/assets/f70ba767-7433-4cb1-b9e7-30210180d999)

3. My CICD pipeline is checking the synchronization, if everything is synced, the pipeline succeed
In this case, it should not succeed, ArgoCD should check the status of the CRD

**Expected behavior**
ArgoCD should implement a health resource (can been seen with a heart in the UI :
![Image](https://github.com/user-attachments/assets/97887f64-70b2-4f91-9853-f2224f9b4895)

By default, ArgoCD only implements for Cluster CRD : see https://github.com/argoproj/argo-cd/tree/master/resource_customizations/rabbitmq.com/RabbitmqCluster 

What do you think to handle the implementation of this health check ?
As a workaround, I've implemented one by myself but not sure if correctly implemented. 

## Version and environment information
- RabbitMQ: [e.g. 3.8.0]
- RabbitMQ Cluster Operator: [e.g. 1.1.0 or commit if building from source]
- Kubernetes: v1.29.11+148a389 (Open shift)
- Argo CD :  v2.10.18+3d900c7
 
## Additional context
Using ArgoCD and RabbitMQ operators in Openshift
