### ISSUE TITLE
Cannot create RMQ instance on Openshift

### ISSUE THREAD

**Issue by harshac** [rabbitmq/cluster-operator#234]
## Creating a RabbitMQ cluster on Openshift fails with following error:
``` FailedCreate   statefulset/mcs-services-rabbitmq-server   create Pod mcs-services-rabbitmq-server-0 in StatefulSet mcs-services-rabbitmq-server failed error: failed to create PVC persistence-mcs-services-rabbitmq-server-0: persistentvolumeclaims "persistence-mcs-services-rabbitmq-server-0" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>```

## To Reproduce

1. Download the release files and extracted them to our local workspace
2. Follow the steps to install the operator using Kubectl (not Helm) from [here](https://docs.pivotal.io/rabbitmq-kubernetes/0-7/index.html)
3. Allow the anyuid SCC which allows users to run with any UID and any GID
`oc adm policy add-scc-to-user anyuid -z p-rmq-operator -n pivotal-rabbitmq-system`
4. Confirm Operator should be installed successfully
5. Confirm CR is available following instructions from [here](https://docs.pivotal.io/rabbitmq-kubernetes/0-7/using.html)
6. Add the following lines to the ClusterRole named p-rmq-operator-role of the rbac.yaml and re-apply the rbac.yaml
```
- apiGroups:
  - rabbitmq.pivotal.io
  resources:
  - rabbitmqclusters/finalizers
  verbs:
  - create
 - get
  - patch
  - update
```

6. Create a RMQ cluster using
```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq-cluster
  namespace: rmq
spec:
  image: <Image>
  replicas: 3
  service:
    type: ClusterIP
```

7. You will see the following errors
```Warning   FailedCreate   statefulset/mcs-services-rabbitmq-server   create Pod mcs-services-rabbitmq-server-0 in StatefulSet mcs-services-rabbitmq-server failed error: failed to create PVC persistence-mcs-services-rabbitmq-server-0: persistentvolumeclaims "persistence-mcs-services-rabbitmq-server-0" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
 
Warning   FailedCreate   statefulset/mcs-services-rabbitmq-server   create Claim persistence-mcs-services-rabbitmq-server-0 for Pod mcs-services-rabbitmq-server-0 in StatefulSet mcs-services-rabbitmq-server failed error: persistentvolumeclaims "persistence-mcs-services-rabbitmq-server-0" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

**Expected behavior**
A rabbitmqCluster should be successfully created on OpenShift

## Version information
- RabbitMQ Cluster Operator: [0.7.0-build.41]

**Comment by mkuratczyk** [comment]
Looking at some other issues (eg. https://github.com/operator-framework/operator-sdk/issues/1736#issuecomment-572485336) I think `create` is not enough. Please add `update` or just try `*` and if it works. we can see if we can limit the scope if necessary.

**Comment by kellymenzel** [comment]
This might be the issue I was emailing a couple folks at VMware about. I have been on vacation so I haven't been able to provide an update, but we were able to work around the issue and get a RabbitMQ instance deployed on OpenShift by editing the `system:controller:statefulset-controller` cluster role. I couldn't figure out the specific permission that resolves the issue, but I added get, create, patch and update verbs on all finalizers and then it worked...

```
kubectl edit clusterrole system:controller:statefulset-controller
```

Then add this

```
- apiGroups:
  - '*'
  resources:
  - '*/finalizers'
  verbs:
  - get
  - create
  - patch
  - update
```

Hopefully this is just a workaround until better support can be provided for the OpenShift platform but maybe this gives a clue about where the problem lies.

**Comment by harshac** [comment]
Thanks @kellymenzel. This helped. @j4mcs and I played around with it a bit. We modified the `system:controller:statefulset-controller` cluster role and narrowed down the permissions as below. 

`kubectl edit clusterrole system:controller:statefulset-controller`

```
- apiGroups:
  - rabbitmq.com
  resources:
  - rabbitmqclusters/finalizers
  verbs:
  - update
```
