### ISSUE TITLE
How to add security context and service account?

### ISSUE THREAD

**Issue by zeromsi** [rabbitmq/cluster-operator#363]
How to add security context and service account in cr?

**Comment by coro** [comment]
Hi @zeromsi, thanks for the question. Assuming you mean you want to override the security context and service account which the RabbitMQ pods run with, you can do this by overriding the `statefulSet`. We have an example of this override [here](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/additionalPorts), or to demonstrate, here's an example yaml that would do what you're after:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            # empty array needed to successfully parse as a statefulSetSpec
            containers: []
            securityContext:
              runAsUser: 999
            serviceAccountName: rabbit-rabbitmq-server
```

I wouldn't recommend changing these though, as the operator already sets the security context and service account for the pods. What is your use case?

**Comment by govindkailas** [comment]
How do I pass the `containerSecurityContext`? My cluster is secured with OPA strict policies and doesn't allow `privileged` 
Is there a way to set the below? 
```
privileged: false
allowPrivilegeEscalation: false
```

**Comment by coro** [comment]
Anything that you need to replace in the StatefulSetSpec can be done with overrides, so in your case assuming your policies apply to initContainers as well as regular containers, you can override the containerSecurityContext for all of the containers used in the operator:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
            initContainers:
            - name: setup-container
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
```
