### ISSUE TITLE
Set `topologySpreadConstraints` by default

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#398]
`topologySpreadConstraints` can be configured in such a way that the StatefulSet will be spread across multiple AZs if they are available but will also deploy to a single-AZ cluster such as `kind`. Therefore, we can just set the constraints by default as a sane default for most deployments. Ultimately we should achieve something like this:
```
topologySpreadConstraints:
- maxSkew: 1
   topologyKey: zone
   whenUnsatisfiable: ScheduleAnyway
   labelSelector:
     matchLabels:
       app: rabbitmq
```
