### ISSUE TITLE
spec.replicas defaulting does not work

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#404]
## Describe the bug

The CRD has default value set for `spec.replicas` and it is an optional value. However, you cannot create a RabbitmqCluster with no `spec.replicas` specified.

## To Reproduce

`kubectl apply ` with a RabbitmqCluster manifest with no spec.replicas set

**Expected behavior**

1) If the value is set to be `optional`, we should be able to create RabbitmqCluster without specifying it.
2) We change it back to a required value. Q: why do we have default value for this required property?

**Comment by ansd** [comment]
I can't reproduce this issue with the reproduction steps described above.
`kubectl apply` succeeds and defaults to 1 replica:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example
  namespace: default
spec: {}
```

However, I can reproduce the issue described in https://github.com/rabbitmq/cluster-operator/pull/393#issuecomment-713679565. That issue can be reproduced with the following manifest:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example
  namespace: default
spec:
  replicas: null
```
