### ISSUE TITLE
Pod stuck in Terminating state

### ISSUE THREAD

**Issue by gerhard** [rabbitmq/cluster-operator#409]
Having applied a change that requires all pods in the `RabbitmqCluster` to be updated, the last pod is stuck in Terminating state.

I am using v0.47.0 on GKE 1.18, all waiting for you to take a closer look at. Reach out privately for access details.

The problem in 1 picture:

![image](https://user-images.githubusercontent.com/3342/97022608-3c66cd00-154c-11eb-8456-76d338e8f01a.png)

I suspect that the deadline exceeded for the readinessProbe has something to do with this:

```
│ Events:                                                                                                                                                                                                                                                                                                                                                                                                                │
│   Type     Reason     Age                    From                                                         Message                                                                                                                                                                                                                                                                                                      │
│   ----     ------     ----                   ----                                                         -------                                                                                                                                                                                                                                                                                                      │
│   Normal   Killing    30m                    kubelet, gke-messaging-streaming-default-pool-baea9f60-gz8t  Stopping container rabbitmq                                                                                                                                                                                                                                                                                  │
│   Warning  Unhealthy  2m11s (x27 over 164m)  kubelet, gke-messaging-streaming-default-pool-baea9f60-gz8t  Readiness probe errored: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Maybe related to https://github.com/rabbitmq/cluster-operator/issues/105

**Comment by ChunyiLyu** [comment]
Had a call with @gerhard and looked into this problem a bit more. We believe that the readiness probe `rabbitmqctl check_port_connectivity` is causing this issue. Gerhard can have seen this problem using the operator, and when using yaml manifests to deploy directly (both used `rabbitmqctl check_port_connectivity` as the readiness probe). When he switched to use a tcp probe ([see](https://github.com/rabbitmq/infrastructure/blob/master/commercial-edition/docker/rmq/k8s/yaml/statefulset.yml#L248)), he can only reproduce this issue. We don't have a good explanation about why running `rabbitmqctl` is causing this, but I think the reasonable next step will be to use the tcp probe as in [here](https://github.com/rabbitmq/infrastructure/blob/master/commercial-edition/docker/rmq/k8s/yaml/statefulset.yml#L248)

A bit more on the issue: the pod is stuck at terminating because podExec is broken on the pod. When using `kubectl exec ` to do a remote podExec, the command will successfully run, however the session won't terminate. I saw this behavior with any commands (ls, cat, not just rabbitmq cli ones), and with all three pods in the cluster. In the preStop hook, we run `rabbitmq-upgrade await_online_quorum_plus_one`,  `rabbitmq-upgrade await_online_synchronized_mirror` and `rabbitmq-upgrade drain`. I ran these three commands using `kubectl exec`. The commands ran successfully, however the podExec cannot terminate, so I think the pod is stuck at terminating because podExec from the preStop hook are stuck.

**Comment by michaelklishin** [comment]
`rabbitmq-diagnostics check_port_connectivity` expects a fully booted node and is not suitable for [readiness probes with sequentially deployed nodes](https://www.rabbitmq.com/clustering.html#restarting-readiness-probes).

**Comment by gerhard** [comment]
A readiness probe determines when a pod is ready to serve traffic. It is meant to mitigate against taking into service pods that cannot handle requests. A TCP probe that checks if port 5672 is open sounds like a great RabbitMQ readiness probe to me. It is the equivalent of `nc -z PRIVATE_IP 5672` which is both faster and lighter to run than `rabbitmqctl`.

As a related question, in your opinion @michaelklishin, what is a good check to run for the [startup probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes)? To be more specific, how do we improve on this?

```yaml
        # We use a startup probe to determine when the RabbitMQ runtime, Erlang, has started.
        # We check every 10 seconds that: "the node OS process is up (the Erlang VM), registered with EPMD and CLI tools can authenticate with it"
        # We check for up to 5 minutes, or 30 times, as sometimes RabbitMQ could be performing CPU-intensive operations, and starting another Erlang VM to check on RabbitMQ may create too much CPU contention.
        # While this is rare and extreme, it does happen, so we are being extra persistent.
        #
        # While the startup probe runs, both the liveness and the readiness probes are disabled.
        # As a matter of fact, we don't use a livesness probe at all because this is more likely to take down an overloaded RabbitMQ node than solve and actual deadlock.
        #
        # Cloud environments where CPU time can be sliced (a.k.a. limited) in milliseconds is especially bad for runtimes that are natively multi-core.
        # These have many optimisations that are based on the fact that multiple cores are available to them, and CPU limits (and even sharing) can have disastrous side-effects.
        #
        # We let Erlang handle the healthiness of the node, and only inform K8S when it has started via the ping command.
        #
        # https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#when-should-you-use-a-startup-probe
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
        # https://blog.colinbreck.com/kubernetes-liveness-and-readiness-probes-how-to-avoid-shooting-yourself-in-the-foot/
        # https://medium.com/swlh/fantastic-probes-and-how-to-configure-them-fef7e030bd2f
        startupProbe:
          exec:
            command:
            - "rabbitmq-diagnostics"
            - "ping"
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 9
```
