### ISSUE TITLE
Make terminationGracePeriodSeconds configuration at rabbitmqcluster.spec

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#419]
**Context**

As discussed in sync-up, it's an important context that we should make people aware that we intentionally set terminationGracePeriodSeconds to a week long to ensure that no data loss during a restart of pods. We decided to 1) document this week long timeout and make people aware that this could cause long termination for pods 2) make this timeout configurable at the top level since we are aware that not all people want this feature.

**Describe the solution you'd like**

```yaml
kind: RabbitmqCluster
spec:
  terminationGracePeriodSeconds: # configurable and [defaults to 604800](https://github.com/rabbitmq/cluster-operator/blob/main/internal/resource/statefulset.go#L30)
```

**Describe alternatives you've considered**

**Additional context**
