### ISSUE TITLE
When using `override` to set an env variable, you can't refer to MY_POD_NAME and other variables

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#433]
## Describe the bug
When using `override` to set an env variable, you can't refer to pre-existing env variables

## To Reproduce
1. Create the following cluster
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: issue
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                env:
                  - name: RMQ_POD_NAME
                    value: $(MY_POD_NAME)
```

2. Check the value of RMQ_POD_NAME - it is not set to "issue-rabbitmq-server-0" but to '$(MY_POD_NAME)'
```
kubectl exec -it issue-rabbitmq-server-0 -- bash -c "set" | grep POD_NAME
MY_POD_NAME=issue-rabbitmq-server-0
MY_POD_NAMESPACE=default
RMQ_POD_NAME='$(MY_POD_NAME)'
```

3. This is probably because of the order of env variables in the StatefulSet definition (RMQ_POD_NAME is first and thefore before MY_POD_NAME):
```
kubectl get -o yaml statefulsets.apps issue-rabbitmq-server  | yq r - 'spec.template.spec.containers.*.env'
- name: RMQ_POD_NAME
  value: $(MY_POD_NAME)
- name: MY_POD_NAME
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.name
- name: MY_POD_NAMESPACE
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: metadata.namespace
- name: RABBITMQ_ENABLED_PLUGINS_FILE
  value: /operator/enabled_plugins
- name: K8S_SERVICE_NAME
  value: issue-rabbitmq-headless
- name: RABBITMQ_USE_LONGNAME
  value: "true"
- name: RABBITMQ_NODENAME
  value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
- name: K8S_HOSTNAME_SUFFIX
  value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
```

**Expected behavior**
I expect to be able to refer to MY_POD_NAME and MY_POD_NAMESPACE in the environment variables I declare.

## Version information
- RabbitMQ Cluster Operator: 0.48
