### ISSUE TITLE
502 Bad Gateway in Management via Ingress

### ISSUE THREAD

**Issue by logineimer** [rabbitmq/cluster-operator#490]
## Describe the bug
I cannot access my RabbitMQ Managemen UI via Ingress because of 502 Bad Gateway error.

## To Reproduce
1. **Fresh** installation of latest cluster-operator 1.0.0
2. Setup RabbitMQCluster with following YAML:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1 | 3 | 5 (Tried everything reasonable)
  tls:
    secretName: tls-cluster-example-com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
spec:
  rules:
    - host: rabbit-management.cluster.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: rabbitmq
                port:
                  name: http | management-tls (both are broken with 502 Bad Gateway)
  tls:
    - secretName: tls-cluster-example-com
```
3. Open https://rabbit-management.cluster.example.com in Chrome
4. Be frustrated discovering 502 Bad Gateway the x-th time this day

**Expected behavior**
I expect no 502 Bad Gateway Error but instead the Management UI.

## Version information
- RabbitMQ: 3.8.9-management
- RabbitMQ Cluster Operator: 1.0.0
- Kubernetes: 1.19.2
 
## Additional context
With the **previous** operator version 0.49.0 **everything was fine**. The port name for Management UI has changed from management to management-tls though.

**Comment by ChunyiLyu** [comment]
Hi @logineimer, thanks for using the operator. We are aware of this issue and it's fixed in [this PR](https://github.com/rabbitmq/cluster-operator/pull/487) which is on the latest main branch. We will release a new version later this week, and I will let you you once we've done that.

**Comment by logineimer** [comment]
Hi @ChunyiLyu, this is very relieving to hear. It was very exasperating. 🤣  I'm looking forward to that new release. :)

**Comment by ChunyiLyu** [comment]
@logineimer  Here you go: https://github.com/rabbitmq/cluster-operator/releases/tag/v1.1.0

Let me know if the new version fixes your problem or not.

**Comment by logineimer** [comment]
@ChunyiLyu Thank you very much for the fast update! Here is an excerpt of my ingress YAML:

```
spec:
  rules:
    - host: rabbit-management.cluster.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: rabbitmq
                port:
                  name: management
```

This **does** work. However, when using `management-tls` instead of `management` port the 502 Bad Gateway reappears. management-tls maps to port 15671 which shows no occurence in the [official docs](https://www.rabbitmq.com/networking.html#ports). I reckon management-tls is obsolete?

**Comment by ChunyiLyu** [comment]
Hi @logineimer, how are you connecting `management-tls`? Are you providing the ca cert that you've provided in `spec.tls.secretName`?

**Comment by logineimer** [comment]
Hi @ChunyiLyu, yes i omitted `spec.tls.secretName` in the example because the example in my original comment contained it. Here's the full YAML of the ingress resource:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
spec:
  rules:
    - host: rabbit-management.cluster.example.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: rabbitmq
                port:
                  name: management-tls <-- Problem?
  tls:
    - secretName: tls-cluster-example-com
```

`kubectl get service rabbitmq -o yaml` proves the existence of `management-tls` port (15671), however connecting via ingress leads to 502 Bad Gateway. I'm not sure if this is intented.

**Comment by Gsantomaggio** [comment]
you missed `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"`

The following configuration works:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-one
  namespace: rabbitmq
spec:
  replicas: 1
  tls:
    secretName:  tls-cluster-one-secret
    caSecretName: ca-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: rabbitmq
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: rabbit-management.cluster.example.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: rabbitmq-one
              port:
                name: management-tls
```


```
 # curl -k   -u test:test https://rabbit-management.cluster.example.com/api/queues                                                                                                                              
[{"arguments":{"x-queue-type":"classic"},"auto_delete":false,"backing_queue_status":{"avg_ack_egress_rate":0.0,"avg_ack_ingress_rate":0.0,"avg_egress_rate":0.0,"avg_ingress_rate":0.0,"delta":["delta","undefined",0,0,"undefined"],"len":0,"mode":"default","next_seq_id":0,"q1":0,"q2":0,"q3":0,"q4":0,"target_ram_count":"infinity"},"consumer_utilisation":null,"consumers":0,"durable":true,"effective_policy_definition":{},"exclusive":false,"exclusive_consumer_tag":null,"garbage_collection":{"fullsweep_after":65535,"max_heap_size":0,"min_bin_vheap_size":46422,"min_heap_size":233,"minor_gcs":4},"head_message_timestamp":null,"idle_since":"2020-11-25 16:36:16","memory":16452,"message_bytes":0,"message_bytes_paged_out":0,"message_bytes_persistent":0,"message_bytes_ram":0,"message_bytes_ready":0,"message_bytes_unacknowledged":0,"messages":0,"messages_details":{"rate":0.0},"messages_paged_out":0,"messages_persistent":0,"messages_ram":0,"messages_ready":0,"messages_ready_details":{"rate":0.0},"messages_ready_ram":0,"messages_unacknowledged":0,"messages_unacknowledged_details":{"rate":0.0},"messages_unacknowledged_ram":0,"name":"hello-tls","node":"rabbit@rabbitmq-one-server-0.rabbitmq-one-nodes.rabbitmq","operator_policy":null,"policy":null,"recoverable_slaves":null,"reductions":8325,"reductions_details":{"rate":0.0},"single_active_consumer_tag":null,"state":"running","type":"classic","vhost":"/"}]% 
```

I think we can close the issue @ChunyiLyu
