### ISSUE TITLE
How to add a sidecar with pod?

### ISSUE THREAD

**Issue by zeromsi** [rabbitmq/cluster-operator#491]
I need to add a sidecar container with my rabbitmq pod. Can anyone provide me an example?

**Comment by ChunyiLyu** [comment]
@zeromsi  You can use statefulSet override which let you patch the statefulSet in whatever way you want. For example:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: your-sidecar-container
...
```
You can read more on how to leverage the statefulSet and service override in the future in [our docs here](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#override).

Out of curious, what's your use case for adding a sidecar here?
