### ISSUE TITLE
Helm chart for operator installation

### ISSUE THREAD

**Issue by naphta** [rabbitmq/cluster-operator#498]
**Is your feature request related to a problem? Please describe.**
The workflow we have at our company for installing things into Kubernetes follows helm charts largely, it's quite frustrating to come into a project where there's no way using Helm to install into Kubernetes. We miss various features around helm such as the immutability, extensibility, and the ease of checking history, rolling back, etc.

**Describe the solution you'd like**
A basic helm chart containing the bare minimum to get the operator installed (with or without the CRD's)

**Describe alternatives you've considered**
The obvious path for us would be to write our own Helm chart, and that will likely be our short term fix as that involves less explaining to other members of the team about how the new installation method works.

**Additional context**
Before raising this issue I did ask the question on the community Slack first, which ultimately let me to create this issue. You can see that discussion [here](https://rabbitmq.slack.com/archives/CTMSV81HA/p1605886237290700).

**Comment by naphta** [comment]
For what it's worth I have a very basic chart to use, which is essentially the manifests from the installation converted into helm templates, with a few bits of configuration, and the crd's added into the chart CRD directory. I'm happy to share this as a starting point if a helm chart is an accepted direction to go in.

**Comment by mkuratczyk** [comment]
How did you covert it? One of those things that we didn't want to spend time doing was how to automatically generate the chart in a consistent way with the YAML we generate as a release. When we had the chart, it was created manually and we kept forgetting to update it. To prevent that, we would need a step in the [Makefile](https://github.com/rabbitmq/cluster-operator/blob/main/Makefile#L92) to generate the chart whenever we generate YAML for manual installation.

**Comment by naphta** [comment]
I did it manually, but I did when I wrote the initial chart for Kiali setup some makefile scripting to do so. It'd depend on what your workflow is but it's perfectly doable to have helm as the authoritative version of the manifests, or pull the current ones into helm with some extra fields added.

I've actually got a tool to help convert an internal operators (kubebuilder) set of manifests into a helm chart which I'd be more than willing to host publicly for use if desired.

But yes I think it's absolutely untenable to have to make changes in two places. I personally prefer the approach where the static manifests are generated from the helm chart as artifacts from running `helm template`>

**Comment by mkuratczyk** [comment]
Sounds great. We use `kubebuilder` so if you have a method of generating the chart based on a `kubebuilder` project, that could definitely help.

**Comment by naphta** [comment]
@mkuratczyk I have a little bit of time to possibly integrate the helm chart I've got our side, is that something you're interested in seeing in a pull request for now? Rather than depend on any tooling I have I'll probably take the approach of the helm chart generating the existing artifacts, rather than the other way around, unless it's a deal breaker for you to continue the existing workflow with Kustomize. 

The tool I mentioned essentially turns a few fields from having static outputs to having helm templated outputs. We use it in combination with a helm chart we've written for our operator to pass in things like the CRD's and RBAC from kubebuilder.

There are a few limitations which haven't been a problem (entirely fixable) such as not being able to specify service account names etc. I could possibly add a conversion in to set the to the result of: `{{ include "chart-name.serviceAccountName" }}` as one potential fix.

e.g.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-super-cool-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-super-cool-role
rules:
- apiGroups:
  - test.example.com
  resources:
  - test
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foo.example.com
  resources:
  - foo
  verbs:
  - get
  - patch
  - update
```

turns into

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart-name.fullname" . }}-my-super-cool-cluster-role-binding
  labels: {{ include "chart-name.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart-name.fullname" . }}-my-super-cool-cluster-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart-name.fullname" . }}-my-super-cool-cluster-role
  labels: {{ include "chart-name.labels" . | nindent 4 }}
rules:
- apiGroups:
  - test.example.com
  resources:
  - test
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foo.example.com
  resources:
  - foo
  verbs:
  - get
  - patch
  - update
```
