### ISSUE TITLE
Better way of handling image, operator and user configuration

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#503]
We discussed the interactions between the image, Operator and user configuration and decided to make the following improvements:

1. Tanzu image will ship its default configuration in `rabbitmq.conf` rather than `conf.d/` as it does right now. This will allow the Operator and its users, to easily override these values if needed. This change has already been implemented.

2. The Operator will not override/mount over `rabbitmq.conf` and instead:
a. mount generated configuration (k8s peer discovery, etc) to `conf.d/10-operatorDefaults.conf` or something similar
b. mount `additionalConfig` as `conf.d/90-additionalConfig.conf` or similar

Justification:
- we don't completely remove image's configuration (by mounting over it) and therefore don't have to repeat it
- all configuration - from the image, from the Operator and from the user are all visible in the running container
- the precedence is as expect - the user has the final say, otherwise they rely on the Operator defaults and then on image defaults (for properties not set by neither the user nor the Operator)

Caveats:
- `rabbitmq` image still ships a file in [conf.d](https://github.com/docker-library/rabbitmq/blob/master/3.8/ubuntu/Dockerfile#L254) that we wouldn't be able to override. This particular setting is not too important - users can just use `rabbitmq:management` which [deletes that files](https://github.com/docker-library/rabbitmq/blob/master/3.8/ubuntu/management/Dockerfile#L6)

**Comment by Zerpet** [comment]
## Context

Started working on this and the changes I'm having in mind to complete this issue are:

- Change the config map resource module to generate a key in the Server conf with just the defaults.
- Use the config map resource module to generate a key in the Server conf with the contents of `spec.rabbitmq.additionalConfig`.
- Update Pod template spec in StatefulSet, so that RabbitMQ container mounts default configuration, default user and spec configuration as files in `conf.d`.

### Next steps

- Manually test how setting multiple sources in a `ProjectedVolume` works, in terms of mounting all the files in one place, without overlapping with the mounted directory i.e. mount files in `conf.d` and preserve the contents of `conf.d` before the mount.
- We are changing the Pod template spec in the StatefulSet, is this a breaking change? If so, how do wemove forward implementing this feature?

**Comment by Zerpet** [comment]
### Context

We can implement this by adding the ConfigMap to the projected volume, it should look like this:

```
[...]
volumes:
      - name: rabbitmq-confd
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              - key: default_user.conf
                path: 11-default_user.conf
              name: aitor-default-user
          - configMap:
              items:
              - key: operatorDefaults.conf
                path: 10-operatorDefaults.conf
              - key: additionalConfig.conf
                path: 90-additionalConfig.conf
              name: aitor-server-conf
```

We also have to remove `rabbitmq.conf` from the volume mounts. Last but not least, we have to change `configmap.go` to always create the default configuration in a key `operatorDefaults.conf` and the user configuration in `additionalConfig.conf` key. The ConfigMap will now have two keys; this is better than creating a new ConfigMap object.

There is a challenge/unknown as to what to do with regards to the TLS configuration. Should it go into the operator defaults? Or should it go into the additional config?
Putting the generated TLS configuration in the additional config seems odd because this file should, ideally, just contain the configuration from `.spec.rabbitmq.additionalConfig` field. However, the TLS configuration is not a "default".
