### ISSUE TITLE
VolumeMode as Block

### ISSUE THREAD

**Issue by Coopyrightdmin** [rabbitmq/cluster-operator#514]
Dears,

I have implemented rabbitmq operator on Scaleway and I am trying to set VolumeMode as Block instead of the default FileSystem. Is there any option? patching pvc after creation seems to be impossible since the volumeMode is immutable.

Regards,
Ludovic

**Comment by ChunyiLyu** [comment]
Hi @Coopyrightdmin, you can leverage our override to change the volumeMode when creating your rabbitmqcluster cr. Override let you patch the statefulSet in whatever way you want. For your specific use case, you could try:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: test
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: persistence
            namespace: rabbitmq-system
            labels:
              app.kubernetes.io/component: rabbitmq
              app.kubernetes.io/name: test
              app.kubernetes.io/part-of: rabbitmq
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            volumeMode: Block
```

The override is applied as a patch using the same library that `kubectl patch` uses behind the scenes. Since `volumeClaimTemplates` is defined as a list without a [strategic merge patch](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md) behavior defined, when patching the PVC list, you need to provide the whole PVC definition, rather than just specifying the volumeMode property that you wish to change. Hope this is helpful and let me know if this solves your problem or not.
