### ISSUE TITLE
cluster operator fails to deploy rabbitmq instance

### ISSUE THREAD

**Issue by thorion3006** [rabbitmq/cluster-operator#537]
## Describe the bug
Rabbitmq cluster operator v1.3.0 fails to deploy rabbitmq instance in EKS v1.18 cluster

## To Reproduce
1. ```kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/download/v1.3.0/cluster-operator.yml```
2. ```kubectl apply -f rabbitmq.yaml -n resources```
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: rabbitmq
            topologyKey: topology.kubernetes.io/zone
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
          topologyKey: kubernetes.io/hostname
  override:
    service:
      spec:
        ports:
          - name: management-http
            protocol: TCP
            port: 15672
            targetPort: 15672
          - name: amqp-tcp
            protocol: TCP
            port: 5672
            targetPort: 5672
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                env:
                  - name: RABBITMQ_QUORUM_DIR
                    value: /var/lib/rabbitmq/quorum-segments
                volumeMounts:
                  - mountPath: /etc/rabbitmq/rabbitmq_definitions.json
                    name: definitions
                  - mountPath: /var/lib/rabbitmq/quorum-segments
                    name: quorum-segments
                  - mountPath: /var/lib/rabbitmq/quorum-wal
                    name: quorum-wal
            nodeSelector:
              ebs-optimized: 'true'
            volumes:
              - name: definitions
                configMap:
                  name: rabbitmq-definitions # Name of the ConfigMap which contains definitions you wish to import
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: quorum-wal
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: quorum-segments
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
  persistence:
    storage: 10Gi
  rabbitmq:
    additionalConfig: |
      channel_max = 200
      disk_free_limit.relative = 1.5
      load_definitions = /etc/rabbitmq/rabbitmq_definitions.json # Path to the mounted definitions file
      management.path_prefix = /rabbitmq
      vm_memory_high_watermark.relative = 0.7
      vm_memory_high_watermark_paging_ratio = 0.9
    additionalPlugins:
      - rabbitmq_top
    advancedConfig: |
      [
        {ra, [
              {wal_data_dir, '/var/lib/rabbitmq/quorum-wal'}
          ]},
        {rabbit, [
          {quorum_cluster_size, 5},
          {quorum_commands_soft_limit, 1024} # maximum number of unconfirmed messages a channel accepts before entering flow
        ]}
      ].
  replicas: 3
  resources:
    requests:
      cpu: '1'
      memory: 2Gi
    limits:
      cpu: '1'
      memory: 2Gi

```
3. error log:
```
2021-01-03T15:50:45.239Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "rabbitmq.com", "reconcilerKind": "RabbitmqCluster", "controller": "rabbitmqcluster", "name": "rabbitmq", "namespace": "resources", "error": "failed setting controller reference: cluster-scoped resource must not have a namespace-scoped owner, owner's namespace resources"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
```

**Expected behavior**
A rabbitmq instance should be deployed to `resources` namespace.

## Version and environment information
- RabbitMQ: 3.8.9
- RabbitMQ Cluster Operator: 1.3.0
- Kubernetes: 1.18
- Cloud provider or hardware configuration: EKS

**Comment by mkuratczyk** [comment]
Thank you. I was able to reproduce the issue and we'll look into it shortly.

**Comment by mkuratczyk** [comment]
I've found two issues:
1. You don't specify `namespace` for the `quorum-wal` and `quorum-segments` PVCs. I can't tell yet whether such YAML should be considered invalid or whether it's a bug in the operator that should be able to handle that. We'll discuss this tomorrow.
2. You don't specify `persistence` PVC. Given that `override` works as a YAML patch, when you specify any PVCs, you have to specify them all - otherwise the default `persistence` PVC gets overwritten/removed. [Multiple-disks example](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/multiple-disks) defines all of them.

After adding the namespace and the missing PVC, I was able to deploy a cluster.
 
I also have some questions/observations, unrelated to the issue:
1. Why do you override port names in the service? What is the benefit of that?
2. You tune disk-level access by separating the volumes but at the same time you assign 1 CPU and 2GB of RAM to this instance which is very low (we set that as default to make it easy to get started but definitely don't recommend for any real use). Have you done any testing to validate this setup?

Full YAML that works for me:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: rabbitmq
            topologyKey: topology.kubernetes.io/zone
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq
          topologyKey: kubernetes.io/hostname
  override:
    service:
      spec:
        ports:
          - name: management-http
            protocol: TCP
            port: 15672
            targetPort: 15672
          - name: amqp-tcp
            protocol: TCP
            port: 5672
            targetPort: 5672
    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                env:
                  - name: RABBITMQ_QUORUM_DIR
                    value: /var/lib/rabbitmq/quorum-segments
                volumeMounts:
                  - mountPath: /etc/rabbitmq/rabbitmq_definitions.json
                    name: definitions
                  - mountPath: /var/lib/rabbitmq/quorum-segments
                    name: quorum-segments
                  - mountPath: /var/lib/rabbitmq/quorum-wal
                    name: quorum-wal
            nodeSelector:
              ebs-optimized: "true"
            volumes:
              - name: definitions
                configMap:
                  name: rabbitmq-definitions # Name of the ConfigMap which contains definitions you wish to import
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence
              namespace: default
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
              volumeMode: Filesystem
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: quorum-wal
              namespace: default
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: quorum-segments
              namespace: default
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
  persistence:
    storage: 10Gi
  rabbitmq:
    additionalConfig: |
      channel_max = 200
      disk_free_limit.relative = 1.5
      load_definitions = /etc/rabbitmq/rabbitmq_definitions.json # Path to the mounted definitions file
      management.path_prefix = /rabbitmq
      vm_memory_high_watermark.relative = 0.7
      vm_memory_high_watermark_paging_ratio = 0.9
    additionalPlugins:
      - rabbitmq_top
    advancedConfig: |
      [
        {ra, [
              {wal_data_dir, '/var/lib/rabbitmq/quorum-wal'}
          ]},
        {rabbit, [
          {quorum_cluster_size, 5},
          {quorum_commands_soft_limit, 1024} # maximum number of unconfirmed messages a channel accepts before entering flow
        ]}
      ].
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 2Gi
```
