### ISSUE TITLE
Custom RabbitMQ pod annotations doesn't apply

### ISSUE THREAD

**Issue by Arn-Arm** [rabbitmq/cluster-operator#538]
## Describe the bug
I have been trying to annotate RabbtMQ application pods with custom annotations/labels, but it seems that it might not be possible or just doesn't work. I was able to annotate the whole service, but this is not what i intended. As documentation say CRD supports custom override values, but i couldn't make it work with annotations.

## To Reproduce

kubectl -n rabbitmq-system create --kustomize rabbitmq-operator/

kubectl -n rabbitmq create --kustomize rabbitmq-test/

Include any YAML or manifest necessary to reproduce the problem.

**kustomization.yaml**
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
bases:
  - github.com/rabbitmq/cluster-operator/config/namespace/base?ref=v1.3.0
  - github.com/rabbitmq/cluster-operator/config/crd?ref=v1.3.0
  - github.com/rabbitmq/cluster-operator/config/rbac?ref=v1.3.0
  - github.com/rabbitmq/cluster-operator/config/manager?ref=v1.3.0
```
**definitions.yaml**
```
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-test
spec:
  image: rabbitmq:3.8.5
  replicas: 1
  persistence:
    storage: 1Gi
  override:
    statefulSet:
      metadata:
        annotations:
          foo: bar
```

**Expected behavior**
RabbitMQ pods would be annotated with custom annotations

## Version and environment information
- RabbitMQ: 3.8.5
- RabbitMQ Cluster Operator: 1.3.0
- Kubernetes: v1.19.4
- Cloud provider or hardware configuration: minikube v1.15.1 on Darwin 10.15.7 as well tried on Azure AKS with K8s version 1.18

**Comment by thorion3006** [comment]
Hi @Arn-Arm, i think the issue is in your definitions.yaml. You're just annotating the statefulset not the pods, if you want to annotate just the pods then your definitions.yaml should look like:
```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-test
spec:
  image: rabbitmq:3.8.5
  replicas: 1
  persistence:
    storage: 1Gi
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              foo: bar
```
