### ISSUE TITLE
Expose rabbitmq.conf in the CRD

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#57]
**Is your feature request related to a problem? Please describe.**
Currently a basic RabbitMQ config file is generated by the operator but can only be customized once the cluster is deployed. Since the CR should define the desired state of a deployment, RabbitMQ configuration should be a part of it.

**Describe the solution you'd like**
I should be able to specify configuration like this:
```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: foo
spec:
  rabbitmq:
    additional_config: |
      vm_memory_high_watermark.relative = 0.6
```

The value of this field should be appended to the configuration we currently generate so that the value in the ConfigMap contains settings from both (first ours and then custom).

Changes to this property should trigger a StatefulSet rolling restart to reload configuration.
