### ISSUE TITLE
logs timestamp

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#571]
Hello,
I am using   kubectl -n rabbitmq-system  logs  to look at logs ...

I see that the timestamp is not that of the host...
Can we adjust it to match the host.
I believe it is set to UTC.

Not sure if this should be considered a bug or an enhancement.  Please assign it to correct group.

**Comment by ChunyiLyu** [comment]
Hi @bdaoudtdc,

We use the logger that controller-runtime provides. I took a look and I don't see configuring timestamp is supported there: https://github.com/kubernetes-sigs/controller-runtime/blob/66537ca5b7439b06f2f3b08901640f934834c9a1/pkg/log/zap/zap.go#L227-L233

If you would like to configure the logger (log level, stack trace level are supported for example), you can modify the cluster operator deployment manifest, like

```
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  namespace: foo
 ...
spec:
 ...
    spec:
      containers:
      - name: operator
        command:
        - /manager
        args:
        - zap-log-level=error
```
