### ISSUE TITLE
Expose rabbitmq plugins in the CRD

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#58]
Currently the list of plugins is generated by the operator but can only be customized once the cluster is deployed. Since the CR should define the desired state of a deployment, RabbitMQ plugins should be a part of it.

Describe the solution you'd like
I should be able to specify plugins like this:

```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: foo
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
```

spec.rabbitmq.additionalPlugins

The value of this field should be appended to the list of required plugins (`[rabbitmq_peer_discovery_k8s, rabbitmq_prometheus, rabbitmq_management]`) so that the required plugins and the plugins listed here are all enabled.

By default `spec.rabbitmq.additionalPlugins` should be empty.

### Scenario 1
I deploy the simplest cluster:
```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: simple
```

When I `kubectl edit` this cluster, I see:
```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: simple
spec:
# other properties here
```

When I check `rabbitmq-plugins list` I can see that `rabbitmq_management`, `rabbitmq_peer_discovery_k8s` and `rabbitmq_prometheus` are enabled since they are essential and therefore always enabled.

### Scenario 2
I deploy a cluster with plugin configuration:
```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: mqtt
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
```

When I `kubectl edit` this cluster, I see:
```
apiVersion: rabbitmq.pivotal.io/v1beta1
kind: RabbitmqCluster
metadata:
  name: mqtt
spec:
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
# other properties here
```

When I check `rabbitmq-plugins list` I can see that only `rabbitmq_mqtt`, `rabbitmq_management`, `rabbitmq_peer_discovery_k8s` and `rabbitmq_prometheus` are enabled.
