### ISSUE TITLE
Setting fixed NodePorts for amqp and http

### ISSUE THREAD

**Issue by tessierp** [rabbitmq/cluster-operator#580]
Hi,

Read the documentation and tried to set fixed NodePorts for qmqp and http and I just can't seem to get it to work. 
This is the yaml file I used to try and override the default which assigns random ports.. Any recommendations on how I should proceed to get fix NodePorts?

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: cpiir
spec:
  service:
    type: NodePort
    ports:
      - name: http
        protocol: TCP
        port: 15672
        targetPort: 15672
        nodePort: 31672
      - name: amqp
        protocol: TCP
        port: 5672
        targetPort: 5672
        nodePort: 30672

**Comment by mkuratczyk** [comment]
Our documentation only talks about [`spec.service.type`](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#service-type) and [`spec.service.annotations`](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#service-annotations). However, you can customize the service by using the [`spec.override.service`](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#override) property. Try this:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  service:
    type: NodePort
  override:
    service:
      spec:
        ports:
          - name: http
            protocol: TCP
            port: 15672
            targetPort: 15672
            nodePort: 31672
          - name: amqp
            protocol: TCP
            port: 5672
            targetPort: 5672
            nodePort: 30672
```
