### ISSUE TITLE
Following the quick install instructions I get an error related to persistent volume

### ISSUE THREAD

**Issue by Le0nlck** [rabbitmq/cluster-operator#601]
RabbitMQ cluster operator does not work in Kubernetes.
I have a kubernetes cluster 1.17.17 of 3 nodes. I deployed it with a rancher. According to this instruction I installed RabbitMQ cluster-operator: https://www.rabbitmq.com/kubernetes/operator/quickstart-operator.html
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
Its ok! but.. I have created this very simple configuration for the instance according to the documentation:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: test-rabbitmq
  ```
I have error:error while running "VolumeBinding" filter plugin for pod "rabbitmq-server-0": pod has unbound immediate PersistentVolumeClaims

after that i checked:
kubectl get storageclasses
and saw that there were no resources! I added the following storegeclasses:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
create pv and pvc:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-data-sigma
  labels:
    type: local
  namespace: test-rabbitmq
  annotations:
    volume.alpha.kubernetes.io/storage-class: rabbitmq-data-sigma
spec:
  storageClassName: local-storage
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data-sigma"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-data
  namespace: test-rabbitmq
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
      ```
I end up getting an error in the volume - which is being generated automated:
```FailedBinding   no persistent volumes available for this claim and no storage class is set  ```
please help to understand this problem!

![Снимок экрана от 2021-02-12 16-42-10](https://user-images.githubusercontent.com/24776932/107769372-51f94000-6d51-11eb-9522-f5dbe125669d.png)
![Снимок экрана от 2021-02-12 16-41-57](https://user-images.githubusercontent.com/24776932/107769374-5291d680-6d51-11eb-83ef-0db5c04fdf3d.png)
