### ISSUE TITLE
Share tls config with Web Stomp plugin

### ISSUE THREAD

**Issue by pintobikez** [rabbitmq/cluster-operator#617]
**Is your feature request related to a problem? Please describe.**
We currently use web_stomp plugin in a one node installation. We are moving into a kubernetes cluster and started using operator for it. We user cert-manager to install the certificates which works fine for queuing and the web interface. But we are having troubles into making the Web Stomp plugin to work with the centralized TLS config

**Describe the solution you'd like**
Whatever was done in https://github.com/rabbitmq/cluster-operator/issues/267

**Describe alternatives you've considered**
If it is impossible or extremely difficult to be done, I would appreciate any kind of guidance on making it work as is today.

**Additional context**

**Comment by ChunyiLyu** [comment]
@pintobikez What do you mean by centralized TLS config?

If you have enabled TLS and `rabbitmq_web_stomp` plugins in RabbitmqCluster, the TLS configuration is shared across plugins. For example, if your RabbitmqCluster looks like:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: plugins
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_web_stomp
  tls:
    secretName: tls-secret
```
The operator will automatically sets `web_mqtt.ssl.port`, `web_mqtt.ssl.cacertfile`, `web_mqtt.ssl.certfile`, and `web_mqtt.ssl.keyfile` in RabbitMQ configurations.

**Comment by pintobikez** [comment]
@ChunyiLyu 

Using: Image rabbitmq:3.8.9-managemen
this is how it looks like my rabbitmq cluster definition:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: development-rabbitmq
  namespace: rabbitmq-system
spec:
  service:
    type: NodePort
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  replicas: 1
  persistence:
    storageClassName: gp2encrypted
    storage: "8Gi"
  tls:
    secretName: dev-certificate-tls
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - mountPath: /tmp/definitions/
                name: definitions
            volumes:
            - name: definitions
              configMap:
                name: rabbitmq-definitions
  rabbitmq:
    additionalPlugins:
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_web_stomp
    additionalConfig: |
      load_definitions = /tmp/definitions/definitions.json
```
      
But when I look at the logs the only port that is open is plain http:

` 2021-02-26 15:44:48.052 [info] <0.2076.0> rabbit_web_stomp: listening for HTTP connections on 0.0.0.0:15674`

And the list of ports in the pod:

`
Ports
epmd: 4369/TCP
amqp: 5672/TCP
management: 15672/TCP
prometheus: 15692/TCP
web-stomp: 15674/TCP
amqps: 5671/TCP
management-tls: 15671/TCP
prometheus-tls: 15691/TCP
`
