### ISSUE TITLE
Enforcing TLS 1.2 or TLS 1.3 doesn't seem to be working

### ISSUE THREAD

**Issue by bdaoudtdc** [rabbitmq/cluster-operator#632]
## Describe the bug
I added
ssl_options.versions.1 = tlsv1.3
ssl_options.versions.2 = tlsv1.2
 to my additionalConfig in the cluster definition file.

I can see that the new config is available  in  90-userDefinedConfiguration.conf inside the container 
ssl_options.versions.1                = tlsv1.3
ssl_options.versions.2                = tlsv1.2

I expected that I will not be able to connect using TLS1 or TLS1.1 
openssl s_client -connect mycluster:myport -tls1

However , I have a successful connection . 

## Version and environment information
- RabbitMQ: [e.g. 3.8.12]
- RabbitMQ Cluster Operator: [e.g. 1.5.0 ]
- Kubernetes: [e.g. 1.17.13]

**Comment by Zerpet** [comment]
I'm not able to reproduce this behaviour using RabbitMQ 3.8.12, Operator 1.5.0 and Kubernetes 1.20.2. I'm using the following RabbitMQ cluster spec:

```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: bug-632
spec:
  replicas: 1
  service:
    type: NodePort
  tls:
    secretName: selfsigned-cert-tls
  rabbitmq:
    additionalConfig: |
      ssl_options.versions.1 = tlsv1.3
      ssl_options.versions.2 = tlsv1.2
```

When I attempt to connect to the TLS listener using `openssl`, I get:

```
CONNECTED(00000003)
139873416168576:error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version:ssl/record/rec_layer_s3.c:1544:SSL alert number 70
```

The SSL alert number 70 means that the protocol version is recognized but not supported, as expected. Can you share the following information?

- RabbitmqCluster definition
- Output of `kubectl describe rabbitmqcluster <your-rabbitmq-cluster-name>`
- The output of your `openssl s_client` command
