### ISSUE TITLE
Support large definitions import

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#638]
**Is your feature request related to a problem? Please describe.**

Operator provides an example manifest on importing definitions:

```

apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: import-definitions
spec:
  replicas: 1
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              volumeMounts:
              - mountPath: /path/to/exported/ # filename left out intentionally
                name: definitions
            volumes:
            - name: definitions
              configMap:
                name: definitions # Name of the ConfigMap which contains definitions you wish to import
  rabbitmq:
    additionalConfig: |
      load_definitions = /path/to/exported/definitions.json # Path to the mounted definitions file
```

This example has the limitation that the definitions file needs to be small enough to be saved in k8s etcd, which has a 2mb limit. We should investigate solutions for importing definitions files larger than 2mb (we have seen 150MB definitions for example). 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
