### ISSUE TITLE
Annotation to choose which rabbitmq-operator manages instance

### ISSUE THREAD

**Issue by james-callahan** [rabbitmq/cluster-operator#699]
**Is your feature request related to a problem? Please describe.**
To be able to run more than one instance of the rabbitmq operator in a cluster, we'd like a way to specify *which* rabbitmq-operator should act on a given Cluster manifest

**Describe the solution you'd like**
Add an environment variable to the operator, e.g. `OPERATOR_NAME` which is checked against a `RabbitmqCluster` annotation such as `rabbitmq.com/cluster-operator/name`.

**Additional context**
The proposed solution is similar to how you can have multiple ingresses in a given cluster selected by `kubernetes.io/ingress.class`

**Comment by ChunyiLyu** [comment]
@james-callahan Thanks for using cluster operator 😸 

This is an interesting idea and can certainly be done with the operator. I would like to understand what specific use case it could enable for you. With the example of multiple ingress controllers, they are functionally different and I can see why it's necessary for certain environments. For cluster operators, later versions only add features and never remove any feature support. Could you explain more your needs for such this feature request?

On the other hand, if you wish to have multiple operators in your k8s clusters each managing a set of rabbits, you can do that today with namespacing the cluster operator by setting the environment variable OPERATOR_SCOPE_NAMESPACE on the operator deployment. For like:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  template:
...
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_SCOPE_NAMESPACE
           value: <the-specific-namespace-for-this-operator>
        image: rabbitmqoperator/cluster-operator:1.7.0
        name: operator
...
```
This will make the operator only watch for rabbit clusters in one namespace and you could have multiple operators deployed in different namespaces.
