### ISSUE TITLE
Reference admin secret and client service in RabbitmqCluster status

### ISSUE THREAD

**Issue by st3v** [rabbitmq/cluster-operator#72]
**Is your feature request related to a problem? Please describe.**
Currently, the user of the `RabbitmqCluster` CR must know what the names of the `Secret` and client `Service` resources are in order to retrieve the necessary information to connect to the RabbitMQ instance as an admin. This is obviously problematic from the perspective of usability. Moreover, this causes the naming of these internal resources to become part of the API. If we ever change the internal names, users will face problems.

**Describe the solution you'd like**
Have `RabbitmqCluster.status` point the user to the necessary `Secret` and `Service` using a reference that specifies the resources' name and its namespace. For the secret, the reference should also describe the names of the individual keys.

```yaml
  apiVersion: rabbitmq.pivotal.io/v1beta1
  kind: RabbitmqCluster
  metadata:
    ...
  spec:
    ...
  status:
    conditions:
      ...
    admin:
      secretRef:
        name: on-demand-claim-rabbitmq-admin
        namespace: default
        keys:
          password: password
          username: username
      serviceRef:
        name: on-demand-claim-rabbitmq-ingress
        namespace: default
```

**Describe alternatives you've considered**
n/a

**Additional context**
I'd be open to suggestions on alternative naming for the proposed properties.
