### ISSUE TITLE
Override does not patch with null values

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#741]
## Describe the bug

Create a RMQ with manifest like so:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
  namespace: rabbitmq-system
spec:
  image: rabbitmq:3.8.17-management
  override:
    statefulSet:
      spec:
        template:
          spec:
            securityContext: null
            containers: []
            initContainers:
            - name: setup-container
               securityContext: null
```

**Expected behavior**

Deployed statefulSet pod spec should have securityContext set to `null` or not set (empty). However, both `securityContext: null` is  omitted after the manifest is saved (if you get the RMQ manifest after creation, you don't see `securityContext: null` in the manifest).

Setting fields to `null` is a documented way of deleting a field for [strategic merge patch ](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md#maps). When applying the same patch but using `kubectl patch` directly, securityContext can be set to null succesfully. 

Example patch:
```yaml
spec:
 template:
   spec:
     securityContext: null
     initContainers:
     - name: setup-container
       securityContext: null
```
applied by running `k patch sts sample-server --patch "$(cat patch.yaml)"`

## Version and environment information
- RabbitMQ: 3.8.17
- RabbitMQ Cluster Operator: latest main
- Kubernetes: [e.g. 1.18.0]
- Cloud provider or hardware configuration:
