### ISSUE TITLE
Failed to log RabbitMQ in file

### ISSUE THREAD

**Issue by soleimaniamir** [rabbitmq/cluster-operator#771]
I'm trying to send RabbitMQ logs to both console and file, I'm using RabbitMQ Operator to run cluster and this `definition.yaml`:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  image: rabbitmq:3.8.9-management
  replicas: 3
  imagePullSecrets:
  - name: rabbitmq-cluster-registry-access
  service:
    type: ClusterIP
  persistence:
    storageClassName: rbd
    storage: 20Gi
  resources:
    requests:
      cpu: 2000m
      memory: 6Gi
    limits:
      cpu: 2000m
      memory: 6Gi
  rabbitmq:
    additionalConfig: |
      log.console = true
      log.console.level = debug
      log.file = rabbit.log
      log.dir = /var/lib/rabbitmq/
      log.file.level = debug
      log.file = true
    additionalPlugins:
      - rabbitmq_top
      - rabbitmq_shovel
      - rabbitmq_management
      - rabbitmq_peer_discovery_k8s
      - rabbitmq_stomp
      - rabbitmq_prometheus
      - rabbitmq_peer_discovery_consul
```
after running on the cluster, this is console logs:

  ```
##  ##      RabbitMQ 3.8.9
  ##  ##
  ##########  Copyright (c) 2007-2020 VMware, Inc. or its affiliates.
  ######  ##
  ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com
  Doc guides: https://rabbitmq.com/documentation.html
  Support:    https://rabbitmq.com/contact.html
  Tutorials:  https://rabbitmq.com/getstarted.html
  Monitoring: https://rabbitmq.com/monitoring.html
  Logs: <stdout>
  Config file(s): /etc/rabbitmq/rabbitmq.conf
                  /etc/rabbitmq/conf.d/default_user.conf
  Starting broker...2021-07-18 07:22:26.203 [info] <0.272.0>
 node           : rabbit@rabbitmqcluster-server-0.rabbitmqcluster-nodes.rabbitmq-system
 home dir       : /var/lib/rabbitmq
 config file(s) : /etc/rabbitmq/rabbitmq.conf
                : /etc/rabbitmq/conf.d/default_user.conf
 cookie hash    : shP20jU/vTqNF4lW9g0tqg==
 log(s)         : <stdout>
 database dir   : /var/lib/rabbitmq/mnesia/rabbit@rabbitmqcluster-server-0.rabbitmqcluster-nodes.rabbitmq-system
```
and after starting the cluster there is no log file in the path I specified and only `crash.log` is in the directory:
```
$ls
crash.log
```
 what should I do?

**Comment by Zerpet** [comment]
Hello @soleimaniamir 👋 

You ran into a "gotcha" with environment variables taking precedence over the configuration file. The official Dockerfile sets the variable `RABBITMQ_LOGS` to `-`, so that RabbitMQ logs to the standard output (which is a desired thing in containers).

https://github.com/docker-library/rabbitmq/blob/9331f6a8c3f6484d15ff1498f3d82a886f168617/3.8/ubuntu/Dockerfile#L205-L206

The second issue I observe in your manifest is `log.file = true`. This key is either `false` to disable file logging, or a path. You can achieve file logging by overriding the env var and removing `log.file = true`. Something like this:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster
spec:
  [...]
  rabbitmq:
    additionalConfig: |
      log.console = true
      log.console.level = debug
      log.file = rabbit.log
      log.dir = /var/lib/rabbitmq/
      log.file.level = debug
   [...]
    envConfig: |
      RABBITMQ_LOGS="rabbit.log"
```
