### ISSUE TITLE
consumer_timeout configuration

### ISSUE THREAD

**Issue by wardzxzxc** [rabbitmq/cluster-operator#787]
Hello! I'm using RabbitMQ 3.8.16 Management and have the following configuration for the RabbitmqCluster:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  rabbitmq:
    additionalConfig: |
      consumer_timeout = 10000
```

As per the docs [here](https://www.rabbitmq.com/consumers.html) , I know that the consumer_timeout is configurable via the `rabbitmq.conf` and to add in new additional configuration for `rabbitmq.conf`, I'll have to add it as shown in the code above (reference from [here](https://www.rabbitmq.com/kubernetes/operator/using-operator.html#additional-config)). I just wanted to know, is this correct? Because by right an error should be shown if the messages are unack for 10 seconds (in this case) but I couldn't see the error being raised when I tried to mimic a message being unack for 10 seconds.

Just for some information, I'm currently doing it locally on `minikube` and using RabbitMQ as a message broker for my Celery worker. Each worker is only allowed to finish 1 task at a time and each task takes more than 10 seconds to finish. Based on what I understand of Celery, the message is only acknowledged right before the Celery worker executes the task. Given the above situation, queued up messages should only be acknowledged after 10 seconds and thus raise a consumer timed out. However, that's not what I'm seeing.

Appreciate any answers!
