### ISSUE TITLE
How should I handle backup/restore using this operator?

### ISSUE THREAD

**Issue by DanielPritchard** [rabbitmq/cluster-operator#792]
Hello

I'm evaluating using the operator to run rabbit in my organisation (to replace AWS SNS/SQS). I have some questions about backup/restore.
I am looking for a way to restore my cluster in a DR scenario, but I don't see anything about backups in your examples folder. Basically I'm looking to either re-use existing PV/PVC on cluster recreation or handle having a backup and restore programmatically

I would like to be able to boot up a new cluster and use snapshots (we use velero) of the existing PVCs. However its unclear how to re-use existing volumes.

I have tried overriding the `volumeClaimTemplate` however the operator just creates new PVCs rather than using the existing ones, even when creating a cluster using the same names etc.

Any guidance would be appreciated,
Thanks

p.s.
Really good experience using your operator so far!

**Comment by mkuratczyk** [comment]
Hi,

As you already know - there is currently no explicit support for reusing PVs. However, if a PVC with the expected name (`persistence-FOO-server-0` etc) already exists, it will be used. Therefore, the following scenario should work:
1. Assuming you already have a PV that you want to use
2. Create a PVC that refers to that PV ( `persistence-foo-server-0` and so on for other nodes if applicable)
3. If the PVC is not ready, it may be necessary to "unclaim" it (remove `claimRef` from the PV spec)
3. At this point you should have a a PV and PVC ready to use
4. Deploy a cluster with the name `foo` - it should reuse the PVC and PV

There are (at least) two caveats though:
1. Because of the way RabbitMQ stores data on disk, the contents of the volume will only work if the new node has the same name (so if the cluster was called `foo` in the past, it needs to be called `foo` now as well - https://www.rabbitmq.com/clustering.html#issues-hostname). Alternatively you'd need to make some adjustments to the contents of the persistent disk
2. When deploying the new instance, a new `Secret` will be created with the credentials for the default user. However, RabbitMQ only creates the default user on a fresh node and since you reuse a PV, it's not considered a fresh deployment. Therefore, you'll have a `Secret` called `foo-default-user` that contains credentials that don't actually work - you need to use the credentials you used on the old cluster instead. You can update that `Secret` with the old credentials manually.

We want to make the restore experience better so it'd help a lot if you could:
1. Confirm whether the above is acceptable right now
2. Let us know the exact use cases you expect (why do you need to restore RabbitMQ, is it within the same namespace/cluster or not, whether the old cluster still works when you deploy the new one, etc)
3. If you have specific ideas to how to improve this workflow - we are all ears

Thanks,

**Comment by DanielPritchard** [comment]
Hello,

Thanks for your reply!

I have tested the the above solution and it works. 
The caveats are fine for us too. The replacement cluster has the same name so that's not a problem and we can deal with the default user + password being wrong in the kube secret object because we can template our own Secret.

Our use case is disaster recovery, if the cluster is ever taken down by mistake (by a human error) we want to be able to restore without losing data.
This would all be done in the same kube cluster with the same cluster name etc.


Examples if anyone else finds this useful

Rabbit Cluster:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 3
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: persistence
            namespace: rabbitmq
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            volumeMode: Filesystem
```

 Example PVCs
```yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-rabbitmq-server-0
spec:
  storageClassName: gp2-retain-a
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-rabbitmq-server-1
spec:
  storageClassName: gp2-retain-b
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-rabbitmq-server-2
spec:
  storageClassName: gp2-retain-c
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
```

Example storage classes (AWS)
```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: gp2-retain-a
parameters:
  type: gp2
  zone: eu-west-2a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: gp2-retain-b
parameters:
  type: gp2
  zone: eu-west-2b
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: gp2-retain-c
parameters:
  type: gp2
  zone: eu-west-2c
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

```
