### ISSUE TITLE
Seeing only 1 node, cluster split brain ?

### ISSUE THREAD

**Issue by ebuildy** [rabbitmq/cluster-operator#834]
Using operator ``1.8.2`` with RabbitMQ ``3.8.21`` on kubernetes ``1.19`` , with polaris constraints (pod must be read-only , etc...).

The 3 pods are running fine, CRD cluster status is OK (ReconcileSuccess: true) but I see always 1 node on management web UI and ``rabbitmqctl cluster_status`` is reporting only 1 running node:

```
Cluster status of node rabbit@datahub-server-2.datahub-nodes.dev-steam ...
Basics

Cluster name: datahub

Disk Nodes

rabbit@datahub-server-2.datahub-nodes.dev-steam

Running Nodes

rabbit@datahub-server-2.datahub-nodes.dev-steam

Versions

rabbit@datahub-server-2.datahub-nodes.dev-steam: RabbitMQ 3.8.21 on Erlang 24.0.5

Maintenance status

Node: rabbit@datahub-server-2.datahub-nodes.dev-steam, status: not under maintenance

Alarms

Memory alarm on node rabbit@datahub-server-2.datahub-nodes.dev-steam

Network Partitions

(none)

Listeners

Node: rabbit@datahub-server-2.datahub-nodes.dev-steam, interface: 0.0.0.0, port: 15672, protocol: http, purpose: HTTP API
Node: rabbit@datahub-server-2.datahub-nodes.dev-steam, interface: 0.0.0.0, port: 15692, protocol: http/prometheus, purpose: Prometheus exporter API over HTTP
Node: rabbit@datahub-server-2.datahub-nodes.dev-steam, interface: [::], port: 25672, protocol: clustering, purpose: inter-node and CLI tool communication
Node: rabbit@datahub-server-2.datahub-nodes.dev-steam, interface: 0.0.0.0, port: 5672, protocol: amqp, purpose: AMQP 0-9-1 and AMQP 1.0

Feature flags

Flag: drop_unroutable_metric, state: enabled
Flag: empty_basic_get_metric, state: enabled
Flag: implicit_default_bindings, state: enabled
Flag: maintenance_mode_status, state: enabled
Flag: quorum_queue, state: enabled
Flag: user_limits, state: enabled
Flag: virtual_host_metadata, state: enabled
```

I dont see any error on pods logs, can see RabbitMQ is trying to create the cluster:

```
2021-09-06 18:29:16.452 [debug] <0.273.0> POST https://kubernetes.default:443/api/v1/namespaces/dev-steam/events/ ["{\"count\":1,\"involvedObject\":{\"apiVersion\":\"v1\",\"kind\":\"RabbitMQ\",\"name\":\"pod/datahub-rabbitmq-operator-server-0\",\"namespace\":\"dev-steam\"},\"lastTimestamp\":\"2021-09-06T18:29:16+00:00\",\"message\":\"Node rabbit@datahub-rabbitmq-operator-server-0.datahub-rabbitmq-operator-nodes.dev-steam is registered\",\"metadata\":{\"name\":\"datahub-rabbitmq-operator-server-0.1630952956452\",\"namespace\":\"dev-steam\"},\"reason\":\"Created\",\"source\":{\"component\":\"datahub-rabbitmq-operator-server-0/rabbitmq_peer_discovery\",\"host\":\"datahub-rabbitmq-operator-server-0\"},\"type\":\"Normal\"}"]
```

I guess I should see the 3 nodes here? How can I debug it? 

Cluster declaration:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: datahub
spec:
  replicas: 3
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 512Mi
  rabbitmq:
    additionalConfig: |
      channel_max = 1050
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              qwant.com/fw.kubernetes: allow
          spec:
            securityContext:
              fsGroup: 1000
              runAsUser: 1000
            volumes:
            - name: rabbitmq-config
              emptyDir: {}
            - name: rabbitmq-log
              emptyDir: {}
            initContainers:
            - name: setup-container
              command:
                - sh
                - '-c'
                - >-
                  cp /tmp/erlang-cookie-secret/.erlang.cookie
                  /var/lib/rabbitmq/.erlang.cookie && chmod 600
                  /var/lib/rabbitmq/.erlang.cookie ; cp
                  /tmp/rabbitmq-plugins/enabled_plugins /operator/enabled_plugins ; echo
                  '[default]' > /var/lib/rabbitmq/.rabbitmqadmin.conf && sed -e
                  's/default_user/username/' -e 's/default_pass/password/'
                  /tmp/default_user.conf >> /var/lib/rabbitmq/.rabbitmqadmin.conf &&
                  chmod 600 /var/lib/rabbitmq/.rabbitmqadmin.conf;
                  cp -r /etc/rabbitmq/. /etc/rabbitmq2
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
              volumeMounts:
              - name: rabbitmq-config
                mountPath: /etc/rabbitmq2
            containers:
            - name: rabbitmq
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
              volumeMounts:
              - name: rabbitmq-config
                mountPath: /etc/rabbitmq
              - name: rabbitmq-log
                mountPath: /var/log/rabbitmq
```

network policy.yaml:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: hot-rabbitmq
    argocd.argoproj.io/instance: datahub-hot-rabbitmq
    chart: networkpolicy
    heritage: Helm
    release: hot-rabbitmq
  name: rabbitmq-operator
spec:
  egress:
    - ports:
        - port: 5672
          protocol: TCP
        - port: 15672
          protocol: TCP
        - port: 25672
          protocol: TCP
        - port: 4369
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: datahub
              app.kubernetes.io/component: rabbitmq
  ingress:
    - ports:
        - port: 5672
          protocol: TCP
    - from:
        - namespaceSelector:
            matchLabels:
              name: nginx-ingress
          podSelector:
            matchLabels:
              app: nginx-ingress
      ports:
        - port: 15672
          protocol: TCP
    - ports:
        - port: 9419
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: datahub
              app.kubernetes.io/component: rabbitmq
        - namespaceSelector:
            matchLabels:
              name: rabbitmq-system
      ports:
        - port: 5672
          protocol: TCP
        - port: 15672
          protocol: TCP
        - port: 25672
          protocol: TCP
        - port: 4369
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/name: datahub
      app.kubernetes.io/component: rabbitmq
  policyTypes:
    - Ingress
    - Egress
```
