### ISSUE TITLE
Add an option to do not create default-user secret

### ISSUE THREAD

**Issue by olfway** [rabbitmq/cluster-operator#840]
I would like to use a predefined admin username and password and prevent rabbitmq-operator from creating it

It seems I can create default-user secret first and then create a cluster, so the operator will use that secret,
but unfortunately in gitops way you cannot guarantee the order of resource creating

Also, I'm planning to use external-secret controller to get the secret from aws secret manager and it will take some time to fetch data and create a secret.

So I need a way to tell rabbitmq-operator to not create a secret and just wait for it

**Comment by ChunyiLyu** [comment]
Hi @olfway, we discussed in a team meeting about supporting different secret backend (vault support is coming soon, but we haven't considered AWS secret for your information). Our conclusion is it's a relatively complicated track of work that we might start looking at soon. However, at this time, we cannot provide an estimate/guarantee about timeline.

On the other hand, there is a workaround that you can try with the current operator. The Rabbitmq Cluster Operator creates the k8s secret for the default user secret with a specific format and object name. The secret name is `RMQNAME-default-user`. If you create the secret with this name then create the RabbitMQ cluster, operator will not generate the user credential and will take the username and password from the pre existing secret. Would this workaround work for use case?

The default user secret has to have key `default_user.conf` and with the object name of `RMQNAME-default-user`. For example, if your rabbitmqcluster is named "sample". You can create a k8s secret such as:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sample-default-user
stringData:
  default_user.conf: |
    default_user = <USERNAME-HERE>
    default_pass = <PASSWORD-HERE>
  password: <PASSWORD-HERE> # this line is only necessary if you also use messaging topology operator
  username: <USERNAME-HERE> # this line is only necessary if you also use messaging topology operator
```

**Comment by olfway** [comment]
@ChunyiLyu thank you for the information!
I'm using argo-cd (git ops tool), so all manifest applied to k8s at once
I cannot create secret first, then wait and after that create cluster

I found I can override rabbitmq-confd volume itself:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            volumes:
              - name: rabbitmq-confd
                projected:
                  defaultMode: 420
                  sources:
                    - secret:
                        name: rabbitmq-cluster-admin
                        items:
                          - key: default_user.conf
                            path: default_user.conf
                    - configMap:
                        name: rabbitmq-cluster-server-conf
                        items:
                          - key: operatorDefaults.conf
                            path: operatorDefaults.conf
                          - key: userDefinedConfiguration.conf
                            path: userDefinedConfiguration.conf
```
I'm using non-standard secret name here "rabbitmq-cluster-admin" instead of rmqname-default-user
This way it's not important if rmq cluster will be started before secret ready or not

Rabbitmq operator will start rabbitmq pods, but they will wait before the external secrets controller creates rabbitmq-cluster-admin secret with my pre-defined password

Also rabbitmq operator will create rmqname-default-user secret but it will be unused
