### ISSUE TITLE
RabbitMQ Cluster Service's port names cause issue in Istio [KIA0601: Port name must follow <protocol>[-suffix] form]

### ISSUE THREAD

**Issue by klydra** [rabbitmq/cluster-operator#878]
## Describe the bug
When using a RabbitMQ Cluster with Istio, the service which is automatically created an can't be changed manually, is creating errors.
Since the Service is managed by the Operator, you can't simply change the port names manually without rebuilding the operator AFAIK.

## To Reproduce
1. Install Istio
2. Deploy RabbitMQ Operator
3. Deploy a RabbitMQ Cluster
4. Inspect the rabbitmq-queue service in the Kiali Dashboard

**Expected behavior**
There should be no problem reported by Istio with the out of the box configuration.

## Screenshots
![image](https://user-images.githubusercontent.com/40038209/138507629-7216319f-f13f-4ee5-97e4-28dd455b8002.png)
![image](https://user-images.githubusercontent.com/40038209/138507672-181eb985-e7cd-45c0-b4bd-fbde82848e9b.png)

## Version and environment information
- RabbitMQ: 3.8.9-management
- RabbitMQ Cluster Operator: 1.10.0
- Kubernetes: 
- Cloud provider or hardware configuration: MicroK8S + Istio

## Configuration
rabbitmq-cluster.yaml
```yaml
kind: RabbitmqCluster
apiVersion: rabbitmq.com/v1beta1
metadata:
  name: rabbitmq-queue
  namespace: api
spec:
  image: 'rabbitmq:3.8.9-management'
  override: {}
  persistence:
    storageClassName: microk8s-hostpath
    storage: 10Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_event_exchange
  replicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  service:
    type: ClusterIP
  terminationGracePeriodSeconds: 604800
  tls:
    disableNonTLSListeners: true
    secretName: tls-credential
```

Automatically generated service
```yaml
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-queue
  namespace: api
spec:
  ports:
    - name: prometheus-tls
      protocol: TCP
      port: 15691
      targetPort: 15691
    - name: amqps
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: management-tls
      protocol: TCP
      port: 15671
      targetPort: 15671
  selector:
    app.kubernetes.io/name: rabbitmq-queue
  type: ClusterIP
```
