### ISSUE TITLE
support set securityContext

### ISSUE THREAD

**Issue by alochym01** [rabbitmq/cluster-operator#880]
error: error validating "rabbitmq-cluster.yaml": error validating data: ValidationError(RabbitmqCluster.spec): unknown field "securityContext" in com.rabbitmq.v1beta1.RabbitmqCluster.spec; if you choose to ignore these errors, turn validation off with --validate=false
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbit-alochym
    namespace: rabbitmq-system
spec:
    securityContext:
        fsGroup: 1000
        runAsUser: 1000    
    replicas: 1
    persistence:
        storageClassName: local-storage
        storage: 10Gi    
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Equal"
      #value: "rabbitmq"
      effect: "NoSchedule"    
      # node-role.kubernetes.io/master:NoSchedule
    resources:
        requests:
            cpu: 500m
            memory: 1Gi
        limits:
            cpu: 4000m
            memory: 8Gi
```
