### ISSUE TITLE
StatefulSet doesn't propagate Metadata.labels to pod spec

### ISSUE THREAD

**Issue by baznikin** [rabbitmq/cluster-operator#896]
I'm using RMQ Operator with Kustomize. I can't use additional resources like PodDisruptionBudget automatically because additional labels, assigned by kustomize, doesn't propagate down to pods (and selector failed to match any RMQ pods).

Example:
Kustomize add 'namespace: dev' and label 'env: dev' to all resources. We see it in SS manifest but not in pod spec

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: mq-rosnetf
    app.kubernetes.io/part-of: rabbitmq
    env: dev
  name: mq-rosnetf-server
  namespace: dev
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: mq-rosnetf
  serviceName: mq-rosnetf-nodes
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq
        app.kubernetes.io/name: mq-rosnetf
        app.kubernetes.io/part-of: rabbitmq
```

PDB, created at same time, try to find pods by selector and can't:

```
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: mq-rosnetf
        env: dev

```

**Comment by Zerpet** [comment]
That is correct, we do not propagate labels to the Pod template since #442, since it caused unwanted Pod restart in certain GitOps systems like [Flux](https://fluxcd.io/). In addition to this, we reasoned that, changing a label in a Kubernetes object is something light, and it shouldn't have strong, potentially harmful, side-effect consequences, like restarting a RabbitMQ Pod, which might cause a greater impact in a system.

With regards to your use case, you could configure the PDB selector to use one of the pre-populated labels like `app.kubernetes.io/name: mq-rosnetf` (specific to one STS), or `app.kubernetes.io/component: rabbitmq` (all RabbitMQ STS), and given that PDBs are namespaced, it will only affect the StatefulSets within that namespace e.g. `dev`. Would something like this help to achieve what you are trying to accomplish?

**Comment by baznikin** [comment]
> With regards to your use case, you could configure the PDB selector to use one of the pre-populated labels like `app.kubernetes.io/name: mq-rosnetf` (specific to one STS), or `app.kubernetes.io/component: rabbitmq` (all RabbitMQ STS), and given that PDBs are namespaced, it will only affect the StatefulSets within that namespace e.g. `dev`. Would something like this help to achieve what you are trying to accomplish?

Too sad - it won't help! Kustomize add labels to all resources. Actually I use only `app.kubernetes.io/name` in PDB manifest, but kustomize enrich in with additional labels - this tool designed to do so. Only way to overcome is to NOT use kusomize for PDB and it kill whole idea.
To better illustrate usage there is cuts from actual manifests and live resources - https://gist.github.com/baznikin/2491c3a430577ea7036315b70539106e

> That is correct, we do not propagate labels to the Pod template since #442, since it caused unwanted Pod restart in certain GitOps systems like [Flux](https://fluxcd.io/). In addition to this, we reasoned that, changing a label in a Kubernetes object is something light, and it shouldn't have strong, potentially harmful, side-effect consequences, like restarting a RabbitMQ Pod, which might cause a greater impact in a system.

Any chances to make this behaviour customizable? Another option - let Operator create not only StatefulSet, Pods and Services but PDB too

**Comment by Zerpet** [comment]
I'm not keen to make a change in the functionality to workaround a limitation in a YAML templating tool. I would argue that kustomize should give the flexibility to choose where my labels are applied, and selectively exclude certain fields in certain kinds.

With regards to your issue, you can get the label in the Pod by using the StatefulSet override feature. The final YAML for `RabbitmqCluster` should look like this:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmqcluster
spec:
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              env: dev
  service:
    type: LoadBalancer
```

Since you only want this label for certain overlays, I guess you could patch the `RabbitmqCluster` in the overlay and leave the base manifest as is. Hope this helps!
