### ISSUE TITLE
add `RabbitmqCluster.spec.persistence.selector` to select PV to bind

### ISSUE THREAD

**Issue by wenmingwei** [rabbitmq/cluster-operator#916]
Feature Requirement:
> add `RabbitmqCluster.spec.persistence.selector` to select PV to bind

Backgroud:
> I allocated RabbitmqCluster and cluster of other product on same nodes to share resources, when I created local-storage PV for each cluster(one PV for RabbitmqCluster and one PV for cluster of other product).
> But I cannot bind RabbitmqCluster.spec.persistence to specified PV which is labeled.
>

**Comment by Zerpet** [comment]
The cluster operator creates a PVC dynamically using the [StatefulSet volume claim template field](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#volume-claim-templates). We did not consider static provisioned PVs as an option, and it makes more sense to support mainly dynamic PV provisioning.

If you still want to use the PV you created, you can override the PVC claim with the StatefulSet override feature, something like this:

```yaml
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmqcluster
spec:
  override:
    statefulSet:
      spec:
        volumeClaimTemplates:
          - spec:
              accessModes:
                - ReadWriteOnce
              selector:
                matchLabels:
                  rabbitmq: mylabel
              resources:
                requests:
                  storage: "15Gi"
            metadata:
              name: persistence
  persistence:
    storage: "15Gi"
```

The field `.spec.override.statefulSet.spec.volumeClaimTemplate[].metadata.name` is required and must be set to that value. You can tune the storage request and the label selector. Hope this helps!
