### ISSUE TITLE
Disabling affinity rule in override.statefulset does not get applied to statefulSet

### ISSUE THREAD

**Issue by hoyhbx** [rabbitmq/cluster-operator#928]
## Describe the bug
I was trying to patch the `/spec/override/statefulSet/spec/template/spec/affinity` to `null` to delete the affinity rule that was previously specified for rabbitmqCluster under `/spec/affinity`. It seems this null value is lost when unmarshalling and then marshalling. This causes that the affinity rule deleting is not applied to the statefulSet.

## To Reproduce
Steps to reproduce this behavior:
1. Deploy cluster-operator using the command: 
```kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml```
2. Deploy rabbitmqCluster with the following yaml file:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
spec:
  image: "rabbitmq:3.8.21-management"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - sample
          topologyKey: kubernetes.io/hostname
  persistence:
    storage: 20Gi
  replicas: 2
```
3. Patch the rabbitmqCluster using the patch file with the command: `kubectl patch rabbitmqCluster sample --type merge --patch-file patch.yaml`

**patch.yaml**:    
```yaml
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            affinity: null
```
4. Check rabbitmqCluster spec, the affinity in override is omitted:
```json
"override": {
    "statefulSet": {
        "spec": {
            "template": {
                "spec": {
                    "containers": []
                }
            }
        }
    }
}
```
and in the statefulSet spec, affinity rule is not deleted.

The root cause here is because the override.statefulset.spec.template is unmarshalled into *corev1.podSpec at first and then the operator marshals it back to JSON format so that it can apply JSON strategic merge. However, the affinity field is omitted due to the `omitempty` rule in coreV1 API, and the patch no longer has `affinity: null` in it. The essential thing that's missed here is that, for a JSON patch P, `marshal(unmarshal(P))` does not necessarily equal to P.

**Expected behavior**
The patch in the patch.yaml would delete the affinity policy in statefulSet

## Version and environment information
- rabbitmq: rabbitmq:3.8.21-management
- rabbitmq cluster operator: rabbitmqoperator/cluster-operator:1.10.0
- Kubernetes: 1.21.1
- Running on Kind cluster
 
## Additional context
This is a very similar issue(https://github.com/rabbitmq/cluster-operator/issues/741) reported before, but the fix was specifically for securityContext. This problem needs a systematic fix(e.g. marshal the field override into Raw JSON format) because there are dozens of other fields in the coreV1 API that could cause the same issue.
