### ISSUE TITLE
Operator v1.11.0 does not support Kubernetes v1.18 out of the box

### ISSUE THREAD

**Issue by coro** [rabbitmq/cluster-operator#930]
## Describe the bug
Operator fails to create RabbitmqClusters on v1.18 Kubernetes with default feature flags.

## To Reproduce
Applying the manifest:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example-test
spec:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
```
to a cluster running Kubernetes 1.18 results in the following error:
```
Service "example-test" is invalid: [spec.ports[0].appProtocol: Forbidden: This field can be enabled with the ServiceAppProtocol feature gate, spec.ports[1].appProtocol: Forbidden: This field can be enabled with the ServiceAppProtocol feature gate, spec.ports[2].appProtocol: Forbidden: This field can be enabled with the ServiceAppProtocol feature gate]
```

1.18 is marked as supported according to the README, and does not mention the need of feature flags.

**Expected behavior**
Expected to be able to use the operator without enabling any feature flags.

## Version and environment information
- RabbitMQ: N/A
- RabbitMQ Cluster Operator: 1.11.0
- Kubernetes: 1.18.x
- Cloud provider or hardware configuration: N/A
 
## Additional context
Looks like the `ServiceAppProtocol` flag defaults to false in 1.18, and true 1.19 onwards: https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Introduced by this commit: https://github.com/rabbitmq/cluster-operator/commit/98789cb47f27a3c844281be9c55d356a50c7327d
