### ISSUE TITLE
Creating an Ingress for the Management UI in a RabbitmqCluster spec

### ISSUE THREAD

**Issue by YannayH** [rabbitmq/cluster-operator#940]
Currently, in order to access a cluster's management UI we have to use a **temporary** port forward, which makes it problematic to have a consistent way to access the UI.

It would be great if we could define an ingress within the RabbitmqCluster spec, which will create an ingress forwarding to the cluster's management UI.

**Comment by Zerpet** [comment]
I think it would be nice to have some automation around the creation of an `Ingress`, however I do not want to embed the entire `Ingress` spec in the `RabbitmqCluster`. It can be interesting to generate an ingress with the name of the `RabbitmqCluster` name and `-rabbitmq` suffix, with a rule to match prefix `$rabbitmqClusterName + "-rabbitmq"`, and automagically set the backend Service to the same Service we create.

I think something like this in `RabbitmqCluster` spec:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
spec:
  ingress:
    ingressClassName: my-ingress-class
    annotations:
      some/annotation: foo-bar
```

Resulting in the creation of an `Ingress` in these lines:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-rabbitmq
  annotations:
    some/annotation: foo-bar
spec:
  ingressClassName: my-ingress-class
  rules:
  - http:
      paths:
      - path: /hello-world-rabbitmq
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 15672
```

There are some caveats in the UX: the user needs to know their Ingress IP or DNS. It's not easy to observe (monitor) and troubleshoot a misconfigured Ingress.
