### ISSUE TITLE
A lot of reconciling events happens on a short time without any clear reason

### ISSUE THREAD

**Issue by dorshay6** [rabbitmq/cluster-operator#944]
## Describe the bug
The cluster or any configuration related to it wasn't changed in the last week, suddenly we saw reconciling logs every few seconds, this caused one of the pods and his queues some downtime.

Help is needed as we don't feel comfortable with the operator in production right now 

```
Finished reconciling |   | 2022-01-30T01:55:24.287622672Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:55:24.287622672Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:55:24.287622672Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"app.kubernetes.io/name":"production-ready"}}}]}}}}},"terminationGracePeriodSeconds":604800,"secretBackend":{}} | 2022-01-30T01:55:24.287622672Z
Finished reconciling |   | 2022-01-30T01:55:14.317850095Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:55:14.317850095Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:55:14.317850095Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"app.kubernetes.io/name":"production-ready"}}}]}}}}},"terminationGracePeriodSeconds":604800,"secretBackend":{}} | 2022-01-30T01:55:14.317850095Z
Finished reconciling |   | 2022-01-30T01:55:14.317850095Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:55:14.317850095Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:55:14.317850095Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"app.kubernetes.io/name":"production-ready"}}}]}}}}},"terminationGracePeriodSeconds":604800,"secretBackend":{}} | 2022-01-30T01:55:14.317850095Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:55:09.291413108Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:55:09.291413108Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"app.kubernetes.io/name":"production-ready"}}}]}}}}},"terminationGracePeriodSeconds":604800,"secretBackend":{}} | 2022-01-30T01:55:09.291413108Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:54:54.293612815Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:54:54.293612815Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"app.kubernetes.io/name":"production-ready"}}}]}}}}},"terminationGracePeriodSeconds":604800,"secretBackend":{}} | 2022-01-30T01:54:54.293612815Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:54:39.290037216Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:54:39.290037216Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":{"matchLabels":{"app.kubernetes.io/name":"production-ready"}}}]}}}}},"terminationGracePeriodSeconds":604800,"secretBackend":{}} | 2022-01-30T01:54:39.290037216Z
updated resource rabbitmq-server of Type   *v1.StatefulSet |   | 2022-01-30T01:54:24.290501390Z
updated resource rabbitmq-nodes of Type   *v1.Service |   | 2022-01-30T01:54:24.290501390Z
Start reconciling | {"replicas":4,"image":"rabbitmq:3.8.21-management","service":{"type":"LoadBalancer","annotations":{"cloud.google.com/load-balancer-type":"Internal"}},"persistence":{"storage":"500Gi"},"resources":{"limits":{"cpu":"2","memory":"4Gi"},"requests":{"cpu":"2","memory":"4Gi"}},"affinity":{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":[{"labelSelector":{"matchExpressions":[{"key":"app.kubernetes.io/name","operator":"In","values":["production-ready"]}]},"topologyKey":"kubernetes.io/hostname"}]}},"rabbitmq":{"additionalConfig":"cluster_partition_handling   = pause_minority\nvm_memory_high_watermark_paging_ratio =   0.99\ndisk_free_limit.relative = 1.0\ncollect_statistics_interval =   10000\n"},"tls":{},"override":{"statefulSet":{"spec":{"template":{"spec":{"containers":[],"topologySpreadConstraints":[{"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"DoNotSchedule","labelSelector":
```

**Expected behavior**
reconciling should only happen for a reason.

## Version and environment information
- RabbitMQ: RabbitMQ 3.8.21
- RabbitMQ Cluster Operator: rabbitmqoperator/cluster-operator:1.10.0
- Kubernetes: 1.20.12
- Cloud provider or hardware configuration: GCP
 
## Additional context
A node version upgrade happened in a similar time.

Might be related to https://github.com/rabbitmq/cluster-operator/issues/826

Maintainer edit: log as a code block

**Comment by Zerpet** [comment]
Hey @dorshay6, can you share the manifest of your `RabbitmqCluster` ?

The reconcile loop triggers when there's an event (create, update, delete) on the `RabbitmqCluster`, or its owned resources i.e. StatefulSet, Services, ConfigMap, Secrets, etc. Another event that triggers reconcile is when the Operator Pod is recreated.

Did RabbitMQ pods restart as a consequence of those reconcile events?

**Comment by coro** [comment]
From looking at the reconcile logs here it looks like the manifest was:

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-ready
spec:
  replicas: 4
  image: rabbitmq:3.8.21-management
  service:
    type: LoadBalancer
    annotations:
      "cloud.google.com/load-balancer-type": Internal
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storage: "500Gi"
  terminationGracePeriodSeconds: 604800
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - production-ready
        topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: production-ready
```
