### ISSUE TITLE
Templating issue with prometheus-rules rabbitmq-unroutable-messages

### ISSUE THREAD

**Issue by ToadCast** [rabbitmq/cluster-operator#950]
## Describe the bug
When I'm trying to do the templating phase, I get an error about an undefined variable in the content of the rule.

## To Reproduce
1. Get the file `observability/prometheus/rules/rabbitmq/unroutable-messages.yml`
2. Add a file with your Helm values
3. Do a `helm template . --values [path-to-values-file]`
4. See error `Error: parse error at (monitoring-conf/templates/prometheus-rules/rabbitmq_unroutable-messages.yml:26): undefined variable "$value"`

I added some lines to the original file, here is how it exactly looks like while having the error:
```yaml
{{- if .Values.monitoring.app_enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rabbitmq-unroutable-messages
  namespace: "{{ .Values.monitoring.namespace }}"
  # If labels are defined in spec.ruleSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
  labels:
    role: alert-rules
    {{- toYaml .Values.global.labels | trim | nindent 4 }}
    {{- toYaml .Values.monitoring.prometheus_rules_labels | trim | nindent 4 }}
spec:
  groups:
  - name: rabbitmq
    rules:
    - alert: UnroutableMessages
      expr: |
        sum by(namespace, rabbitmq_cluster) (increase(rabbitmq_channel_messages_unroutable_dropped_total[5m]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info)
        >= 1
        or
        sum by(namespace, rabbitmq_cluster) (increase(rabbitmq_channel_messages_unroutable_returned_total[5m]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info)
        >= 1
      annotations:
        description: |
          There were `{{ $value | printf "%.0f" }}` unroutable messages within the last
          5 minutes in RabbitMQ cluster `{{ $labels.rabbitmq_cluster }}` in namespace
          `{{ $labels.namespace }}`.
        summary: |
          There are messages published into an exchange which cannot be routed and are either dropped silently, or returned to publishers.
          Is your routing topology set up correctly?
          Check your application code and bindings between exchanges and queues.
          See
          https://www.rabbitmq.com/publishers.html#unroutable,
          https://www.rabbitmq.com/confirms.html#when-publishes-are-confirmed.
      labels:
        rulesgroup: rabbitmq
        severity: warning
{{- end }}
```

You can notice I only added those:
```yaml
{{- if .Values.monitoring.app_enabled }}

  namespace: "{{ .Values.monitoring.namespace }}"

    {{- toYaml .Values.global.labels | trim | nindent 4 }}
    {{- toYaml .Values.monitoring.prometheus_rules_labels | trim | nindent 4 }}

{{- end }}
```

**Expected behavior**
Have the templating working, or failing for my added part if any errors are on my side.

## Version and environment information
- RabbitMQ: 3.8.23
- RabbitMQ Cluster Operator: 1.11.0-scratch-r0
- Kubernetes: 1.22.6
