### ISSUE TITLE
`initContainerMemory` and cpu should can be customize

### ISSUE THREAD

**Issue by jinleileiking** [rabbitmq/cluster-operator#960]
In the code:

```
initContainerMemory string = "500Mi"
```

This should can be modified in rabbitmq.yaml for using in test env.

**Comment by mkuratczyk** [comment]
How much lower do you expect to set it? While we could probably lower this value or make it configurable, I'm honestly not sure we'd like RabbitMQ deployed in environments with less than 0.5GB available. It's a recipe for very poor performance and overall experience of using RabbitMQ. Can you elaborate on your use case?

**Comment by jinleileiking** [comment]
In a test env，I only test for the function. In aws k8s 500M is a lot of money, so, I think configure this size is useful.

BTW, I can set the memory in rabbit container, why I can not set in rabbit-setup container.

Moreover， the init container will exit when it fininshed.

**Comment by mkuratczyk** [comment]
As you mentioned, this container exists for a very short time, so I really doubt you can save any significant amount of money by assigning less memory for it. If you really think it's valuable, you can actually customize it right now:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmqcluster
spec:
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            initContainers:
            - name: setup-container
              resources:
                limits:
                  memory: 250Mi
                requests:
                  memory: 250Mi
```
Just keep in mind that this container could need more memory in the future (I hope not, but we can't guarantee that).

If you know how much you can save by lowering this value, please let us know.
