### ISSUE TITLE
Rabbitmq cluster-operator extra annotations not taken into consideration

### ISSUE THREAD

**Issue by ZiedBenSaber** [rabbitmq/cluster-operator#961]
**Description :** 

Am trying to add extra annotations to our rabbitmq cluster-operator to be able to scrap it's logs like we are doing for every other tool / pod in our k8s cluster, but the following yaml doesn't propagate, nor apply any of the given annotations to the operator's child resources like stated here :
https://www.rabbitmq.com/kubernetes/operator/using-operator.html#labels-annotations

Am I doing it wrong, or is this a potential bug ?
Thanks in advance. 

**Here's the yaml :** 
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  image: docker.registry.company/rabbitmq:3.9.8-management
  imagePullSecrets:
  - name: secret
  replicas: {{ rabbitmq_replicas_number }}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmq-cluster
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: {{ rabbitmq_request_cpu }}
      memory: {{ rabbitmq_request_memory }}
    limits:
      cpu: {{ rabbitmq_limit_cpu }}
      memory: {{ rabbitmq_limit_memory }}
  rabbitmq:
    additionalConfig: |
      ## RabbitMQ configuration
      ## Ref: https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/docs/rabbitmq.conf.example
      total_memory_available_override_value = "{{ rabbitmq_tmaov }}"
      
      ## Memory-based Flow Control threshold.
      vm_memory_high_watermark.relative = "{{ rabbitmq_vmhwr }}"

      disk_free_limit.absolute = "{{ rabbitmq_dfla }}"

      listeners.tcp.default = "{{ rabbitmq_service_port }}"

      management.tcp.port = "{{ rabbitmq_service_managerPort }}"
      log.console.level = info

      ## Consumer timeout
      ## If a message delivered to a consumer has not been acknowledge before this timer
      ## triggers the channel will be force closed by the broker. This ensure that
      ## faultly consumers that never ack will not hold on to messages indefinitely.
      ## 4 hours in milliseconds
      consumer_timeout = 14400000

      default_vhost = /
      default_user= default_user 
      default_pass = "{{ rabbitmq_password }}"
      default_user_tags.administrator = true
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_shovel_management
      - rabbitmq_shovel
      - rabbitmq_top
      - rabbitmq_prometheus
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              co.elastic.logs/enabled: "true" # Using a string here is mandatory
              co.elastic.logs/module: rabbitmq
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: {{ rabbitmq_storage }}
              volumeMode: Filesystem
          spec:
            nodeSelector:
              k8s.scaleway.com/pool-name: services
```

**Comment by ChunyiLyu** [comment]
@ZiedBenSaber RabbitmqCluster annotations and labels are not populated to pod, which is documented in the doc you've linked to https://www.rabbitmq.com/kubernetes/operator/using-operator.html#labels-annotations (`The Pods do not inherit these labels and/or annotations.`)

You could use the statefulSet override to set labels/annotations to pods, just like what you are doing here. I don't know why it didn't work in your case. I was able to use yaml:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              co.elastic.logs/enabled: "true" # Using a string here is mandatory
              co.elastic.logs/module: rabbitmq
```

And saw the `co.elastic.logs` annotation in pod:

```
❯ k get pods rabbitmq-cluster-server-0 -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/module: rabbitmq
    prometheus.io/port: "15692"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-02-22T12:35:00Z"
```

If you still have the pod available, could you do a `kubectl get pods -oyaml` and share the pod manifest?
