### ISSUE TITLE
Modifying Service's annotations in CR does not delete removed annotations

### ISSUE THREAD

**Issue by hoyhbx** [rabbitmq/cluster-operator#968]
## Describe the bug
I was trying to modify the service's annotation via `/spec/service/annotations`. After changing a key-value pair in annotations from `key1: value1` to `key2: value2`, I noticed that the `key2: value2` is added under the Service's `metadata/annotations` correctly, but the `key1: value1` is still present.

## To Reproduce
Steps to reproduce this behavior:
1. Deploy cluster-operator using the command:
    ```kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml```
2. Deploy rabbitmqCluster with the following yaml file:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
spec:
  image: "rabbitmq:3.8.21-management"
  persistence:
    storage: 20Gi
  replicas: 2
  service:
    annotations:
      key1: value1
    type: ClusterIP
```
3. Use `kubectl apply` to apply the following changed yaml file. Note that the `/spec/service/annotations` is changed from `key1: value1` to `key2: value2`
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
spec:
  image: "rabbitmq:3.8.21-management"
  persistence:
    storage: 20Gi
  replicas: 2
  service:
    annotations:
      key2: value2
    type: ClusterIP
```
4. Use `kubectl get services sample -o yaml` to get the state of deployed service
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    key1: value1
    key2: value2
  creationTimestamp: "2022-02-15T23:40:25Z"
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: sample
    app.kubernetes.io/part-of: rabbitmq
...
```
**Note** that under the `/metadata/annotations` field, both `key1: value1` and `key2: value2` are present.

**Expected behavior**
After applying the change, the Service should not have the `key1: value1` annotation.

## Version and environment information
- RabbitMQ: rabbitmq:3.8.21-management
- RabbitMQ Cluster Operator: rabbitmqoperator/cluster-operator:1.10.0
- Kubernetes: 1.21.1
- Cloud provider or hardware configuration: Kind

## Additional context
The root cause seems to point to https://github.com/rabbitmq/cluster-operator/blob/f79f2a571077a89e47f6e8350a7adc4586138848/internal/metadata/annotation.go#L22
where the annotations get merged with existing ones.
