### ISSUE TITLE
Memory usage of Cluster Operator

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#978]
## Describe the bug

Our current memory request and limit for cluster operator is 500Mi. 
```
        name: operator
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
```

In one user's environment, we saw the operator periodically go over the 500Mi limit and getting OOM killed and restarted by k8s. 

## More information needed

1. User said they will collect and provide logs for the operator when it's getting restarted.
2. Ask how many rabbitmqclusters are in cluster for reconcile
**Expected behavior**

## Version and environment information
- RabbitMQ: 
- RabbitMQ Cluster Operator: 1.12
- Kubernetes: 1.19
- Cloud provider or hardware configuration: Openshift
