### ISSUE TITLE
Kubernetes 1.23.4 requires to prefix the docker hub image with docker.io

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#991]
@ChunyiLyu Hi, at Kubernetes 1.23.4 I noticed that it is required and best practice to prefix the docker hub image with docker.io/

This is the change for the two occurences of the image in the operator yaml:
```sh
image: rabbitmqoperator/cluster-operator:1.12.0
```
to this:
```sh
image: docker.io/rabbitmqoperator/cluster-operator:1.12.0
```
Could you change this please? :)

_Originally posted by @FischerLGLN in https://github.com/rabbitmq/cluster-operator/issues/945#issuecomment-1055564307_

**Comment by coro** [comment]
Hi @FischerLGLN, I don't see any release notes from Kubernetes stating this as a required or suggested change; where did you see this? In any case, I just tested on Kind 1.23.4 and couldn't reproduce. Let us know if you're still having issues!

**Comment by FischerLGLN** [comment]
Hi @coro 
Thanks for having tested :) 

I've setup a cluster with cluster-api and kubeadm and cilium without kube-proxy on hetzner and noticed on this 1.23.4 k8s version, that the docker.io registry wasn't set to standard. I thought that this would be a further consequence after the docker shim deprecation.

I don't want to override the image in the crd, because then I have to maintain the image updates myself:
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  image: docker.io/rabbitmq:3.9.13-management
```

Ah, maybe the reason is that I am using fedora 35 as vm for k8s. First noticed here: https://forums.docker.com/t/why-are-images-from-the-docker-hub-prefixed-with-docker-io-on-some-platforms-and-not-on-others/37083

So maybe it works in your kind environment, because it is not using Fedora??

**Comment by FischerLGLN** [comment]
@coro Or maybe it is related to crio instead of containerd? 

This is the install I am using:
https://github.com/syself/cluster-api-provider-hetzner/blob/0ba88c65f994c5ac1978e33993107ca4abd4109f/templates/cluster-template-hcloud-network.yaml

**Comment by coro** [comment]
I will give it a go on crio when I get a moment! In the meantime, if you'd like to override the image on the operator scope, but not modify the CRD, you could set the default image as an environment variable of the operator deployment: https://github.com/rabbitmq/cluster-operator/blob/36ced5fb108b3195f28ee03e9dbfdd1accb1c2e7/main.go#L75-L77

For example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: rabbitmq-cluster-operator
    app.kubernetes.io/part-of: rabbitmq
  name: rabbitmq-cluster-operator
  namespace: rabbitmq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: rabbitmq-cluster-operator
        app.kubernetes.io/part-of: rabbitmq
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DEFAULT_RABBITMQ_IMAGE
          value: "docker.io/rabbitmq:3.9-management"
...<rest of Deployment manifest>...
```

Note the tag `3.9-management`, which would always get the latest 3.9.x patch image for new clusters.
