### ISSUE TITLE
Changing storageClassName in CR does not change the PVC resource

### ISSUE THREAD

**Issue by hoyhbx** [rabbitmq/cluster-operator#992]
## Describe the bug
I was trying to change the `persistence/storageClassName` field in my rabbitmq-cluster's CR, but changing the `persistence/storageClassName` has no effect on the PVC used by the statefulSet. 
The `persistence/storageClassName` field was initially not specified so the operator used the default storage class "standard". Then I created a new storage class following instruction here https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/production-ready/ssd-gke.yaml, and changed `persistence/storageClassName` from `null` to `ssd`. This change failed silently.

## To Reproduce
Steps to reproduce this behavior:
1. Deploy cluster-operator using the command: 
```kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml```
2. Deploy rabbitmqCluster with the following yaml file:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
spec:
  image: "rabbitmq:3.8.21-management"
  persistence:
    storage: 20Gi
  replicas: 2
```
3. Create new storage class:
`kubectl apply -f https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/production-ready/ssd-gke.yaml`
4. Change the rabbitmqCluster's `persistence/storageClassName` to `ssd` and apply
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: sample
spec:
  image: "rabbitmq:3.8.21-management"
  persistence:
    storage: 20Gi
    storageClassName: ssd
  replicas: 2
```
5. Check the PVC used by rabbitmq cluster, the storageClassName change is not applied. It's still "standard" instead of "ssd":
```json
"spec": {
    "accessModes": [
        "ReadWriteOnce"
    ],
    "resources": {
        "requests": {
            "storage": "20Gi"
        }
    },
    "storageClassName": "standard",
    "volumeMode": "Filesystem",
    "volumeName": "pvc-43d66309-2090-4de3-bc82-9edcd0a69361"
}
```

**Expected behavior**
The PVC with the desired storage class being created to replace the old PVC.

## Version and environment information
- rabbitmq: rabbitmq:3.8.21-management
- rabbitmq cluster operator: rabbitmqoperator/cluster-operator:1.10.0
- Kubernetes: 1.21.1
- Running on Kind cluster
 
## Addition context
This bug is caused because the operator only reconciles the PVC's storage capacity, but does not reconcile the storageClassName here: https://github.com/rabbitmq/cluster-operator/blob/d657ffb516f948aaffd252794e3ed5e75e352d3d/controllers/reconcile_persistence.go#L15.

Possible fix is to create the desired storage type and migrate the data over. Or report an error message like PVC scaling down here: https://github.com/rabbitmq/cluster-operator/blob/d657ffb516f948aaffd252794e3ed5e75e352d3d/internal/scaling/scaling.go#L51
